export const MORAL_SYLLABUS = {
  self_help: [
    { id: 1, text: "Kiên trì sẽ luôn được đền đáp xứng đáng", desc: "Sức mạnh của việc không bỏ cuộc trước khó khăn" },
    { id: 2, text: "Kỷ luật bản thân là chìa khóa của tự do", desc: "Làm chủ hành động để làm chủ tương lai" },
    { id: 3, text: "Thất bại hôm nay là học phí cho thành công ngày mai", desc: "Xem trở ngại là cơ hội học hỏi quý giá" },
    { id: 4, text: "Mỗi ngày tiến bộ 1% sau một năm sẽ thay đổi kinh ngạc", desc: "Tích lũy những thay đổi nhỏ làm nên kỳ tích" },
    { id: 5, text: "Đừng so sánh chương 1 của mình với chương 20 của người khác", desc: "Tập trung vào hành trình của riêng bạn" },
    { id: 6, text: "Giới hạn duy nhất là những gì bạn tự đặt ra", desc: "Vượt qua rào cản tâm lý để bứt phá" },
    { id: 7, text: "Thức dậy với mục tiêu, đi ngủ với sự hài lòng", desc: "Sống có định hướng rõ ràng mỗi ngày" },
    { id: 8, text: "Thành công không đến từ sự ngẫu hứng, nó đến từ sự đều đặn", desc: "Giá trị của thói quen và sự nhất quán" },
    { id: 9, text: "Khi muốn bỏ cuộc, hãy nhớ lý do bạn bắt đầu", desc: "Định vị lại động lực cốt lõi khi mệt mỏi" },
    { id: 10, text: "Nỗi đau của sự kỷ luật nhẹ hơn nỗi đau của sự hối hận", desc: "Lựa chọn cái giá để trưởng thành" },
    { id: 11, text: "Bắt đầu từ nơi bạn đứng, sử dụng những gì bạn có", desc: "Hành động ngay thay vì chờ đợi sự hoàn hảo" },
    { id: 12, text: "Đừng đợi cơ hội xuất hiện, hãy tự tạo ra nó", desc: "Tinh thần chủ động nắm giữ vận mệnh" },
    { id: 13, text: "Bạn là trung bình cộng của 5 người bạn dành thời gian nhiều nhất", desc: "Lựa chọn môi trường và các mối quan hệ tích cực" },
    { id: 14, text: "Việc hôm nay chớ để ngày mai", desc: "Đập tan thói quen trì hoãn phá hủy cơ hội" },
    { id: 15, text: "Học cách nói không với những thứ làm xao nhãng mục tiêu", desc: "Bảo vệ sự tập trung của bản thân" },
    { id: 16, text: "Tập trung vào quá trình, kết quả tự khắc sẽ đến", desc: "Không nóng vội, làm tốt từng bước nhỏ" },
    { id: 17, text: "Sự kiên nhẫn có thể biến lá dâu thành tơ lụa", desc: "Thời gian là người đồng minh tốt nhất" },
    { id: 18, text: "Không có lối đi tắt nào cho những nơi thực sự đáng đến", desc: "Tôn trọng quy luật nhân quả của nỗ lực" },
    { id: 19, text: "Người kiên trì là người không bao giờ bị đánh bại", desc: "Sức mạnh ý chí bền bỉ theo năm tháng" },
    { id: 20, text: "Trực giác mách bảo con đường, hành động tạo ra đích đến", desc: "Kết hợp tư duy nhạy bén và hành động quyết liệt" },
    { id: 21, text: "Thói quen tốt tạo nên cuộc đời tốt", desc: "Xây dựng nền móng cuộc sống vững chắc" },
    { id: 22, text: "Hãy làm việc trong im lặng và để thành công lên tiếng", desc: "Hành động âm thầm tạo kết quả vang dội" },
    { id: 23, text: "Đừng sợ đi chậm, chỉ sợ đứng yên", desc: "Duy trì quán tính tiến bước mỗi ngày" },
    { id: 24, text: "Quản lý thời gian tốt là quản lý cuộc đời tốt", desc: "Tối ưu hóa tài nguyên quý giá nhất" },
    { id: 25, text: "Mọi thay đổi lớn đều bắt đầu từ một quyết định nhỏ", desc: "Dũng cảm thực hiện bước ngoặt đầu tiên" },
    { id: 26, text: "Khó khăn chỉ là phép thử cho lòng kiên nhẫn", desc: "Trui rèn bản lĩnh qua sóng gió" },
    { id: 27, text: "Đầu tư vào bản thân là khoản đầu tư sinh lời nhất", desc: "Nâng cao tri thức và kỹ năng sống" },
    { id: 28, text: "Thái độ tích cực quyết định độ cao của thành công", desc: "Nhìn nhận thế giới bằng lăng kính lạc quan" },
    { id: 29, text: "Muốn đi nhanh thì đi một mình, muốn đi xa hãy kiên trì", desc: "Đồng hành bền bỉ vượt thời gian" },
    { id: 30, text: "Vượt qua vùng an toàn là nơi phép màu bắt đầu", desc: "Thách thức bản thân ở lĩnh vực mới" },
    { id: 31, text: "Đừng cầu nguyện cho cuộc sống dễ dàng, hãy cầu nguyện để mạnh mẽ hơn", desc: "Tôi luyện nội lực vững vàng" },
    { id: 32, text: "Mọi thành quả lớn đều cần thời gian tích lũy", desc: "Không đốt cháy giai đoạn gieo trồng" },
    { id: 33, text: "Sự chú ý là tài sản quý giá nhất của bạn", desc: "Tránh xa cạm bẫy xao nhãng của công nghệ" },
    { id: 34, text: "Hãy là phiên bản tốt nhất của chính mình hôm nay", desc: "Chỉ cạnh tranh với chính mình hôm qua" },
    { id: 35, text: "Chiến thắng bản thân là chiến thắng hiển hách nhất", desc: "Kiểm soát phần lười biếng và bản năng" },
    { id: 36, text: "Đọc sách là cách nhanh nhất để đứng trên vai người khổng lồ", desc: "Khai thác kho tàng trí tuệ nhân loại" },
    { id: 37, text: "Nghĩ lớn, bắt đầu nhỏ, hành động ngay lập tức", desc: "Chiến thuật triển khai dự án hiệu quả" },
    { id: 38, text: "Mỗi vết sẹo đều mang lại một bài học trưởng thành", desc: "Chữa lành và đứng dậy mạnh mẽ hơn" },
    { id: 39, text: "Đừng lãng phí năng lượng vào những việc không thể thay đổi", desc: "Học cách buông bỏ và tập trung hiện tại" },
    { id: 40, text: "Sự tập trung là sức mạnh tối thượng", desc: "Dành toàn lực cho một mục tiêu duy nhất" },
    { id: 41, text: "Không có thất bại thực sự, chỉ có bài học kinh nghiệm", desc: "Thay đổi góc nhìn về những lần vấp ngã" },
    { id: 42, text: "Niềm tin là bước đi đầu tiên ngay cả khi chưa thấy toàn bộ cầu thang", desc: "Dũng cảm bước đi bằng niềm tin nội tâm" },
    { id: 43, text: "Làm chủ cảm xúc là làm chủ vận mệnh", desc: "Kiểm soát nóng giận để tránh sai lầm" },
    { id: 44, text: "Hãy kiên định với mục tiêu nhưng linh hoạt với phương pháp", desc: "Chiến lược thông minh để thích ứng khó khăn" },
    { id: 45, text: "Sự chuẩn bị gặp gỡ cơ hội sẽ tạo nên may mắn", desc: "Không ngừng tích lũy chờ ngày tỏa sáng" },
    { id: 46, text: "Tiền bạc đi sau giá trị trao đi", desc: "Tập trung cống hiến để nhận lại xứng đáng" },
    { id: 47, text: "Học hỏi từ người giỏi nhất để rút ngắn con đường", desc: "Tìm kiếm người cố vấn dẫn đường" },
    { id: 48, text: "Đừng sống một năm 75 lần và gọi đó là cuộc đời", desc: "Sống trải nghiệm và bứt phá thay vì lặp lại" },
    { id: 49, text: "Năng lượng tích cực sẽ thu hút những điều tích cực", desc: "Quy luật hấp dẫn của tâm thức" },
    { id: 50, text: "Hành trình vạn dặm bắt đầu từ một bước chân đầu tiên", desc: "Hành động nhỏ mở ra chặng đường lớn" }
  ],
  top_lists: [
    { id: 1, text: "Top 5 thứ tuyệt đối không nên làm khi đi du lịch nước ngoài", desc: "Tránh rắc rối luật pháp và văn hóa bản địa" },
    { id: 2, text: "Top 3 thói quen buổi sáng đang âm thầm hủy hoại sức khỏe của bạn", desc: "Thay đổi để bảo vệ năng lượng khởi đầu ngày mới" },
    { id: 3, text: "Top 4 hành động lịch sự nhưng lại cực kỳ mất điểm trong giao tiếp", desc: "Những hiểu lầm tai hại khi cố tỏ ra tế nhị" },
    { id: 4, text: "Top 5 quy tắc ngầm khi đi ăn tiệc xã giao bạn bắt buộc phải biết", desc: "Cách hành xử tinh tế giúp ghi điểm tuyệt đối" },
    { id: 5, text: "Top 3 sai lầm phổ biến khi mua đồ dùng gia đình gây lãng phí tiền bạc", desc: "Chi tiêu thông minh cho tổ ấm" },
    { id: 6, text: "Top 5 dấu hiệu cảnh báo một mối quan hệ độc hại cần tránh xa", desc: "Bảo vệ sức khỏe tinh thần của chính mình" },
    { id: 7, text: "Top 4 việc cần làm ngay lập tức khi phát hiện bị mất ví tiền", desc: "Xử lý khủng hoảng nhanh chóng, giảm thiểu thiệt hại" },
    { id: 8, text: "Top 3 sai lầm ngớ ngẩn khi phỏng vấn xin việc khiến bạn bị loại ngay", desc: "Những chi tiết nhỏ quyết định thành bại" },
    { id: 9, text: "Top 5 mẹo tiết kiệm tiền hiệu quả cho người trẻ thu nhập trung bình", desc: "Tích lũy tài sản thông minh và bền vững" },
    { id: 10, text: "Top 4 thứ không nên chia sẻ lên mạng xã hội để bảo vệ bản thân", desc: "Giữ an toàn thông tin cá nhân trên không gian số" },
    { id: 11, text: "Top 3 thói quen trước khi đi ngủ giúp bạn ngủ ngon và sâu giấc hơn", desc: "Cải thiện chất lượng giấc ngủ tự nhiên" },
    { id: 12, text: "Top 5 cách từ chối khéo léo mà không làm mất lòng người khác", desc: "Nghệ thuật từ chối nhẹ nhàng nhưng dứt khoát" },
    { id: 13, text: "Top 4 kỹ năng tự vệ cơ bản ai cũng cần biết khi đi một mình ban đêm", desc: "Đề phòng nguy hiểm và tự bảo vệ bản thân" },
    { id: 14, text: "Top 3 biểu hiện của người có EQ cao trong các cuộc tranh luận", desc: "Giao tiếp thuyết phục bằng sự điềm tĩnh" },
    { id: 15, text: "Top 5 thực phẩm quen thuộc tưởng tốt nhưng ăn nhiều lại gây hại", desc: "Cân nhắc chế độ dinh dưỡng lành mạnh" },
    { id: 16, text: "Top 4 thói quen mua sắm thông minh giúp bạn dư dả cuối tháng", desc: "Quản lý ngân sách mua sắm hiệu quả" },
    { id: 17, text: "Top 3 cách xử lý thông minh khi gặp khách hàng khó tính", desc: "Hóa giải mâu thuẫn, giữ chân khách hàng" },
    { id: 18, text: "Top 5 điều bạn nên chuẩn bị kỹ càng trước khi bước sang tuổi 30", desc: "Định hình sự nghiệp và tài chính vững vàng" },
    { id: 19, text: "Top 4 dấu hiệu cho thấy bạn đang bị quá tải công việc (Burnout)", desc: "Lắng nghe cơ thể và dành thời gian phục hồi" },
    { id: 20, text: "Top 3 quy tắc ứng xử khi mượn tiền hoặc đồ dùng của người khác", desc: "Giữ gìn uy tín và mối quan hệ tốt đẹp" },
    { id: 21, text: "Top 5 mẹo sắp xếp hành lý siêu gọn nhẹ khi đi du lịch dài ngày", desc: "Tối ưu hóa balo hành lý thông minh" },
    { id: 22, text: "Top 4 sai lầm khi chăm sóc da mặt khiến mụn nổi nhiều hơn", desc: "Điều chỉnh thói quen dưỡng da đúng cách" },
    { id: 23, text: "Top 3 việc nên làm ngay khi chuyển đến nơi ở mới", desc: "Bắt đầu cuộc sống mới suôn sẻ" },
    { id: 24, text: "Top 5 thói quen giúp bạn duy trì năng lượng tích cực suốt cả ngày", desc: "Nạp năng lượng cho tâm trí và thể chất" },
    { id: 25, text: "Top 4 ngôn ngữ cơ thể vô tình tố cáo sự thiếu tự tin của bạn", desc: "Điều chỉnh tư thế để giao tiếp hiệu quả" },
    { id: 26, text: "Top 3 lỗi sai phổ biến khi viết CV xin việc bạn cần sửa ngay", desc: "Gây ấn tượng mạnh mẽ với nhà tuyển dụng" },
    { id: 27, text: "Top 5 điều cấm kỵ khi nói chuyện với người mới quen lần đầu", desc: "Tránh tạo ấn tượng xấu ban đầu" },
    { id: 28, text: "Top 4 thói quen ăn uống đang làm chậm quá trình giảm cân của bạn", desc: "Tối ưu hóa chế độ dinh dưỡng hàng ngày" },
    { id: 29, text: "Top 3 cách đối phó với những lời chỉ trích tiêu cực từ đồng nghiệp", desc: "Xử lý thông minh trước thị phi công sở" },
    { id: 30, text: "Top 5 kỹ năng giao tiếp giúp bạn dễ dàng kết bạn ở môi trường mới", desc: "Hòa nhập nhanh chóng và tự nhiên" },
    { id: 31, text: "Top 4 đồ vật không nên để trong xe ô tô dưới trời nắng nóng", desc: "Phòng tránh cháy nổ và hỏng hóc đồ đạc" },
    { id: 32, text: "Top 3 quy tắc ngầm khi sử dụng thang máy ở nơi công sở", desc: "Lịch sự văn minh tại tòa nhà văn phòng" },
    { id: 33, text: "Top 5 thói quen chi tiêu đang khiến bạn mãi không có tiền tiết kiệm", desc: "Nhận diện những khoản chi vô ích ngầm" },
    { id: 34, text: "Top 4 việc nên làm trước khi quyết định đầu tư vào bất cứ lĩnh vực nào", desc: "Giảm thiểu rủi ro mất tiền oan" },
    { id: 35, text: "Top 3 dấu hiệu cho thấy điện thoại của bạn đang bị theo dõi", desc: "Bảo mật thông tin thiết bị cá nhân" },
    { id: 36, text: "Top 5 sai lầm khi quản lý tài chính cá nhân ở tuổi đôi mươi", desc: "Tránh nợ nần và xây dựng tài sản sớm" },
    { id: 37, text: "Top 4 cách rèn luyện tư duy phản biện trong học tập và công việc", desc: "Nâng cao năng lực phân tích vấn đề độc lập" },
    { id: 38, text: "Top 3 mẹo giúp giảm căng thẳng cực nhanh trong vòng 5 phút", desc: "Lấy lại bình tĩnh và cân bằng tức thì" },
    { id: 39, text: "Top 5 điều cần kiểm tra kỹ trước khi rời khỏi phòng khách sạn", desc: "Tránh bỏ quên tài sản quan trọng" },
    { id: 40, text: "Top 4 quy tắc an toàn khi sử dụng thẻ tín dụng để tránh mất tiền", desc: "Bảo vệ thông tin tài chính cá nhân" },
    { id: 41, text: "Top 3 thói quen giúp cải thiện trí nhớ cực kỳ hiệu quả", desc: "Rèn luyện bộ não sắc bén mỗi ngày" },
    { id: 42, text: "Top 5 việc không nên làm ngay sau khi ăn no để bảo vệ dạ dày", desc: "Bảo vệ hệ tiêu hóa hoạt động khỏe mạnh" },
    { id: 43, text: "Top 4 cách nhận biết một trang web lừa đảo trực tuyến", desc: "Tránh mất mát thông tin tài khoản và tiền bạc" },
    { id: 44, text: "Top 3 kỹ năng giao tiếp quan trọng nhất mà trường học không dạy bạn", desc: "Trang bị hành trang ứng xử thực tế cuộc sống" },
    { id: 45, text: "Top 5 món đồ công nghệ đáng tiền nhất giúp tăng hiệu suất làm việc", desc: "Lựa chọn công cụ hỗ trợ công việc thông minh" },
    { id: 46, text: "Top 4 sai lầm khi tập thể dục khiến bạn dễ bị chấn thương", desc: "Rèn luyện cơ thể an toàn và khoa học" },
    { id: 47, text: "Top 3 thói quen giúp giữ nhà cửa luôn gọn gàng mà không tốn công dọn", desc: "Duy trì không gian sống sạch sẽ tự động" },
    { id: 48, text: "Top 5 điều bạn sẽ hối hận nếu không làm khi còn trẻ", desc: "Sống trọn vẹn và ý nghĩa từng phút giây" },
    { id: 49, text: "Top 4 mẹo nói chuyện trước đám đông giúp bạn bớt run và tự tin hơn", desc: "Làm chủ bục giảng và thuyết trình cuốn hút" },
    { id: 50, text: "Top 3 quy tắc vàng khi thảo luận công việc nhóm để tránh xung đột", desc: "Làm việc nhóm hiệu quả và gắn kết" }
  ],
  rules_of_life: [
    { id: 1, text: "Quy tắc giao tiếp tế nhị với lãnh đạo khi bất đồng ý kiến", desc: "Trình bày quan điểm thông minh, tôn trọng cấp trên" },
    { id: 2, text: "Cách cư xử lịch thiệp khi nhận được món quà bạn không thích", desc: "Tôn trọng tấm lòng người tặng, ứng xử tinh tế" },
    { id: 3, text: "Quy tắc ứng xử khi đồng nghiệp nói xấu sau lưng người khác", desc: "Tránh xa thị phi và giữ thái độ trung lập chuyên nghiệp" },
    { id: 4, text: "Cách xử lý thông minh khi vô tình làm đổ đồ uống tại bữa tiệc", desc: "Giữ bình tĩnh, xử lý khéo léo để không gây chú ý tiêu cực" },
    { id: 5, text: "Quy tắc giới thiệu người khác trong lần đầu gặp mặt xã giao", desc: "Thứ tự giới thiệu tôn trọng cấp bậc và tuổi tác" },
    { id: 6, text: "Quy tắc vàng khi trả lời điện thoại trong không gian làm việc chung", desc: "Giữ âm lượng vừa phải, tôn trọng sự tập trung của đồng nghiệp" },
    { id: 7, text: "Cách ứng xử khéo léo khi bị người khác hỏi những câu hỏi quá riêng tư", desc: "Đánh lạc hướng nhẹ nhàng, bảo vệ không gian cá nhân" },
    { id: 8, text: "Quy tắc ăn uống lịch sự khi đi ăn tối cùng đối tác làm ăn", desc: "Những cử chỉ bàn ăn tối thiểu của người lịch thiệp" },
    { id: 9, text: "Cách cư xử văn minh khi xếp hàng ở nơi công cộng bị chen hàng", desc: "Nhắc nhở nhẹ nhàng, giữ bình tĩnh ứng xử" },
    { id: 10, text: "Quy tắc ứng xử khi bạn trễ hẹn để giữ uy tín cá nhân", desc: "Thông báo sớm, xin lỗi chân thành và đề xuất giải pháp" },
    { id: 11, text: "Cách xin lỗi chân thành và chuyên nghiệp trong công việc", desc: "Nhận trách nhiệm và đưa ra kế hoạch khắc phục rõ ràng" },
    { id: 12, text: "Quy tắc chúc mừng đồng nghiệp được thăng chức mà không mang tiếng nịnh bợ", desc: "Chúc mừng chân thành dựa trên thành quả thực tế" },
    { id: 13, text: "Cách cư xử khi bạn là người duy nhất không đồng tình trong cuộc họp", desc: "Trình bày lý do logic thay vì tranh cãi cảm xúc" },
    { id: 14, text: "Quy tắc gửi email công việc chuyên nghiệp và lịch sự", desc: "Bố cục rõ ràng, câu từ ngắn gọn và tôn trọng" },
    { id: 15, text: "Cách ứng xử khi bạn vô tình nghe thấy bí mật của sếp hoặc đồng nghiệp", desc: "Giữ im lặng tuyệt đối, tập trung vào công việc riêng" },
    { id: 16, text: "Quy tắc ứng xử khi đi nhờ xe của người khác để luôn được chào đón", desc: "Lịch sự, chủ động chia sẻ chi phí và giữ vệ sinh xe" },
    { id: 17, text: "Cách cư xử tinh tế khi từ chối lời mời ăn tối từ đối tác", desc: "Nêu lý do hợp lý và đề xuất một lịch hẹn phù hợp khác" },
    { id: 18, text: "Quy tắc giao tiếp bằng mắt để tạo lòng tin mà không gây khó chịu", desc: "Nghệ thuật duy trì ánh mắt tự nhiên và vừa vặn" },
    { id: 19, text: "Cách ứng xử khi bạn nhận ra mình đã nói sai điều gì đó trong cuộc trò chuyện", desc: "Chủ động đính chính nhẹ nhàng, tiếp tục mạch truyện" },
    { id: 20, text: "Quy tắc ứng xử khi sử dụng mạng xã hội của công ty", desc: "Bảo vệ uy tín tập thể và hình ảnh thương hiệu công việc" },
    { id: 21, text: "Cách cư xử lịch sự khi nhận được lời khen ngợi từ cấp trên", desc: "Đón nhận khiêm tốn và chia sẻ thành tích cùng đội ngũ" },
    { id: 22, text: "Quy tắc thảo luận về lương thưởng một cách khéo léo với nhân sự", desc: "Chuẩn bị dẫn chứng giá trị đóng góp thay vì đòi hỏi cảm tính" },
    { id: 23, text: "Cách phản hồi lịch sự trước những lời khuyên không mong muốn", desc: "Cảm ơn lịch sự và giữ vững quan điểm riêng" },
    { id: 24, text: "Quy tắc ứng xử khi bạn cần mượn văn phòng phẩm của đồng nghiệp", desc: "Xin phép trước, hoàn trả đúng hẹn và bảo quản tốt" },
    { id: 25, text: "Cách cư xử đúng mực khi tham gia chuyến dã ngoại của công ty", desc: "Thoải mái giao lưu nhưng giữ chừng mực chuyên nghiệp" },
    { id: 26, text: "Quy tắc bắt tay lịch sự và tự tin trong các cuộc gặp gỡ đối tác", desc: "Cường độ và thời gian bắt tay tạo thiện cảm tốt" },
    { id: 27, text: "Cách ứng xử khi bạn gặp lại người quen cũ nhưng quên mất tên họ", desc: "Chào hỏi nồng nhiệt và khéo léo hỏi lại thông tin" },
    { id: 28, text: "Quy tắc chia sẻ tủ lạnh chung và lò vi sóng tại văn phòng", desc: "Tôn trọng đồ ăn của người khác, dọn dẹp sau khi dùng" },
    { id: 29, text: "Cách cư xử văn minh khi tài xế công nghệ đi sai đường hoặc thái độ kém", desc: "Phản hồi nhẹ nhàng thông qua đánh giá ứng dụng" },
    { id: 30, text: "Quy tắc ứng xử khi bạn muốn xin nghỉ phép đột xuất vì việc gia đình", desc: "Bàn giao công việc rõ ràng, xin lỗi vì sự bất tiện" },
    { id: 31, text: "Cách xử lý khi bạn bị sếp phê bình trực tiếp trước mặt đồng nghiệp", desc: "Lắng nghe cầu thị, giải thích riêng tư sau cuộc họp" },
    { id: 32, text: "Quy tắc ứng xử khi tham dự một đám tang hoặc lễ chia buồn", desc: "Kính cẩn, trang phục trang nhã, tránh cười đùa xôn xao" },
    { id: 33, text: "Cách cư xử khi bạn muốn nhờ đồng nghiệp giúp đỡ công việc cá nhân", desc: "Hỏi ý kiến lịch sự, không ép buộc và sẵn sàng hỗ trợ lại" },
    { id: 34, text: "Quy tắc lịch sự khi sử dụng tai nghe tại văn phòng làm việc", desc: "Vẫn chú ý xung quanh khi đồng nghiệp cần gọi" },
    { id: 35, text: "Cách từ chối uống rượu bia tại các bữa tiệc công việc một cách khéo léo", desc: "Nêu lý do sức khỏe hoặc lái xe an toàn thuyết phục" },
    { id: 36, text: "Quy tắc chúc mừng sinh nhật sếp một cách tinh tế và trang trọng", desc: "Lời chúc lịch thiệp, ý nghĩa và tránh phô trương" },
    { id: 37, text: "Cách ứng xử khi bạn phát hiện lỗi sai trong báo cáo của đồng nghiệp", desc: "Góp ý riêng tư nhẹ nhàng để đồng nghiệp tự sửa" },
    { id: 38, text: "Quy tắc ứng xử khi bạn muốn rời khỏi một cuộc trò chuyện tẻ nhạt", desc: "Khéo léo lấy lý do công việc hoặc nước uống để ngắt mạch" },
    { id: 39, text: "Cách cư xử tinh tế khi đi ăn cùng nhóm và chia hóa đơn", desc: "Chủ động thanh toán phần của mình sòng phẳng, nhanh chóng" },
    { id: 40, text: "Quy tắc phản hồi tin nhắn công việc ngoài giờ hành chính", desc: "Thiết lập ranh giới lịch sự cho cuộc sống cá nhân" },
    { id: 41, text: "Cách ứng xử khi bạn nhận được phản hồi tiêu cực từ khách hàng", desc: "Lắng nghe khiếu nại, xoa dịu cảm xúc và đưa ra hướng xử lý" },
    { id: 42, text: "Quy tắc lịch sự khi mượn sách hoặc tài liệu của người khác", desc: "Bảo quản sạch sẽ, trả lại đúng thời gian đã hứa" },
    { id: 43, text: "Cách cư xử khi bạn phải làm việc nhóm với người bạn không thích", desc: "Đặt công việc lên trên cảm xúc cá nhân" },
    { id: 44, text: "Quy tắc ứng xử khi bạn muốn phản bác ý kiến của sếp trong cuộc họp", desc: "Đưa ra bằng chứng khách quan thay vì phản đối chủ quan" },
    { id: 45, text: "Cách cư xử lịch tế khi đi thang máy cùng ban lãnh đạo công ty", desc: "Chào hỏi lễ phép, nhường đường sếp đi trước" },
    { id: 46, text: "Quy tắc giữ khoảng cách cá nhân phù hợp khi nói chuyện xã giao", desc: "Tránh đứng quá gần gây ngột ngạt cho người đối diện" },
    { id: 47, text: "Cách ứng xử khi đồng nghiệp mượn đồ nhưng quên trả nhiều lần", desc: "Nhắc nhở hài hước nhẹ nhàng để lấy lại món đồ" },
    { id: 48, text: "Quy tắc ứng xử văn minh khi sử dụng nhà vệ sinh chung nơi công sở", desc: "Giữ gìn vệ sinh chung, tôn trọng không gian tập thể" },
    { id: 49, text: "Cách cư xử tinh tế khi sếp mời cơm thân mật tại nhà riêng", desc: "Đến đúng giờ, có món quà nhỏ chào chủ nhà" },
    { id: 50, text: "Quy tắc vàng để duy trì ranh giới chuyên nghiệp giữa công việc và đời tư", desc: "Sắp xếp thời gian cân bằng và tránh chia sẻ quá đà" }
  ],
  // ---------------------------------------------------------------------------------------------
  // 6 nhóm dưới đây nhắm ĐÚNG người xem 15-30 tuổi (Gen Z Việt). Khác 3 nhóm trên ở chỗ: mỗi chủ
  // đề là một TÌNH HUỐNG CỤ THỂ người xem đang sống trong đó (ở trọ, lương đầu tiên, bị so sánh,
  // deadline, bị ghost) chứ không phải một châm ngôn trừu tượng — và tiêu đề tự mang sẵn "khoảng
  // trống tò mò" (con số + điều chưa ai nói ra) để người xem phải nghe đến hết mới biết đủ.
  // Xem moralThemes.js để biết nhóm nào dùng văn phong nào (reflective/list).
  // ---------------------------------------------------------------------------------------------
  harsh_truths: [
    { id: 1, text: "7 sự thật về tiền mà trường học không bao giờ dạy bạn", desc: "Những điều chỉ vỡ ra khi tự đi làm kiếm sống" },
    { id: 2, text: "6 điều bạn tưởng là bạn thân, thật ra chỉ là người quen", desc: "Phân biệt bạn thật và bạn theo hoàn cảnh" },
    { id: 3, text: "5 sự thật phũ phàng sau câu \"cứ cố gắng rồi sẽ thành công\"", desc: "Vì sao nỗ lực sai hướng chỉ làm bạn kiệt sức" },
    { id: 4, text: "7 lý do người thật thà thường là người thiệt nhất", desc: "Tử tế cần đi kèm ranh giới và sự tỉnh táo" },
    { id: 5, text: "5 điều lộ ra ngay khi bạn hết tiền", desc: "Khủng hoảng tài chính bóc trần mọi mối quan hệ" },
    { id: 6, text: "6 sự thật về đi làm mà không ai nói trước khi bạn ra trường", desc: "Khoảng cách giữa giảng đường và công sở thật" },
    { id: 7, text: "5 kiểu người nên rời xa trước khi bạn 25 tuổi", desc: "Cắt bớt những người kéo bạn đứng yên" },
    { id: 8, text: "7 điều người ta chỉ tôn trọng khi bạn có nó", desc: "Sự thật về cách xã hội định giá một con người" },
    { id: 9, text: "6 sự thật về mạng xã hội đang khiến bạn tự thấy mình kém cỏi", desc: "Cơ chế so sánh ngầm phá hủy lòng tự tin" },
    { id: 10, text: "5 lý do càng dễ tính thì càng bị coi nhẹ", desc: "Vì sao người không có giới hạn luôn bị vượt qua" },
    { id: 11, text: "7 điều tuyệt đối không kể cho ai, kể cả người thân nhất", desc: "Giữ lại phần riêng để bảo vệ chính mình" },
    { id: 12, text: "6 sự thật về gia đình mà lớn lên rồi mới hiểu", desc: "Thương yêu và tổn thương có thể cùng tồn tại" },
    { id: 13, text: "5 kiểu giúp người khiến bạn mất cả tiền lẫn bạn", desc: "Giúp đúng cách để không mất cả hai" },
    { id: 14, text: "7 sự thật về tình yêu tuổi 20 mà sau 30 mới thấm", desc: "Những điều lúc đó tưởng là cả thế giới" },
    { id: 15, text: "6 lý do người ít nói lại là người bạn nên dè chừng", desc: "Im lặng không đồng nghĩa với vô hại" },
    { id: 16, text: "5 thứ bạn mất dần khi sống chỉ để làm vui lòng người khác", desc: "Cái giá thật của việc không dám từ chối" },
    { id: 17, text: "7 sự thật về đại học mà không ai chịu nói thẳng với bạn", desc: "Tấm bằng không phải tấm vé bảo đảm" },
    { id: 18, text: "6 dấu hiệu bạn đang bị lợi dụng bởi chính người quen", desc: "Nhận ra sự nhờ vả đã thành khai thác" },
    { id: 19, text: "5 sự thật về cái nghèo mà người chưa từng thiếu tiền không hiểu", desc: "Thiếu tiền lấy đi cả lựa chọn và lòng tự trọng" },
    { id: 20, text: "7 thứ thay đổi trong bạn sau lần đầu bị phản bội", desc: "Trưởng thành đắt giá sau một vết nứt" },
    { id: 21, text: "6 lý do người giỏi vẫn thất nghiệp còn người biết nói chuyện thì không", desc: "Năng lực cần được người khác nhìn thấy" },
    { id: 22, text: "5 sự thật về việc \"làm công việc mình thích\" mà nghe xong bạn sẽ tỉnh", desc: "Đam mê không tự trả tiền thuê nhà" },
    { id: 23, text: "7 điều bạn chỉ nhận ra khi tự đi làm kiếm tiền", desc: "Đồng tiền đầu tiên dạy nhiều hơn 4 năm học" },
    { id: 24, text: "6 sự thật về lòng tốt mà bạn phải biết trước khi cho đi", desc: "Cho đi cần kèm hiểu biết, không chỉ cảm xúc" },
    { id: 25, text: "5 lý do bạn càng giải thích thì người ta càng không hiểu", desc: "Khi nào nên nói và khi nào nên dừng" },
    { id: 26, text: "7 sự thật về việc sống một mình ở thành phố lớn", desc: "Tự do đi kèm nỗi cô đơn không ai chuẩn bị trước" },
    { id: 27, text: "6 điều người ta nói sau lưng bạn khi bạn bắt đầu khá lên", desc: "Thành công luôn kéo theo bình luận" },
    { id: 28, text: "5 sự thật về việc vay tiền bạn bè mà ai cũng nên biết trước", desc: "Tiền vào giữa là tình bạn phải chịu tải" },
    { id: 29, text: "7 dấu hiệu bạn đang ở sai môi trường mà cứ tưởng mình kém", desc: "Đôi khi vấn đề là cái ao, không phải con cá" },
    { id: 30, text: "6 sự thật cho thấy học giỏi không đồng nghĩa với sống tốt", desc: "Điểm số không dạy cách xử lý cuộc đời" },
    { id: 31, text: "5 lý do những người bênh bạn to nhất lại rời đi trước nhất", desc: "Ồn ào lúc đầu thường ngắn hơi nhất" },
    { id: 32, text: "7 sự thật về công việc mà sinh viên chưa hình dung được", desc: "Đi làm không giống làm bài tập nhóm" },
    { id: 33, text: "6 điều bạn sẽ hiểu ngay sau lần đầu bị cho thôi việc", desc: "Không ai không thể thay thế, kể cả bạn" },
    { id: 34, text: "5 sự thật về tình bạn sau khi rời ghế nhà trường", desc: "Bạn bè thật sự lộ ra khi không còn chung lớp" },
    { id: 35, text: "7 lý do nói ít lại khiến người khác coi trọng bạn hơn", desc: "Giá trị của sự tiết chế trong giao tiếp" },
    { id: 36, text: "6 sự thật về hẹn hò online mà không ai cảnh báo bạn", desc: "Điều màn hình không bao giờ cho bạn thấy" },
    { id: 37, text: "5 điều khiến người ta đổi thái độ với bạn chỉ trong một ngày", desc: "Sự tôn trọng mong manh hơn bạn nghĩ" },
    { id: 38, text: "7 sự thật về sự công bằng mà càng lớn càng thấy rõ", desc: "Học cách chơi tiếp khi luật không công bằng" },
    { id: 39, text: "6 lý do bạn không nên kể kế hoạch của mình cho ai", desc: "Nói ra sớm làm cạn động lực và mở đường cho phá" },
    { id: 40, text: "5 sự thật về việc sống thử trước khi cưới", desc: "Điều chỉ hiện ra khi ở cùng một mái nhà" },
    { id: 41, text: "7 điều bạn tưởng là trưởng thành, thật ra chỉ là chịu đựng", desc: "Phân biệt bản lĩnh và sự cam chịu" },
    { id: 42, text: "6 sự thật về áp lực gia đình mà đứa con lớn nào cũng gánh", desc: "Trách nhiệm không ai chọn nhưng phải mang" },
    { id: 43, text: "5 dấu hiệu bạn đang tự phá hỏng cơ hội của chính mình", desc: "Kẻ cản đường lớn nhất thường ở bên trong" },
    { id: 44, text: "7 sự thật về sức khỏe mà tuổi 20 luôn coi nhẹ", desc: "Cơ thể ghi nợ và sẽ đòi vào tuổi 30" },
    { id: 45, text: "6 điều người trưởng thành học được từ những lần bị từ chối", desc: "Lời từ chối là dữ liệu, không phải bản án" },
    { id: 46, text: "5 sự thật về việc làm thêm khi còn là sinh viên", desc: "Đánh đổi thời gian sao cho không lỗ" },
    { id: 47, text: "7 lý do người ta chọn kẻ biết nói hơn người biết làm", desc: "Vì sao im lặng làm việc là chưa đủ" },
    { id: 48, text: "6 sự thật về việc bị so sánh với \"con nhà người ta\"", desc: "Thoát khỏi thước đo của người khác" },
    { id: 49, text: "5 điều bạn chỉ hiểu sau khi mất đi một người quan trọng", desc: "Bài học đến quá muộn để kịp nói ra" },
    { id: 50, text: "7 sự thật về sự cô đơn ở tuổi 20 mà ai cũng che giấu", desc: "Đông bạn trên mạng vẫn trống rỗng ngoài đời" }
  ],
  mind_reading: [
    { id: 1, text: "7 dấu hiệu cho thấy một người đang nói dối bạn", desc: "Đọc mâu thuẫn giữa lời nói và hành vi" },
    { id: 2, text: "6 câu nói tiết lộ người đó không thật lòng với bạn", desc: "Nghe kỹ những câu nghe rất tử tế" },
    { id: 3, text: "5 cách nhận ra ai đang giả vờ tốt với bạn", desc: "Tử tế có điều kiện luôn để lại dấu vết" },
    { id: 4, text: "7 hành vi cho thấy một người có EQ rất cao", desc: "Người điềm tĩnh xử lý xung đột thế nào" },
    { id: 5, text: "6 dấu hiệu bạn đang bị thao túng cảm xúc", desc: "Nhận diện khi cảm giác tội lỗi bị dùng làm vũ khí" },
    { id: 6, text: "5 ngôn ngữ cơ thể tố cáo bạn đang thiếu tự tin", desc: "Sửa tư thế để đổi cách người khác nhìn bạn" },
    { id: 7, text: "7 dấu hiệu một người thật sự thích bạn mà không nói ra", desc: "Hành vi luôn nói trước lời tỏ tình" },
    { id: 8, text: "6 kiểu im lặng và ý nghĩa thật đằng sau mỗi kiểu", desc: "Không phải sự im lặng nào cũng giống nhau" },
    { id: 9, text: "5 câu hỏi giúp bạn đọc được tính cách người mới gặp", desc: "Hỏi đúng chỗ để thấy con người thật" },
    { id: 10, text: "7 dấu hiệu người đó đang ghen tị với bạn", desc: "Lời khen có gai và sự cạnh tranh ngầm" },
    { id: 11, text: "6 hành vi nhỏ tiết lộ một người được nuôi dạy tử tế", desc: "Nếp nhà hiện ra ở chi tiết vụn vặt" },
    { id: 12, text: "5 dấu hiệu bạn chỉ là phương án dự phòng của người ta", desc: "Khi bạn luôn được nhớ tới lúc rảnh" },
    { id: 13, text: "7 cách nhận ra người có nội tâm mạnh mẽ", desc: "Sức mạnh thật thường rất lặng lẽ" },
    { id: 14, text: "6 dấu hiệu cuộc trò chuyện đang dẫn bạn vào bẫy", desc: "Nhận ra khi bị dò thông tin và rút lui" },
    { id: 15, text: "5 kiểu người luôn tỏ ra bận rộn nhưng chẳng làm gì", desc: "Phân biệt hiệu suất thật và diễn xuất" },
    { id: 16, text: "7 dấu hiệu bạn đang nói quá nhiều về bản thân", desc: "Vì sao người nghe giỏi luôn được nhớ tới" },
    { id: 17, text: "6 biểu hiện của người đang giả vờ mình ổn", desc: "Nhìn ra người cần giúp trước khi quá muộn" },
    { id: 18, text: "5 dấu hiệu cho thấy người đó tôn trọng bạn thật sự", desc: "Tôn trọng thể hiện bằng hành động nhỏ" },
    { id: 19, text: "7 câu nói của người thiếu tự tin mà họ không nhận ra", desc: "Thói quen tự hạ giá trong lời nói" },
    { id: 20, text: "6 dấu hiệu người đó đang lợi dụng lòng tốt của bạn", desc: "Khi sự nhờ vả không còn có đi có lại" },
    { id: 21, text: "5 cách đọc cảm xúc thật qua đôi mắt", desc: "Ánh mắt phản ứng nhanh hơn lời nói" },
    { id: 22, text: "7 dấu hiệu bạn vừa gặp một người rất thông minh", desc: "Trí tuệ thật thường không cần chứng minh" },
    { id: 23, text: "6 hành vi cho thấy người đó bất an trong tình cảm", desc: "Kiểm soát thường sinh ra từ nỗi sợ" },
    { id: 24, text: "5 dấu hiệu ai đó đang muốn kết thúc cuộc nói chuyện", desc: "Biết dừng đúng lúc là một kỹ năng" },
    { id: 25, text: "7 kiểu tin nhắn tiết lộ mức độ quan tâm thật của người ta", desc: "Cách trả lời nói nhiều hơn nội dung" },
    { id: 26, text: "6 dấu hiệu người đó đang nói xấu bạn với người khác", desc: "Đọc sự thay đổi trong thái độ nhóm" },
    { id: 27, text: "5 cách nhận ra người đang cố tỏ ra giàu có", desc: "Người có thật thường không cần trưng ra" },
    { id: 28, text: "7 dấu hiệu bạn đang bị đối xử như người ngoài trong nhóm", desc: "Nhận ra sự loại trừ ngấm ngầm" },
    { id: 29, text: "6 biểu hiện của người có lòng tự trọng cao", desc: "Không cần hạ ai xuống để đứng cao hơn" },
    { id: 30, text: "5 dấu hiệu người đó chỉ giả vờ nghe bạn nói", desc: "Lắng nghe thật để lại phản hồi cụ thể" },
    { id: 31, text: "7 kiểu phản ứng khi bị chỉ trích và ý nghĩa từng kiểu", desc: "Bản lĩnh hiện ra rõ nhất lúc bị phê bình" },
    { id: 32, text: "6 dấu hiệu người đó đang chịu đựng chứ không hạnh phúc", desc: "Nụ cười không phải bằng chứng của ổn" },
    { id: 33, text: "5 cách nhận biết người dễ nổi giận trước khi quá muộn", desc: "Đọc tín hiệu cảnh báo sớm để tránh va chạm" },
    { id: 34, text: "7 dấu hiệu sự tử tế của bạn đang bị hiểu thành dễ dãi", desc: "Đặt lại ranh giới trước khi bị vượt qua" },
    { id: 35, text: "6 biểu hiện của người đang che giấu nỗi buồn rất sâu", desc: "Học cách hỏi đúng câu vào đúng lúc" },
    { id: 36, text: "5 dấu hiệu cho thấy một người thật sự trưởng thành", desc: "Trưởng thành đo bằng cách xử lý, không bằng tuổi" },
    { id: 37, text: "7 câu nói thao túng thường gặp và cách đáp lại", desc: "Có sẵn câu trả lời để không bị dồn ép" },
    { id: 38, text: "6 dấu hiệu bạn đang ở trong một nhóm bạn độc hại", desc: "Khi ở cùng nhóm mà luôn thấy mình tệ đi" },
    { id: 39, text: "5 cách nhận ra người thích kiểm soát người khác", desc: "Quan tâm quá mức có thể là lồng giam" },
    { id: 40, text: "7 dấu hiệu người đó coi bạn là đối thủ chứ không phải bạn", desc: "Cạnh tranh ngầm trong vỏ bọc thân thiết" },
    { id: 41, text: "6 biểu hiện của người từng thiếu yêu thương khi còn nhỏ", desc: "Hiểu để bao dung thay vì phán xét" },
    { id: 42, text: "5 dấu hiệu bạn đang tự hạ giá mình trong giao tiếp", desc: "Bỏ thói quen xin lỗi trước khi nói" },
    { id: 43, text: "7 kiểu người bạn sẽ gặp ở bất kỳ công ty nào", desc: "Nhận diện sớm để chọn cách làm việc phù hợp" },
    { id: 44, text: "6 dấu hiệu một lời xin lỗi là thật lòng", desc: "Xin lỗi thật đi kèm thay đổi hành vi" },
    { id: 45, text: "5 cách nhận ra người chỉ nói mà không bao giờ làm", desc: "Đừng đầu tư niềm tin vào lời hứa suông" },
    { id: 46, text: "7 dấu hiệu bạn đang được người khác âm thầm tôn trọng", desc: "Sự tôn trọng thật ít khi được nói ra" },
    { id: 47, text: "6 biểu hiện cho thấy người đó đang quá tải nhưng không nói", desc: "Nhận ra kiệt sức ở người bên cạnh" },
    { id: 48, text: "5 dấu hiệu một mối quan hệ đang nguội dần", desc: "Nhìn thấy sớm để kịp cứu hoặc kịp đi" },
    { id: 49, text: "7 điều cách người ta đối xử với người phục vụ nói lên về họ", desc: "Nhân cách lộ ra khi không cần diễn" },
    { id: 50, text: "6 dấu hiệu bạn nên ngừng tin một người ngay lập tức", desc: "Giới hạn cuối cùng của sự tin tưởng" }
  ],
  money_youth: [
    { id: 1, text: "7 sai lầm về tiền khiến người trẻ mãi không dư đồng nào", desc: "Vì sao lương tăng mà tài khoản vẫn trống" },
    { id: 2, text: "5 khoản chi âm thầm ăn hết lương của bạn mỗi tháng", desc: "Những khoản nhỏ cộng lại thành con số lớn" },
    { id: 3, text: "6 việc cần làm ngay khi nhận tháng lương đầu tiên", desc: "Đặt nền nếp tài chính từ đồng đầu tiên" },
    { id: 4, text: "7 lý do bạn kiếm nhiều hơn nhưng vẫn không giàu hơn", desc: "Cái bẫy nâng cấp lối sống theo thu nhập" },
    { id: 5, text: "5 thứ đừng bao giờ mua bằng tiền đi vay", desc: "Phân biệt nợ tạo giá trị và nợ tiêu dùng" },
    { id: 6, text: "6 dấu hiệu bạn đang tiêu tiền để chữa lành cảm xúc", desc: "Mua sắm không lấp được khoảng trống bên trong" },
    { id: 7, text: "7 quy tắc quản lý tiền cho người lương dưới 10 triệu", desc: "Thu nhập nhỏ vẫn có thể tích lũy được" },
    { id: 8, text: "5 sai lầm khi mua điện thoại mới khiến bạn hối hận", desc: "Cân nhắc nhu cầu thật trước khi xuống tiền" },
    { id: 9, text: "6 điều cần biết trước khi thuê trọ ở một mình", desc: "Chi phí ẩn không ai nói trước với bạn" },
    { id: 10, text: "7 kiểu bạn bè khiến bạn tiêu tiền nhiều nhất", desc: "Áp lực chi tiêu đến từ vòng bạn bè" },
    { id: 11, text: "5 cách từ chối khéo khi bạn bè rủ đi chơi mà bạn hết tiền", desc: "Giữ mặt và giữ ví cùng lúc" },
    { id: 12, text: "6 sai lầm khi cho bạn bè vay tiền", desc: "Cách cho vay mà không mất bạn" },
    { id: 13, text: "7 khoản bạn nên có trong tay trước tuổi 25", desc: "Bộ khung tài chính tối thiểu của người trẻ" },
    { id: 14, text: "5 dấu hiệu bạn đang sống vượt quá khả năng của mình", desc: "Nhận ra trước khi nợ chồng lên nợ" },
    { id: 15, text: "6 cách tăng thu nhập mà sinh viên có thể làm ngay", desc: "Kiếm thêm mà không bỏ học giữa đường" },
    { id: 16, text: "7 sai lầm khi bắt đầu đầu tư với số tiền nhỏ", desc: "Học trước khi xuống tiền để không mất oan" },
    { id: 17, text: "5 lý do trả góp 0% vẫn khiến bạn nghèo đi", desc: "Cái giá thật nằm ở thói quen chi tiêu" },
    { id: 18, text: "6 câu cần hỏi trước khi nhận một công việc lương cao", desc: "Lương cao đôi khi trả bằng sức khỏe" },
    { id: 19, text: "7 thói quen tiêu tiền của người luôn dư cuối tháng", desc: "Kỷ luật nhỏ tạo khoảng đệm tài chính" },
    { id: 20, text: "5 dấu hiệu bạn đang bị mời vào một mô hình lừa đảo", desc: "Nhận ra lời hứa lợi nhuận bất thường" },
    { id: 21, text: "6 khoản chi cho bản thân luôn đáng từng đồng", desc: "Đầu tư vào sức khỏe, kỹ năng và giấc ngủ" },
    { id: 22, text: "7 lý do phải có quỹ dự phòng trước khi đầu tư", desc: "Tấm đệm giúp bạn không phải bán lỗ" },
    { id: 23, text: "5 sai lầm khi mua chiếc xe máy đầu tiên", desc: "Tính cả chi phí nuôi xe, không chỉ giá mua" },
    { id: 24, text: "6 cách tiết kiệm mà không phải sống khổ", desc: "Cắt đúng chỗ để vẫn sống dễ chịu" },
    { id: 25, text: "7 điều tiền không mua được nhưng thiếu tiền sẽ mất", desc: "Tiền không là tất cả nhưng chạm tới tất cả" },
    { id: 26, text: "5 dấu hiệu bạn cần đổi việc vì lương không theo kịp", desc: "Khi trung thành khiến bạn tụt lại" },
    { id: 27, text: "6 sai lầm khi đàm phán lương mà người mới hay mắc", desc: "Nói về giá trị thay vì nói về nhu cầu" },
    { id: 28, text: "7 cách người trẻ mất tiền trên mạng mà không hay biết", desc: "Bảo vệ ví tiền trong môi trường số" },
    { id: 29, text: "5 lý do đừng khoe thu nhập của bạn với bất kỳ ai", desc: "Con số mở ra là rắc rối mở theo" },
    { id: 30, text: "6 việc nên làm trước khi nghỉ việc mà chưa có việc mới", desc: "Chuẩn bị đủ để không phải nhận việc vội" },
    { id: 31, text: "7 sai lầm tài chính của các cặp đôi mới cưới", desc: "Nói chuyện tiền trước khi nói chuyện cưới" },
    { id: 32, text: "5 dấu hiệu bạn đang bị xem như cây ATM của gia đình", desc: "Có hiếu vẫn cần có giới hạn" },
    { id: 33, text: "6 cách chia lương theo tỉ lệ dễ áp dụng nhất", desc: "Công thức đơn giản để duy trì được lâu" },
    { id: 34, text: "7 lý do người trẻ ngại nói về tiền và cái giá phải trả", desc: "Im lặng về tiền khiến bạn bị trả thấp" },
    { id: 35, text: "5 điều cần biết trước khi mở thẻ tín dụng đầu tiên", desc: "Dùng đúng thì lợi, dùng sai thì kẹt" },
    { id: 36, text: "6 khoản nhỏ mỗi ngày cộng lại thành cả tháng lương", desc: "Đánh giá lại các chi tiêu quen tay" },
    { id: 37, text: "7 dấu hiệu bạn đang làm việc chỉ để trả nợ", desc: "Thoát khỏi vòng xoay lương về là hết" },
    { id: 38, text: "5 sai lầm khi làm freelance mà không ai nhắc bạn", desc: "Định giá, hợp đồng và dòng tiền không đều" },
    { id: 39, text: "6 lý do lương thấp không đáng sợ bằng không có kỹ năng", desc: "Đầu tư vào năng lực trước khi đòi giá" },
    { id: 40, text: "7 điều nên chuẩn bị trước khi lên thành phố lớn làm việc", desc: "Tính đủ chi phí sống 3 tháng đầu" },
    { id: 41, text: "5 dấu hiệu bạn nên dừng mua sắm online ngay hôm nay", desc: "Nhận ra khi giỏ hàng thay thế cảm xúc" },
    { id: 42, text: "6 cách xây hồ sơ tài chính sạch từ tuổi 22", desc: "Uy tín tín dụng cần thời gian để có" },
    { id: 43, text: "7 sai lầm khi gửi tiết kiệm mà cứ tưởng là an toàn", desc: "An toàn danh nghĩa không bằng an toàn thật" },
    { id: 44, text: "5 lý do nên học nói về giá trị thay vì xin tăng lương", desc: "Chuẩn bị bằng chứng đóng góp cụ thể" },
    { id: 45, text: "6 thứ nên bán bớt để nhẹ đầu và có thêm tiền", desc: "Dọn đồ cũng là dọn tài chính" },
    { id: 46, text: "7 dấu hiệu công việc đang trả bạn quá thấp so với công sức", desc: "Định giá lại sức lao động của mình" },
    { id: 47, text: "5 điều nên làm khi mắc nợ mà chưa dám nói với gia đình", desc: "Xử lý nợ theo thứ tự thay vì trốn tránh" },
    { id: 48, text: "6 sai lầm khi mua đồ giảm giá khiến bạn tốn nhiều hơn", desc: "Giảm giá không đồng nghĩa với tiết kiệm" },
    { id: 49, text: "7 câu hỏi giúp bạn biết có nên mua món đồ đó không", desc: "Bộ lọc nhanh trước mỗi lần xuống tiền" },
    { id: 50, text: "5 việc làm hôm nay giúp bạn đỡ khổ vào năm 30 tuổi", desc: "Quyết định nhỏ hôm nay đổi cả thập kỷ sau" }
  ],
  love_boundaries: [
    { id: 1, text: "Người thương bạn thật sẽ không để bạn phải đoán", desc: "Sự rõ ràng là một hình thức của tử tế" },
    { id: 2, text: "Bạn không cần phải kiệt sức mới xứng đáng được chọn", desc: "Tình cảm không phải phần thưởng cho sự cố gắng" },
    { id: 3, text: "Có người rời đi để bạn kịp gặp lại chính mình", desc: "Mất mát đôi khi là đường về với bản thân" },
    { id: 4, text: "Yêu một người không có nghĩa là đánh mất chính mình", desc: "Giữ lại bản thể riêng trong mối quan hệ" },
    { id: 5, text: "Người ta đối xử với bạn đến đâu là do bạn cho phép đến đó", desc: "Ranh giới dạy người khác cách yêu bạn" },
    { id: 6, text: "Đừng níu một người đã quyết định rời đi", desc: "Giữ lại thân thể không giữ được tấm lòng" },
    { id: 7, text: "Im lặng cũng là một câu trả lời rất rõ ràng", desc: "Học cách đọc điều người ta không nói" },
    { id: 8, text: "Bạn xứng đáng với một tình yêu không phải cầu xin", desc: "Tình cảm phải xin là tình cảm đã hết" },
    { id: 9, text: "Có những lời xin lỗi chỉ để được tiếp tục làm bạn đau", desc: "Xin lỗi mà không đổi là chiến thuật" },
    { id: 10, text: "Người thật lòng sẽ chọn bạn cả lúc bạn không có gì", desc: "Thử thách thật nằm ở giai đoạn khó khăn" },
    { id: 11, text: "Yêu thương bản thân không phải sự ích kỷ", desc: "Không thể cho đi từ một chiếc bình rỗng" },
    { id: 12, text: "Sự bận rộn không bao giờ là lý do, đó là thứ tự ưu tiên", desc: "Người ta luôn có thời gian cho điều quan trọng" },
    { id: 13, text: "Đừng biến sự chịu đựng thành bằng chứng của tình yêu", desc: "Hy sinh một chiều không phải sâu sắc" },
    { id: 14, text: "Một mối quan hệ tốt sẽ làm bạn bình yên, không phải bất an", desc: "Cảm giác an toàn là thước đo đáng tin nhất" },
    { id: 15, text: "Nói ra điều mình cần không làm bạn trở nên khó tính", desc: "Người phù hợp sẽ lắng nghe điều đó" },
    { id: 16, text: "Có những người bước vào đời bạn chỉ để dạy một bài học", desc: "Biết ơn rồi bước tiếp nhẹ nhàng" },
    { id: 17, text: "Bạn không có trách nhiệm chữa lành cho người không muốn đổi", desc: "Yêu thương không phải công việc sửa người" },
    { id: 18, text: "Sự cô đơn trong một mối quan hệ đáng sợ hơn ở một mình", desc: "Ở cạnh nhau mà không còn kết nối" },
    { id: 19, text: "Đừng nhầm sự quen thuộc với tình yêu", desc: "Ở lâu không có nghĩa là còn phù hợp" },
    { id: 20, text: "Người biết yêu mình sẽ không sợ mất một người sai", desc: "Tự trọng là ranh giới cuối cùng" },
    { id: 21, text: "Tha thứ là để bạn nhẹ lòng, không phải để họ quay lại", desc: "Phân biệt tha thứ và cho thêm cơ hội" },
    { id: 22, text: "Đừng để nỗi sợ ở một mình đẩy bạn vào chỗ tệ hơn", desc: "Chọn vì phù hợp, không vì trống trải" },
    { id: 23, text: "Bạn không cần giải thích ranh giới của mình cho ai cả", desc: "Giới hạn không cần được ai phê duyệt" },
    { id: 24, text: "Điều bạn tha thứ lần đầu sẽ được lặp lại lần nữa", desc: "Sự dễ dãi dạy người khác cách vượt giới hạn" },
    { id: 25, text: "Tình yêu không phải cuộc thi xem ai nhịn giỏi hơn", desc: "Cùng bước thay vì cùng chịu" },
    { id: 26, text: "Đôi khi buông tay là hành động yêu thương chính mình", desc: "Kết thúc đúng lúc cũng là trưởng thành" },
    { id: 27, text: "Người trưởng thành không dùng sự im lặng để trừng phạt nhau", desc: "Giao tiếp thẳng thay vì làm nhau đoán" },
    { id: 28, text: "Bạn không phải phương án dự phòng của bất kỳ ai", desc: "Biết rời đi khi chỉ được nhớ lúc rảnh" },
    { id: 29, text: "Đừng hạ tiêu chuẩn của mình để giữ một người", desc: "Thỏa hiệp khác với tự bỏ rơi mình" },
    { id: 30, text: "Sự quan tâm thật không cần bạn phải nhắc mỗi lần", desc: "Người để tâm sẽ tự nhớ" },
    { id: 31, text: "Không phải ai cũng xứng đáng biết hết câu chuyện của bạn", desc: "Chọn người để mở lòng" },
    { id: 32, text: "Tình cảm bắt đầu bằng sự thao túng sẽ không kết thúc đẹp", desc: "Nền móng sai thì nhà không vững" },
    { id: 33, text: "Bạn có quyền thay đổi ý định về một người", desc: "Hiểu thêm rồi chọn lại là điều bình thường" },
    { id: 34, text: "Được ai đó chọn không quan trọng bằng tự chọn chính mình", desc: "Đặt bản thân vào danh sách ưu tiên" },
    { id: 35, text: "Đừng đo giá trị của mình bằng ánh mắt của một người", desc: "Giá trị bạn có trước khi họ xuất hiện" },
    { id: 36, text: "Người phù hợp sẽ làm mọi thứ trở nên dễ hơn, không khó hơn", desc: "Đúng người thì bớt phải cố" },
    { id: 37, text: "Có những cuộc chia tay đến muộn hơn cần thiết", desc: "Nhận ra dấu hiệu trước khi kiệt sức" },
    { id: 38, text: "Nói lời chia tay tử tế cũng là một loại bản lĩnh", desc: "Kết thúc rõ ràng để cả hai đi tiếp" },
    { id: 39, text: "Bạn không nợ ai một lời đồng ý", desc: "Từ chối là quyền, không phải sự bất lịch sự" },
    { id: 40, text: "Đừng để một người biến bạn thành phiên bản mình không nhận ra", desc: "Giữ lại tính cách gốc của mình" },
    { id: 41, text: "Ghen tị không phải bằng chứng của tình yêu", desc: "Kiểm soát khác với quan tâm" },
    { id: 42, text: "Tình yêu lành mạnh cho phép bạn vẫn có bạn bè riêng", desc: "Không gian riêng nuôi mối quan hệ bền" },
    { id: 43, text: "Nếu phải thay đổi bản chất để được yêu, đó không phải tình yêu", desc: "Được yêu đúng là được yêu như mình đang là" },
    { id: 44, text: "Một người thật lòng sẽ không để bạn cảm thấy khó gần họ", desc: "Sự sẵn sàng là dấu hiệu của thật lòng" },
    { id: 45, text: "Đừng lấy tuổi tác làm lý do để chọn sai người", desc: "Cưới vội trả giá bằng nhiều năm" },
    { id: 46, text: "Bạn được phép rời đi dù người ta chẳng làm gì sai", desc: "Không phù hợp đã là lý do đủ" },
    { id: 47, text: "Người ở lại lúc bạn tệ nhất mới là người nên nhớ", desc: "Nhìn vào giai đoạn khó để nhận ra ai thật" },
    { id: 48, text: "Nói chuyện được với nhau quan trọng hơn hợp nhau lúc đầu", desc: "Kỹ năng đối thoại quyết định độ bền" },
    { id: 49, text: "Đừng biến người khác thành cả thế giới của bạn", desc: "Giữ cuộc sống riêng ngoài mối quan hệ" },
    { id: 50, text: "Cuối cùng, người bạn phải sống cùng lâu nhất là chính bạn", desc: "Xây quan hệ tốt với bản thân trước tiên" }
  ],
  healing_pressure: [
    { id: 1, text: "Bạn không hề tụt lại, bạn chỉ đang đi một con đường khác", desc: "Bỏ so sánh tiến độ với người cùng tuổi" },
    { id: 2, text: "Mệt mỏi không phải vì bạn yếu, mà vì bạn gánh quá lâu", desc: "Kiệt sức là dấu hiệu cần nghỉ, không phải lỗi" },
    { id: 3, text: "Không sao cả nếu hôm nay bạn chỉ làm được một việc nhỏ", desc: "Hạ chuẩn vào ngày cạn năng lượng" },
    { id: 4, text: "Bạn được phép nghỉ mà không cần phải xứng đáng với nó", desc: "Nghỉ ngơi là nhu cầu, không phải phần thưởng" },
    { id: 5, text: "Cuộc đời không phải cuộc đua và không ai bấm giờ bạn", desc: "Tháo bỏ mốc thời gian do người khác đặt" },
    { id: 6, text: "Việc bạn chưa biết mình muốn gì ở tuổi 22 là bình thường", desc: "Chưa rõ hướng không có nghĩa là thất bại" },
    { id: 7, text: "Bạn không cần ổn mọi lúc để được yêu thương", desc: "Cho phép mình không hoàn hảo" },
    { id: 8, text: "Cảm xúc của bạn có giá trị dù không ai hiểu nó", desc: "Không cần ai xác nhận mới được buồn" },
    { id: 9, text: "Điều bạn thấy trên mạng không phải cuộc sống thật của ai cả", desc: "Nhận ra mình đang so với bản đã cắt ghép" },
    { id: 10, text: "Chậm lại không phải bỏ cuộc", desc: "Giữ nhịp bền thay vì bùng rồi tắt" },
    { id: 11, text: "Bạn không có nghĩa vụ trở thành niềm tự hào của tất cả mọi người", desc: "Sống cho kỳ vọng người khác là vô tận" },
    { id: 12, text: "Có những ngày mục tiêu duy nhất là vượt qua ngày đó", desc: "Tồn tại cũng đã là một nỗ lực" },
    { id: 13, text: "Việc bạn cần giúp đỡ không làm bạn trở nên yếu đuối", desc: "Nhờ giúp là hành động của người tỉnh táo" },
    { id: 14, text: "Bạn không thể rót từ một chiếc bình đã cạn", desc: "Sạc lại bản thân trước khi lo cho ai" },
    { id: 15, text: "Áp lực đồng trang lứa là so sánh sai đơn vị đo", desc: "Mỗi người khởi đầu ở một vạch khác" },
    { id: 16, text: "Bạn được phép thay đổi con đường mình đã chọn", desc: "Quay lại không lãng phí bằng đi tiếp sai" },
    { id: 17, text: "Không phải mọi vết thương đều cần được giải thích", desc: "Chữa lành không cần ai chứng kiến" },
    { id: 18, text: "Buông một kỳ vọng cũng nhẹ như buông một gánh nặng", desc: "Bớt kỳ vọng là bớt tự làm khổ mình" },
    { id: 19, text: "Sự bình yên đáng giá hơn việc thắng một cuộc tranh luận", desc: "Chọn giữ năng lượng thay vì giữ lý" },
    { id: 20, text: "Bạn không phải là những suy nghĩ tệ nhất về chính mình", desc: "Tách bản thân khỏi tiếng nói tự phê" },
    { id: 21, text: "Nghỉ đúng lúc là một phần của làm việc giỏi", desc: "Nghỉ có kế hoạch giúp đi được xa" },
    { id: 22, text: "Sự cô đơn ở thành phố lớn là điều rất nhiều người đang chịu", desc: "Bạn không phải người duy nhất cảm thấy vậy" },
    { id: 23, text: "Bạn không cần trả lời ngay mọi tin nhắn để là người tốt", desc: "Đặt ranh giới với sự luôn sẵn sàng" },
    { id: 24, text: "Thành công của người khác không lấy đi phần của bạn", desc: "Bớt xem cuộc sống là ván chơi thắng thua" },
    { id: 25, text: "Bạn được phép tự hào về những bước rất nhỏ", desc: "Ghi nhận tiến bộ nhỏ để đi tiếp" },
    { id: 26, text: "Cơ thể luôn báo trước, chỉ là bạn thường bỏ qua", desc: "Học đọc tín hiệu kiệt sức sớm" },
    { id: 27, text: "Không phải ai cũng cần được ở trong đời bạn mãi", desc: "Cho phép mình rời khỏi vòng cũ" },
    { id: 28, text: "Bạn có thể vừa biết ơn vừa muốn nhiều hơn", desc: "Hai điều đó không loại trừ nhau" },
    { id: 29, text: "Việc bạn chưa làm được không xóa những gì bạn đã làm", desc: "Nhìn lại quãng đường đã đi" },
    { id: 30, text: "Không cần chữa lành thật nhanh để làm hài lòng ai", desc: "Mỗi người có nhịp hồi phục riêng" },
    { id: 31, text: "Bạn được phép nói ra là mình đang không ổn", desc: "Gọi tên cảm xúc là bước đầu để nhẹ hơn" },
    { id: 32, text: "Cố gắng trong im lặng không có nghĩa là bạn phải chịu một mình", desc: "Chia sẻ đúng người làm gánh nhẹ đi" },
    { id: 33, text: "Kỳ vọng của cha mẹ không phải bản án của cuộc đời bạn", desc: "Thương yêu vẫn có thể đi kèm ranh giới" },
    { id: 34, text: "Bạn không lười, bạn đang cạn năng lượng", desc: "Phân biệt trì hoãn và kiệt sức" },
    { id: 35, text: "Điều bạn cần có thể chỉ là một giấc ngủ đủ", desc: "Nền tảng thể chất quyết định tinh thần" },
    { id: 36, text: "Không phải ngày nào cũng phải có ý nghĩa gì đó", desc: "Cho phép có những ngày bình thường" },
    { id: 37, text: "Bạn được phép ngừng cố gắng giải thích mình với người không muốn hiểu", desc: "Tiết kiệm năng lượng cho người xứng đáng" },
    { id: 38, text: "So sánh là cách nhanh nhất để mất niềm vui đang có", desc: "Quay về với những gì trong tầm tay" },
    { id: 39, text: "Việc bắt đầu muộn vẫn tốt hơn không bắt đầu", desc: "Không có mốc tuổi nào là quá muộn" },
    { id: 40, text: "Bạn xứng đáng có một cuộc sống không phải luôn cắn răng chịu", desc: "Đặt lại tiêu chuẩn cho ngày thường" },
    { id: 41, text: "Điều tổn thương bạn không nhất thiết định nghĩa bạn", desc: "Mang vết thương mà không thành vết thương" },
    { id: 42, text: "Không có ai sống đúng như thời gian biểu xã hội vẽ ra", desc: "Bỏ khuôn tuổi nào phải làm gì" },
    { id: 43, text: "Bạn có quyền giữ lại một phần cuộc sống chỉ cho riêng mình", desc: "Không phải thứ gì cũng cần chia sẻ ra" },
    { id: 44, text: "Nhìn lại một năm qua, bạn đã đi xa hơn bạn tưởng", desc: "Đo tiến bộ theo năm thay vì theo ngày" },
    { id: 45, text: "Việc bạn khóc không làm mất đi sức mạnh của bạn", desc: "Cảm xúc không đối lập với bản lĩnh" },
    { id: 46, text: "Bạn không cần phải là người mạnh nhất trong phòng", desc: "Bỏ vai diễn luôn ổn để đỡ mệt" },
    { id: 47, text: "Điều làm bạn kiệt sức có thể là thứ bạn không dám bỏ", desc: "Nhìn thẳng vào gánh nặng đang giữ" },
    { id: 48, text: "Chăm sóc bản thân là việc rất bình thường, không phải xa xỉ", desc: "Đưa nó vào lịch như mọi việc khác" },
    { id: 49, text: "Bạn được phép tự hào dù chưa tới đích", desc: "Ghi nhận mình ngay trên đường đi" },
    { id: 50, text: "Người bạn cần tử tế với nhất là chính bạn", desc: "Nói với mình như nói với một người bạn" }
  ],
  youth_regrets: [
    { id: 1, text: "7 điều bạn sẽ hối hận nếu không làm trước tuổi 25", desc: "Việc càng để lâu càng khó bắt đầu" },
    { id: 2, text: "5 thứ tuổi 20 tiêu xài mà tuổi 30 phải trả giá", desc: "Món nợ sức khỏe và tài chính đến sau" },
    { id: 3, text: "6 kỹ năng nên học xong trước khi ra trường", desc: "Thứ nhà tuyển dụng cần mà trường không dạy" },
    { id: 4, text: "7 lời xin lỗi bạn nên nói trước khi quá muộn", desc: "Có những cánh cửa chỉ mở trong một khoảng thời gian" },
    { id: 5, text: "5 điều người 30 tuổi ước mình biết ở tuổi 20", desc: "Rút ngắn đường đi bằng kinh nghiệm người trước" },
    { id: 6, text: "6 quyết định ở tuổi 20 định hình cả thập kỷ sau", desc: "Chọn nơi ở, người bên cạnh và nghề nghiệp" },
    { id: 7, text: "7 điều đừng chờ đến khi có tiền mới làm", desc: "Nhiều thứ quý không cần nhiều tiền" },
    { id: 8, text: "5 câu hỏi nên tự trả lời trước sinh nhật tuổi 25", desc: "Kiểm tra lại hướng đi của chính mình" },
    { id: 9, text: "6 thói quen nên bỏ trước khi bước sang tuổi 30", desc: "Cắt những thứ kéo bạn lại phía sau" },
    { id: 10, text: "7 điều nên nói với cha mẹ khi họ còn nghe được", desc: "Thời gian bên cha mẹ ít hơn bạn tưởng" },
    { id: 11, text: "5 cơ hội tuổi trẻ chỉ đến một lần và không quay lại", desc: "Nhận ra để không bỏ lỡ lần thứ hai" },
    { id: 12, text: "6 lý do đừng dành cả tuổi 20 để làm hài lòng người khác", desc: "Cái giá của việc sống theo kỳ vọng" },
    { id: 13, text: "7 việc nên làm một mình ít nhất một lần khi còn trẻ", desc: "Trải nghiệm dạy điều sách không dạy" },
    { id: 14, text: "5 sai lầm chọn ngành khiến bạn mất 4 năm", desc: "Cách kiểm tra trước khi cam kết" },
    { id: 15, text: "6 điều bạn sẽ tiếc nếu chỉ ở trong vùng an toàn", desc: "Rủi ro nhỏ khi trẻ, an toàn lớn về sau" },
    { id: 16, text: "7 thứ nên bắt đầu tích lũy từ tuổi 22", desc: "Thời gian là lợi thế lớn nhất bạn đang có" },
    { id: 17, text: "5 mối quan hệ nên đầu tư khi còn trẻ", desc: "Vòng người quyết định nhiều hơn bạn nghĩ" },
    { id: 18, text: "6 lý do đừng bỏ dở việc học sau khi có việc làm", desc: "Học tiếp là cách giữ giá trị lâu dài" },
    { id: 19, text: "7 điều bạn sẽ cảm ơn chính mình sau 10 năm", desc: "Những lựa chọn nhỏ mà bền" },
    { id: 20, text: "5 dấu hiệu bạn đang lãng phí tuổi trẻ mà không biết", desc: "Nhận ra sớm để đổi hướng kịp" },
    { id: 21, text: "6 việc nên làm xong trước khi kết hôn", desc: "Chuẩn bị bản thân trước khi chuẩn bị đám cưới" },
    { id: 22, text: "7 điều đừng để đến năm 30 mới bắt đầu quan tâm", desc: "Sức khỏe, tiền và kỹ năng cần thời gian" },
    { id: 23, text: "5 lời khuyên tuổi 20 nghe thấy sáo nhưng tuổi 30 mới thấm", desc: "Vì sao trải nghiệm không thể vay của ai" },
    { id: 24, text: "6 lý do nên đi làm sớm dù chỉ là việc nhỏ", desc: "Va vào thực tế càng sớm càng bớt ngợp" },
    { id: 25, text: "7 điều nên thử trước khi có quá nhiều trách nhiệm", desc: "Cửa sổ tự do của tuổi trẻ rất hẹp" },
    { id: 26, text: "5 sai lầm khiến người trẻ mất 5 năm đi lòng vòng", desc: "Nhận diện những vòng lặp vô ích" },
    { id: 27, text: "6 điều bạn sẽ tiếc nếu không giữ liên lạc với người cũ", desc: "Một số cánh cửa đóng lại rất im lặng" },
    { id: 28, text: "7 việc nên tự làm được trước khi sống một mình", desc: "Kỹ năng sống cơ bản không ai dạy lại" },
    { id: 29, text: "5 lý do đừng để nỗi sợ bị đánh giá quyết định thay bạn", desc: "Người ta quên nhanh hơn bạn tưởng" },
    { id: 30, text: "6 điều nên viết lại để 10 năm sau đọc lại", desc: "Ghi lại chính mình ở từng giai đoạn" },
    { id: 31, text: "7 thứ nên học nói khi còn trẻ: không, cảm ơn, xin lỗi", desc: "Ba câu ngắn đổi cả chất lượng quan hệ" },
    { id: 32, text: "5 sai lầm khi chọn công việc đầu tiên", desc: "Chọn nơi học được thay vì nơi trả cao" },
    { id: 33, text: "6 điều bạn sẽ hối hận nếu bỏ dở giấc mơ vì người khác", desc: "Sống hộ kỳ vọng là món nợ dài" },
    { id: 34, text: "7 dấu hiệu bạn nên đổi hướng ngay thay vì cố thêm", desc: "Bền bỉ khác với mắc kẹt" },
    { id: 35, text: "5 việc nên làm trong năm cuối đại học", desc: "Chuẩn bị đường ra trước khi ra trường" },
    { id: 36, text: "6 điều đừng chờ đủ giỏi mới bắt đầu", desc: "Bắt đầu là cách duy nhất để giỏi lên" },
    { id: 37, text: "7 thứ tuổi 20 nên đầu tư ngoài tiền bạc", desc: "Sức khỏe, kiến thức và quan hệ" },
    { id: 38, text: "5 lý do đừng so sánh tốc độ của mình với người khác", desc: "Mỗi hành trình có địa hình riêng" },
    { id: 39, text: "6 điều nên nói ra thay vì giữ trong lòng cả tuổi trẻ", desc: "Điều không nói thường ở lại rất lâu" },
    { id: 40, text: "7 việc nên làm khi bạn còn chưa ai phụ thuộc vào mình", desc: "Tận dụng khoảng thời gian nhẹ gánh nhất" },
    { id: 41, text: "5 sai lầm khiến bạn mất cơ hội chỉ vì im lặng", desc: "Chủ động lên tiếng đúng thời điểm" },
    { id: 42, text: "6 điều bạn sẽ tiếc nếu không rời khỏi nơi không phù hợp", desc: "Ở lại quá lâu cũng là một lựa chọn" },
    { id: 43, text: "7 thứ nên dọn bỏ trước khi bước sang một chặng mới", desc: "Nhẹ hành lý để đi được xa hơn" },
    { id: 44, text: "5 điều tuổi 20 nên hỏi người đi trước", desc: "Học từ vết xe đổ thay vì tự lăn" },
    { id: 45, text: "6 lý do đừng để công việc lấy hết tuổi trẻ của bạn", desc: "Cân bằng trước khi cơ thể lên tiếng" },
    { id: 46, text: "7 điều bạn sẽ tự hào khi nhìn lại tuổi 20", desc: "Chọn những việc để sau này kể lại được" },
    { id: 47, text: "5 dấu hiệu bạn đang sống theo kế hoạch của người khác", desc: "Nhận lại quyền quyết định cuộc đời mình" },
    { id: 48, text: "6 việc nên bắt đầu trong 30 ngày tới", desc: "Biến ý định thành hành động có thời hạn" },
    { id: 49, text: "7 điều đừng để tuổi tác trở thành cái cớ", desc: "Mọi mốc tuổi đều còn đường đi tiếp" },
    { id: 50, text: "5 câu bạn sẽ nói với chính mình tuổi 18 nếu gặp lại", desc: "Nhìn lại để đi tiếp tử tế hơn với mình" }
  ],
  inner_world: [
    { id: 1, text: "Người hướng nội không lạnh lùng — họ chỉ chọn ai để mở lòng", desc: "Hiểu sai về người ít nói và ranh giới thật sự của họ" },
    { id: 2, text: "Tại sao bạn cần ở một mình để hiểu mình đang cảm thấy gì", desc: "Không gian riêng là nơi cảm xúc được xử lý" },
    { id: 3, text: "Sức mạnh của người ít nói mà ít ai nhìn thấy", desc: "Im lặng không phải yếu đuối — đó là sự lựa chọn" },
    { id: 4, text: "Nội tâm phong phú không phải cô đơn — đó là thế giới bên trong bạn", desc: "Phân biệt sự cô đơn và việc sống với chính mình" },
    { id: 5, text: "Khi bạn cần thời gian một mình và không biết cách giải thích điều đó", desc: "Học cách đặt ra nhu cầu tái tạo mà không cần xin lỗi" },
    { id: 6, text: "Vì sao đám đông làm bạn kiệt sức nhưng sự tĩnh lặng lại hồi phục bạn", desc: "Cơ chế năng lượng của người hướng nội" },
    { id: 7, text: "Chiều sâu suy nghĩ là ân huệ — không phải là khiếm khuyết", desc: "Nhìn lại những điều người hướng nội mang đến cho thế giới" },
    { id: 8, text: "Bạn không cần phải ồn ào mới được ghi nhận", desc: "Giá trị thật không đến từ việc lấp đầy không gian" },
    { id: 9, text: "Người hiểu mình sâu sẽ không dễ bị người khác định nghĩa", desc: "Nền tảng bên trong vững chắc là tấm khiên chắc nhất" },
    { id: 10, text: "Khi im lặng của bạn bị hiểu lầm là kiêu ngạo", desc: "Cách sống với sự hiểu lầm mà không đánh mất bản thân" },
    { id: 11, text: "Tại sao bạn cảm thấy hụt hẫng sau mỗi buổi tụ tập — dù vui vẻ với mọi người", desc: "Trạng thái kiệt sức sau giao tiếp ở người hướng nội" },
    { id: 12, text: "Khi một mình là nhu cầu, không phải hình phạt", desc: "Thoát khỏi cảm giác tội lỗi khi cần không gian" },
    { id: 13, text: "Sự lặng lẽ không phải là khoảng trống — đó là nơi bạn nghe thấy chính mình", desc: "Tìm lại giọng nói bên trong giữa thế giới ồn ào" },
    { id: 14, text: "Người sâu sắc thường bị hiểu lầm nhiều nhất — và cách sống với điều đó", desc: "Chấp nhận việc không phải ai cũng cần hiểu bạn" },
    { id: 15, text: "Học cách nạp lại năng lượng theo cách riêng của mình mà không cảm thấy có lỗi", desc: "Xây dựng thói quen tái tạo phù hợp với bản chất" },
    { id: 16, text: "Vì sao người ít bạn bè thật sự đôi khi lại hạnh phúc hơn", desc: "Chất lượng kết nối quan trọng hơn số lượng" },
    { id: 17, text: "Không phải ai cũng cần được thấu hiểu bởi đám đông", desc: "Đủ khi có một vài người thật sự nhìn thấy bạn" },
    { id: 18, text: "Bình yên không đến từ sự ồn ào — nó đến từ bên trong", desc: "Hành trình tìm lại trung tâm yên tĩnh của chính mình" },
    { id: 19, text: "Thế giới bên trong là nơi bạn xử lý mọi thứ trước khi ra bên ngoài", desc: "Tại sao người hướng nội cần thêm thời gian để phản hồi" },
    { id: 20, text: "Khi xã hội yêu cầu bạn hướng ngoại hơn — và bạn cảm thấy mình sai", desc: "Không có cách sống nào đúng hay sai hơn" }
  ],
  self_acceptance: [
    { id: 1, text: "Tại sao bạn không cần phải trở thành ai khác để được yêu thương", desc: "Phiên bản thật của bạn đã đủ xứng đáng" },
    { id: 2, text: "Bạn không hoàn hảo — và đó chính xác là điều làm bạn thật", desc: "Vẻ đẹp của sự không hoàn chỉnh trong con người" },
    { id: 3, text: "Cái giá của việc sống theo phiên bản người khác muốn bạn là", desc: "Mất mát khi liên tục đóng vai một nhân vật không phải mình" },
    { id: 4, text: "Học cách nói 'đủ rồi' với áp lực phải tốt hơn mỗi ngày", desc: "Ranh giới giữa phát triển và tự tra tấn" },
    { id: 5, text: "Những vết nứt trong bạn không cần được che — chúng cần được chấp nhận", desc: "Vẻ đẹp của kintsugi và cách nhìn vết thương theo cách khác" },
    { id: 6, text: "Tại sao chấp nhận bản thân khó hơn thay đổi bản thân", desc: "Nghịch lý của việc yêu thương trước khi cải thiện" },
    { id: 7, text: "Bạn xứng đáng được yêu — ngay cả khi bạn chưa hoàn hảo", desc: "Tình yêu không phải phần thưởng sau khi đạt chuẩn" },
    { id: 8, text: "Bước đầu tiên của chữa lành là ngừng chống lại chính mình", desc: "Hòa bình với bản thân trước khi hòa bình với thế giới" },
    { id: 9, text: "Học cách tha thứ cho phiên bản cũ của mình", desc: "Buông bỏ ký ức về những lần bạn đã làm sai" },
    { id: 10, text: "Khi tiêu chuẩn bạn đặt ra cho bản thân đang giết chết bạn từng ngày", desc: "Chủ nghĩa hoàn hảo ẩn sau lớp áo của tham vọng" },
    { id: 11, text: "Không phải mọi thứ trong bạn đều cần phải sửa", desc: "Học cách phân biệt phát triển và tự hủy bỏ" },
    { id: 12, text: "Tại sao so sánh bản thân với người khác là hình thức tự tra tấn tinh vi nhất", desc: "Mỗi hành trình có điểm xuất phát và địa hình riêng" },
    { id: 13, text: "Bạn không cần phải chứng minh mình đủ tốt cho bất kỳ ai", desc: "Thoát khỏi vòng lặp tìm kiếm sự công nhận" },
    { id: 14, text: "Tự thương là kỹ năng — không phải sự yếu đuối", desc: "Tại sao người mạnh nhất cũng cần tử tế với chính mình" },
    { id: 15, text: "Vì sao bạn dễ tha thứ cho người khác nhưng không tha thứ được cho mình", desc: "Tiêu chuẩn kép ta áp đặt lên bản thân" },
    { id: 16, text: "Học cách nhìn bản thân bằng ánh mắt của một người thật sự yêu thương bạn", desc: "Thay đổi giọng nói bên trong từ phê phán sang thấu cảm" },
    { id: 17, text: "Chấp nhận bản thân không có nghĩa là bỏ cuộc — đó là bước đầu tiên để thay đổi thật sự", desc: "Nghịch lý: yêu bản thân mới tạo ra nền tảng để phát triển" },
    { id: 18, text: "Khi bạn ghét chính mình vì những điều bạn không thể thay đổi", desc: "Học cách buông tha những thứ nằm ngoài tầm kiểm soát" },
    { id: 19, text: "Ranh giới giữa cầu toàn lành mạnh và cầu toàn phá hủy", desc: "Dấu hiệu khi tiêu chuẩn cao đang trở thành gánh nặng" },
    { id: 20, text: "Bạn là đủ — ngay cả khi không ai nói với bạn điều đó", desc: "Xây dựng lòng tự trọng không phụ thuộc vào sự chấp thuận của người khác" }
  ],
  overthinking: [
    { id: 1, text: "Bạn đang sống trong đầu hay đang sống trong thực tế", desc: "Khoảng cách giữa suy nghĩ và hiện tại" },
    { id: 2, text: "Tại sao não bạn không chịu tắt — và cách sống chung với nó", desc: "Hiểu cơ chế của tâm trí luôn hoạt động" },
    { id: 3, text: "Suy nghĩ quá nhiều không phải thông minh — đó là lo lắng đang che giả", desc: "Nhận ra sự khác biệt giữa tư duy và lo âu" },
    { id: 4, text: "Khi bạn đã đưa ra quyết định nhưng não vẫn tiếp tục replay cảnh đó", desc: "Học cách buông bỏ sau khi đã chọn" },
    { id: 5, text: "Học cách ngồi với sự không chắc chắn mà không hoảng loạn", desc: "Chịu đựng sự mơ hồ là kỹ năng chữa lành" },
    { id: 6, text: "Vòng lặp suy nghĩ ban đêm — tại sao nó xảy ra và cách thoát ra", desc: "Khi tâm trí chọn đúng lúc bạn cần nghỉ ngơi để bật lên" },
    { id: 7, text: "Tại sao bạn lo sợ những điều chưa xảy ra nhiều hơn những điều đang xảy ra", desc: "Não bộ tạo ra mối đe dọa tương lai như thế nào" },
    { id: 8, text: "Khi sự kiểm soát trở thành nỗi ám ảnh — và lúc nào cần buông", desc: "Ranh giới giữa cẩn thận và kiểm soát quá mức" },
    { id: 9, text: "Học cách phân biệt giữa suy nghĩ và sự thật", desc: "Không phải mọi thứ trong đầu đều phản ánh thực tế" },
    { id: 10, text: "Bình yên không đến từ việc giải quyết mọi thứ — mà từ việc ngừng chiến đấu", desc: "Nghịch lý: buông bỏ là cách kiểm soát duy nhất thật sự hiệu quả" },
    { id: 11, text: "Tại sao phân tích quá kỹ đôi khi là cách trì hoãn tinh vi nhất", desc: "Paralysis by analysis và cái bẫy của sự chuẩn bị mãi mãi" },
    { id: 12, text: "Khi bạn replay một cuộc trò chuyện nhiều lần trong đầu mà không ai biết", desc: "Tâm trí xử lý xung đột xã hội như thế nào" },
    { id: 13, text: "Vì sao bạn biết đủ thông tin rồi nhưng vẫn không dám quyết định", desc: "Nỗi sợ hối hận đang làm tê liệt khả năng chọn lựa" },
    { id: 14, text: "Khi lo lắng là thói quen, không phải phản ứng", desc: "Nhận ra lo âu mãn tính khác với lo lắng bình thường" },
    { id: 15, text: "Học cách buông — không phải vì không quan trọng, mà vì bạn không thể kiểm soát tất cả", desc: "Thoát khỏi ảo tưởng kiểm soát để tìm lại bình yên" },
    { id: 16, text: "Tại sao tâm trí bạn tìm kiếm vấn đề ngay cả khi mọi thứ đang ổn", desc: "Não bộ được lập trình để tìm mối nguy — và cách reset" },
    { id: 17, text: "Sự tĩnh lặng là đích đến — không phải trạng thái không suy nghĩ", desc: "Thiền định và bình yên thật sự không có nghĩa là tắt não" },
    { id: 18, text: "Học cách quan sát suy nghĩ mà không bị chúng cuốn vào", desc: "Trở thành người xem thay vì người trong câu chuyện" },
    { id: 19, text: "Khi bạn mệt vì suy nghĩ nhiều hơn vì làm việc nhiều", desc: "Chi phí năng lượng thật sự của việc để tâm trí chạy không tải" },
    { id: 20, text: "Học cách thở và trở về hiện tại khi đầu óc đang chạy về tương lai", desc: "Kỹ thuật đơn giản để neo mình vào khoảnh khắc này" }
  ],
  // ---------------------------------------------------------------------------------------------
  // 5 nhóm dưới đây đều là văn phong 'list' (xem moralThemes.js): mỗi chủ đề phải hứa một danh sách
  // ĐẾM ĐƯỢC và nêu đúng một tình huống người xem đang sống trong đó. Tránh châm ngôn trừu tượng —
  // đó là phần việc của các nhóm reflective.
  // ---------------------------------------------------------------------------------------------
  boss_etiquette: [
    { id: 1, text: "7 cách trả lời khi sếp hỏi \"em thấy sao\" giữa cuộc họp", desc: "Có ý kiến riêng mà không giẫm chân ai" },
    { id: 2, text: "6 kiểu sếp bạn sẽ gặp và cách sống sót với từng kiểu", desc: "Nhận diện để chọn cách làm việc phù hợp" },
    { id: 3, text: "5 cách từ chối việc sếp giao khi bạn đã quá tải", desc: "Nói không mà vẫn giữ được sự tin cậy" },
    { id: 4, text: "7 câu không bao giờ nên nói với sếp dù đang ức chế", desc: "Một câu lỡ miệng xoá sạch nhiều tháng cố gắng" },
    { id: 5, text: "6 cách báo tin xấu cho sếp mà không bị quy trách nhiệm", desc: "Báo sớm kèm phương án luôn hơn giấu kỹ" },
    { id: 6, text: "5 cách mở lời xin tăng lương mà không làm sếp khó xử", desc: "Chọn đúng thời điểm và đúng dữ liệu" },
    { id: 7, text: "7 dấu hiệu sếp đang đánh giá cao bạn nhưng không nói ra", desc: "Việc được giao nói nhiều hơn lời khen" },
    { id: 8, text: "6 cách phản bác ý sếp mà vẫn giữ được thiện cảm", desc: "Chống lại ý tưởng, không chống lại con người" },
    { id: 9, text: "5 điều nên làm trong 30 ngày đầu dưới quyền sếp mới", desc: "Ấn tượng đầu định hình cả năm sau đó" },
    { id: 10, text: "7 cách khiến sếp nhớ tới bạn khi có cơ hội thăng tiến", desc: "Làm tốt thôi chưa đủ, phải được nhìn thấy" },
    { id: 11, text: "6 lỗi khiến sếp mất niềm tin chỉ sau một lần", desc: "Niềm tin mất nhanh hơn nhiều so với lúc xây" },
    { id: 12, text: "5 câu nên hỏi khi sếp giao việc mập mờ, không rõ yêu cầu", desc: "Hỏi kỹ đầu việc rẻ hơn làm lại từ đầu" },
    { id: 13, text: "7 điều nên chuẩn bị trước buổi họp riêng với sếp", desc: "Mười lăm phút đó quyết định nhiều thứ" },
    { id: 14, text: "6 cách ứng xử khi sếp phê bình bạn trước mặt cả phòng", desc: "Giữ mặt lúc đó, nói lại lúc riêng tư" },
    { id: 15, text: "5 cách nhận lỗi với sếp mà vẫn giữ được uy tín", desc: "Nhận trách nhiệm kèm cách khắc phục cụ thể" },
    { id: 16, text: "7 dấu hiệu bạn đang làm việc dưới quyền một người sếp độc hại", desc: "Phân biệt sếp khó tính và sếp có vấn đề" },
    { id: 17, text: "6 cách giữ ranh giới khi sếp nhắn việc ngoài giờ", desc: "Thiết lập kỳ vọng sớm thay vì chịu đựng dần" },
    { id: 18, text: "5 cách trả lời khi sếp hỏi bạn có định gắn bó lâu dài không", desc: "Thành thật mà không tự đóng cửa cơ hội" },
    { id: 19, text: "7 cách báo cáo công việc để sếp thấy rõ giá trị của bạn", desc: "Kể kết quả chứ đừng kể công sức" },
    { id: 20, text: "6 điều nên làm trước khi nộp đơn xin nghỉ việc", desc: "Ra đi tử tế giữ lại cả quan hệ lẫn thư giới thiệu" }
  ],
  stop_overthinking: [
    { id: 1, text: "7 cách cắt vòng lặp suy nghĩ lúc hai giờ sáng", desc: "Việc cần làm ngay khi đầu không chịu tắt" },
    { id: 2, text: "5 câu hỏi giúp bạn gỡ mớ bòng bong trong đầu", desc: "Hỏi đúng câu là nửa đường ra khỏi mê cung" },
    { id: 3, text: "6 cách chốt quyết định khi bạn cứ cân đo mãi không xong", desc: "Đặt hạn chót cho việc chọn lựa" },
    { id: 4, text: "7 mẹo dừng việc tua lại cuộc trò chuyện đã qua", desc: "Chuyện đã xong rồi, chỉ đầu bạn chưa xong" },
    { id: 5, text: "5 cách phân biệt lo lắng có ích và lo lắng vô ích", desc: "Chỉ giữ lại thứ dẫn tới hành động" },
    { id: 6, text: "6 việc nên làm khi đầu quá tải mà vẫn phải làm việc", desc: "Hạ tải tạm thời để đi tiếp trong hôm nay" },
    { id: 7, text: "7 cách làm dịu đầu óc trước khi ngủ mà không cần điện thoại", desc: "Điện thoại làm bạn tỉnh chứ không làm bạn dịu" },
    { id: 8, text: "5 quy tắc đặt hạn giờ cho suy nghĩ để khỏi nghĩ mãi", desc: "Cho phép nghĩ, nhưng có điểm dừng" },
    { id: 9, text: "6 cách xử lý khi bạn cứ đoán người khác nghĩ gì về mình", desc: "Phần lớn kịch bản đó chưa từng xảy ra" },
    { id: 10, text: "7 dấu hiệu bạn đang phân tích quá mức thay vì bắt tay làm", desc: "Chuẩn bị mãi cũng là một kiểu trì hoãn" },
    { id: 11, text: "5 cách viết ra giấy để đầu nhẹ đi trong mười phút", desc: "Chữ trên giấy chiếm ít chỗ hơn trong đầu" },
    { id: 12, text: "6 mẹo cắt bớt lựa chọn để khỏi tê liệt vì quá nhiều đường", desc: "Ít cửa hơn thì đi nhanh hơn" },
    { id: 13, text: "7 cách kéo mình về hiện tại khi tâm trí chạy tới tương lai", desc: "Neo vào thứ đang có thật trước mặt" },
    { id: 14, text: "5 câu tự nhắc khi bạn bắt đầu nghĩ tới điều tệ nhất", desc: "Chặn kịch bản xấu ngay từ câu đầu tiên" },
    { id: 15, text: "6 cách xử lý nỗi sợ sai khiến bạn đứng yên tại chỗ", desc: "Sai một bước rẻ hơn đứng yên một năm" },
    { id: 16, text: "7 thói quen nhỏ giúp đầu óc bớt ồn mỗi ngày", desc: "Giảm tiếng ồn nền thay vì chờ tĩnh lặng hoàn toàn" },
    { id: 17, text: "5 cách ngừng đòi hỏi sự chắc chắn tuyệt đối trước khi bắt đầu", desc: "Không có đủ dữ kiện nào là đủ cả" },
    { id: 18, text: "6 mẹo giữ bình tĩnh trong lúc chờ một kết quả quan trọng", desc: "Lấp khoảng chờ bằng việc trong tầm tay" },
    { id: 19, text: "7 dấu hiệu bạn đang nghĩ hộ phần việc của người khác", desc: "Trả lại lo lắng cho đúng người sở hữu nó" },
    { id: 20, text: "5 bước xử lý dứt điểm một chuyện cứ lởn vởn trong đầu", desc: "Giải quyết, lên lịch, hoặc buông hẳn" }
  ],
  discipline_habits: [
    { id: 1, text: "7 cách giữ kỷ luật khi không còn chút động lực nào", desc: "Động lực đến rồi đi, hệ thống thì ở lại" },
    { id: 2, text: "6 lý do bạn bỏ cuộc đúng tuần thứ ba và cách vượt qua", desc: "Chỗ gãy quen thuộc của mọi kế hoạch" },
    { id: 3, text: "5 cách bắt đầu lại sau khi đã đứt chuỗi nhiều ngày", desc: "Đứt một hôm không đồng nghĩa hỏng cả tháng" },
    { id: 4, text: "7 thói quen nhỏ đến mức không thể viện cớ bỏ qua", desc: "Nhỏ tới mức làm còn nhanh hơn nghĩ cớ" },
    { id: 5, text: "6 cách sắp xếp môi trường để khỏi phải dùng tới ý chí", desc: "Dọn đường dễ hơn gồng mình mỗi ngày" },
    { id: 6, text: "5 khung giờ nên dành cho việc khó nhất trong ngày", desc: "Làm việc nặng lúc đầu còn tỉnh táo" },
    { id: 7, text: "7 cách dậy sớm mà không phải báo thức tới lần thứ năm", desc: "Việc quyết định buổi sáng nằm ở tối hôm trước" },
    { id: 8, text: "6 mẹo giữ đều đặn khi lịch sinh hoạt thay đổi liên tục", desc: "Bản rút gọn cho những ngày bận nhất" },
    { id: 9, text: "5 cách đo tiến bộ để bạn thấy mình đang đi tới", desc: "Thấy được tiến độ mới có sức đi tiếp" },
    { id: 10, text: "7 cái bẫy của việc đặt mục tiêu quá lớn ngay từ đầu", desc: "Tham quá thì gãy ngay tuần đầu" },
    { id: 11, text: "6 cách cắt cơn lướt điện thoại trước giờ làm việc", desc: "Mười phút lướt đủ phá hỏng cả buổi tập trung" },
    { id: 12, text: "5 cách vận dụng quy tắc hai phút để bắt đầu ngay lập tức", desc: "Khởi động nhỏ phá được sức ì lớn" },
    { id: 13, text: "7 cách giữ kỷ luật khi không có ai giám sát bạn", desc: "Tự chịu trách nhiệm khi làm việc một mình" },
    { id: 14, text: "6 dấu hiệu bạn đang bận rộn giả tạo chứ không hề kỷ luật", desc: "Bận không đồng nghĩa với hiệu quả" },
    { id: 15, text: "5 cách nghỉ ngơi đúng để không kiệt sức giữa chừng", desc: "Nghỉ có kế hoạch là một phần của kỷ luật" },
    { id: 16, text: "7 câu tự nhủ khiến bạn phá vỡ kỷ luật mà không nhận ra", desc: "Những lời bào chữa nghe rất hợp lý" },
    { id: 17, text: "6 cách biến việc khó thành thói quen sau ba mươi ngày", desc: "Lộ trình tăng dần thay vì nhảy cóc" },
    { id: 18, text: "5 cách chọn đúng một việc để tập trung thay vì ôm hết", desc: "Làm xong một thứ hơn dở dang năm thứ" },
    { id: 19, text: "7 thói quen buổi tối quyết định chất lượng ngày hôm sau", desc: "Ngày mai bắt đầu từ đêm nay" },
    { id: 20, text: "6 cách giữ kỷ luật khi người xung quanh bạn thì không", desc: "Đi ngược đám đông mà không thấy lạc lõng" }
  ],
  university_life: [
    { id: 1, text: "7 điều sinh viên năm nhất nên biết trước khi quá muộn", desc: "Biết sớm một năm hơn hối tiếc bốn năm" },
    { id: 2, text: "6 sai lầm khiến bốn năm đại học trôi qua vô nghĩa", desc: "Ra trường tay trắng dù chưa từng trốn học" },
    { id: 3, text: "5 cách xoay xở khi bạn nhận ra mình học nhầm ngành", desc: "Đổi hướng sớm rẻ hơn cố cho xong" },
    { id: 4, text: "7 kỹ năng nên có trước khi ra trường, quan trọng hơn điểm số", desc: "Thứ nhà tuyển dụng hỏi mà bảng điểm không trả lời" },
    { id: 5, text: "6 cách kiếm tiền khi đi học mà không hỏng việc học", desc: "Chọn việc có tích luỹ cho hồ sơ sau này" },
    { id: 6, text: "5 lý do đi làm thêm sớm giúp bạn hơn hẳn bạn cùng lớp", desc: "Va chạm thật dạy nhanh hơn giáo trình" },
    { id: 7, text: "7 cách chọn câu lạc bộ để không phí mất một năm", desc: "Vào để học được gì, không phải cho vui" },
    { id: 8, text: "6 điều nên làm trong kỳ thực tập để được giữ lại", desc: "Thực tập là buổi phỏng vấn kéo dài ba tháng" },
    { id: 9, text: "5 cách sống chung với bạn cùng phòng mà không xích mích", desc: "Thoả thuận trước tránh cãi nhau sau" },
    { id: 10, text: "7 sai lầm tiêu tiền điển hình của sinh viên năm nhất", desc: "Tự do tài chính đầu đời rất dễ trượt" },
    { id: 11, text: "6 cách nhờ thầy cô viết thư giới thiệu đúng cách", desc: "Hỏi sớm, hỏi đúng người, kèm đủ thông tin" },
    { id: 12, text: "5 thứ nên chuẩn bị từ năm hai cho hồ sơ xin việc", desc: "Hồ sơ đẹp được xây dần chứ không làm gấp" },
    { id: 13, text: "7 cách học hiệu quả hơn mà không cần thức khuya", desc: "Học đúng cách tiết kiệm cả sức lẫn giờ" },
    { id: 14, text: "6 dấu hiệu bạn đang học chỉ để qua môn", desc: "Qua môn nhưng không đọng lại gì" },
    { id: 15, text: "5 cách xây quan hệ ở đại học có ích cho sau này", desc: "Bạn cùng lớp hôm nay là đồng nghiệp mai sau" },
    { id: 16, text: "7 điều nên trải nghiệm trước khi tốt nghiệp", desc: "Có những việc chỉ làm được lúc còn là sinh viên" },
    { id: 17, text: "6 cách vượt qua cảm giác lạc lõng khi lên thành phố học", desc: "Năm đầu xa nhà khó hơn mọi người tưởng" },
    { id: 18, text: "5 lý do điểm cao vẫn không xin được việc", desc: "Bảng điểm chỉ mở cửa, không giữ chỗ" },
    { id: 19, text: "7 tài nguyên miễn phí của trường mà bạn đang bỏ phí", desc: "Đã đóng học phí rồi thì dùng cho hết" },
    { id: 20, text: "6 cách nói chuyện với bố mẹ khi bạn muốn đổi hướng", desc: "Thuyết phục bằng kế hoạch, không bằng cảm xúc" }
  ],
  after_graduation: [
    { id: 1, text: "7 điều không ai nói trước về sáu tháng đầu sau tốt nghiệp", desc: "Khoảng trống giữa lễ ra trường và ngày đi làm" },
    { id: 2, text: "6 cách viết hồ sơ xin việc khi bạn chưa có kinh nghiệm", desc: "Chưa đi làm không có nghĩa là không có gì để kể" },
    { id: 3, text: "5 câu phỏng vấn ai cũng gặp và cách trả lời cho thật", desc: "Trả lời thẳng hơn hẳn học thuộc văn mẫu" },
    { id: 4, text: "7 lỗi khiến hồ sơ của bạn bị loại trong mười giây", desc: "Người sàng lọc không đọc kỹ như bạn nghĩ" },
    { id: 5, text: "6 cách trả lời khi được hỏi mức lương mong muốn", desc: "Nói số sớm quá hay muộn quá đều thiệt" },
    { id: 6, text: "5 dấu hiệu nên tránh một công ty ngay từ vòng phỏng vấn", desc: "Buổi phỏng vấn là lúc bạn cũng đang chấm họ" },
    { id: 7, text: "7 cách tìm việc khi bạn không quen ai trong ngành", desc: "Bắt đầu từ con số không về quan hệ" },
    { id: 8, text: "6 điều nên làm trong tháng đầu tiên đi làm", desc: "Ba mươi ngày đầu định hình cách người ta nhìn bạn" },
    { id: 9, text: "5 cách vượt qua cảm giác vô dụng khi rải hồ sơ mãi không ai gọi", desc: "Im lặng của nhà tuyển dụng không phải phán quyết về bạn" },
    { id: 10, text: "7 câu nên hỏi ngược nhà tuyển dụng ở cuối buổi phỏng vấn", desc: "Câu hỏi của bạn cũng đang được chấm điểm" },
    { id: 11, text: "6 lý do nên nhận công việc đầu tiên dù chưa thật ưng ý", desc: "Bước đầu tiên tạo ra những bước sau" },
    { id: 12, text: "5 cách thương lượng lương lần đầu mà không mất cơ hội", desc: "Hỏi thêm đúng cách hiếm khi bị rút lời mời" },
    { id: 13, text: "7 điều nên chuẩn bị trước buổi phỏng vấn trực tuyến", desc: "Mạng, ánh sáng và tiếng động quyết định ấn tượng" },
    { id: 14, text: "6 dấu hiệu cho thấy đã đến lúc rời công việc đầu tiên", desc: "Ở lại quá lâu cũng tốn kém như nhảy quá sớm" },
    { id: 15, text: "5 cách giải thích khoảng trống trong hồ sơ xin việc", desc: "Thành thật kèm những gì bạn đã làm trong thời gian đó" },
    { id: 16, text: "7 kỹ năng nhà tuyển dụng cần mà nhà trường không dạy", desc: "Phần chênh giữa giảng đường và công sở" },
    { id: 17, text: "6 cách xây hồ sơ năng lực khi chưa đi làm ngày nào", desc: "Tự tạo sản phẩm để có thứ đưa người ta xem" },
    { id: 18, text: "5 cái giá phải trả khi nhảy việc quá sớm", desc: "Hồ sơ nhảy liên tục kể một câu chuyện không hay" },
    { id: 19, text: "7 cách vượt qua áp lực khi bạn bè có việc trước bạn", desc: "Mỗi người một tốc độ, kể cả khi mạng xã hội nói khác" },
    { id: 20, text: "6 điều nên làm sau khi bị từ chối ở vòng cuối", desc: "Đến vòng cuối nghĩa là bạn đã rất gần" }
  ],
  // ---------------------------------------------------------------------------------------------
  // Từ lóng trending. Khác mọi nhóm trên ở một điểm: TỪ LÓNG chính là chủ thể của video, phải giữ
  // NGUYÊN VĂN xuyên suốt kịch bản (xem TERM LOCK trong moralTalkVoiceStyle.js) — nên mỗi chủ đề ở
  // đây xoay quanh đúng MỘT từ, viết thẳng từ đó vào tiêu đề.
  //
  // Đây là nhóm CÓ HẠN SỬ DỤNG: từ lóng hết trend rất nhanh. Cứ thêm/bớt thoải mái, chỉ cần giữ
  // đúng khuôn "từ lóng nằm trong text" là prompt hoạt động đúng.
  // ---------------------------------------------------------------------------------------------
  trending_slang: [
    { id: 1, text: "Sĩ Vương là ai mà nhóm bạn nào cũng có một người", desc: "Chân dung châm biếm kiểu người sống vì cái sĩ" },
    { id: 2, text: "5 dấu hiệu bạn đang ngồi cạnh một Sĩ Vương chính hiệu", desc: "Nhận diện qua những tình huống ai cũng từng gặp" },
    { id: 3, text: "Lốp Trưởng — kiểu người khiến cả nhóm im lặng vài giây", desc: "Chân dung châm biếm, đầy tình huống quen thuộc" },
    { id: 4, text: "6 khoảnh khắc lộ nguyên hình một Lốp Trưởng", desc: "Đi ăn, group chat, chia tiền, đi làm" },
    { id: 5, text: "Lọ Vương và những pha xử lý khiến ai cũng đứng hình", desc: "Chân dung châm biếm nhẹ nhàng, không cay nghiệt" },
    { id: 6, text: "7 câu nói kinh điển của một Lọ Vương", desc: "Nghe xong là nghĩ ngay ra một đứa" },
    { id: 7, text: "Khi trong một nhóm có cả Sĩ Vương lẫn Lốp Trưởng", desc: "Hai kiểu người gặp nhau thì chuyện gì xảy ra" },
    { id: 8, text: "5 dấu hiệu chính bạn mới là Sĩ Vương mà không hay", desc: "Cú quay xe: soi lại chính mình" }
  ]
};

/**
 * Danh sách chủ đề của một nhóm. Rơi về self_help nếu nhóm chưa có lộ trình riêng — khớp đúng
 * cách MoralSyllabusModal vẫn làm, để không nơi nào phải tự xử lý trường hợp thiếu key.
 */
export function getMoralSyllabus(themeKey) {
  return MORAL_SYLLABUS[themeKey] || MORAL_SYLLABUS.self_help;
}

/**
 * Số chủ đề THẬT của một nhóm.
 *
 * Con số 50 từng được viết cứng ở nhãn nút và trong modal, từ thời mọi nhóm đều đủ 50 chủ đề. Các
 * nhóm thêm về sau chỉ có 20, nên màn hình hiện ra những dòng tự mâu thuẫn kiểu "Đã làm 20/50 bài
 * (100%)" — phần trăm tính theo số thật, còn mẫu số thì vẫn là 50 cứng.
 */
export function getMoralSyllabusCount(themeKey) {
  return getMoralSyllabus(themeKey).length;
}
