/**
 * Danh mục các chủ đề phong cách tạo Prompt Ảnh AI (Midjourney, Flux, Stable Diffusion, DALL-E 3)
 * Tương ứng với màn hình Category Grid của tab 'Prompt Ảnh'.
 */

export const IMAGE_PROMPT_CATEGORIES = [
  {
    id: 'portrait_cinematic',
    icon: '📸',
    label: 'Nhiếp Ảnh Chân Dung Điện Ảnh',
    badge: 'PORTRAIT 85MM',
    badgeBg: 'linear-gradient(135deg, #ec4899, #8b5cf6)',
    shortDescription: 'Bắt trọn nếp tóc, ánh mắt có hồn, chi tiết da siêu thực với ống kính chân dung 85mm f/1.4, bokeh mịn màng và ánh sáng rim light.',
    tags: ['Chân Dung 85mm', 'Studio Softbox', 'Cinematic Bokeh', 'Da Siêu Thực'],
    defaultIdea: 'Chân dung cận cảnh cụ già người Nhật Bản với ánh mắt hiền từ và nếp nhăn thời gian',
    defaultStyle: 'Cinematic 8K Photography',
    defaultCamera: 'Eye-level shot, 85mm portrait lens, f/1.4 shallow depth of field',
    defaultLighting: 'Cinematic Dramatic Lighting with deep shadows and rim light',
    accentColor: '#ec4899',
  },
  {
    id: 'sumie_ukiyoe',
    icon: '🖌️',
    label: 'Thủy Mặc Cổ Phong & Ukiyo-e',
    badge: 'THỦY MẶC & ZEN',
    badgeBg: 'linear-gradient(135deg, #f59e0b, #b45309)',
    shortDescription: 'Nghệ thuật tranh thủy mặc Sumi-e mực tàu cổ điển, tranh khắc gỗ thời Edo, vết loang nước mộc mạc và phong vị thiền định phương Đông.',
    tags: ['Thủy Mặc Sumi-e', 'Ukiyo-e Edo', 'Giấy Xuyến Chi', 'Màu Nước Cổ Điển'],
    defaultIdea: 'Chiến binh Samurai mặc giáp đỏ đứng giữa cơn bão tuyết bên cạnh cành tùng cổ thụ',
    defaultStyle: 'Traditional Japanese Ink & Watercolor (Ukiyo-e)',
    defaultCamera: 'Wide-angle 24mm landscape perspective, immense depth',
    defaultLighting: 'Soft diffused studio lighting, gentle fill light',
    accentColor: '#f59e0b',
  },
  {
    id: 'anime_shinkai',
    icon: '🌸',
    label: 'Anime Nhật Bản & Makoto Shinkai',
    badge: 'MAKOTO SHINKAI',
    badgeBg: 'linear-gradient(135deg, #38bdf8, #0ea5e9)',
    shortDescription: 'Phong cách hoạt hình Nhật Bản đỉnh cao với bầu trời mây hoàng hôn bồng bềnh, ánh sáng lung linh rực rỡ và cảm xúc sâu lắng như Your Name.',
    tags: ['Anime Makoto Shinkai', 'Bầu Trời Hoàng Hôn', 'Ánh Sáng Thần Tiên', 'Ghibli Vibes'],
    defaultIdea: 'Hai bạn trẻ đứng ở ngã tư đường tàu dưới tán hoa anh đào bay trong gió hoàng hôn',
    defaultStyle: 'Anime Style by Makoto Shinkai',
    defaultCamera: 'Eye-level shot, 85mm portrait lens, f/1.4 shallow depth of field',
    defaultLighting: 'Golden hour warm sunlight with soft lens flare',
    accentColor: '#38bdf8',
  },
  {
    id: 'epic_fantasy',
    icon: '🐉',
    label: 'Kỳ Ảo Huyền Huyễn & Thần Thoại',
    badge: 'EPIC FANTASY',
    badgeBg: 'linear-gradient(135deg, #a855f7, #6366f1)',
    shortDescription: 'Thế giới thần thoại phương Đông & phương Tây: rồng thần uy phong vần vũ, lâu đài bay giữa các tầng mây, tiên hiệp và phù thủy huyền bí.',
    tags: ['Thần Thoại Rồng', 'Lâu Đài Bay', 'Phép Thuật Huyền Bí', 'Unreal Engine 5'],
    defaultIdea: 'Rồng phương Đông uy nghi uốn lượn quanh đỉnh núi tuyết phủ giữa mây cuồn cuộn',
    defaultStyle: '3D Render Unreal Engine 5 / Octane',
    defaultCamera: 'Low-angle heroic shot, dramatic upward view',
    defaultLighting: 'Mystical moonlight, volumetric fog and god rays',
    accentColor: '#a855f7',
  },
  {
    id: 'cyberpunk_neon',
    icon: '🏙️',
    label: 'Cyberpunk & Tương Lai Neon Noir',
    badge: 'CYBERPUNK NEON',
    badgeBg: 'linear-gradient(135deg, #06b6d4, #d946ef)',
    shortDescription: 'Thành phố tương lai rực rỡ bảng hiệu neon phản chiếu mặt đường mưa đêm, xe bay tấp nập, công nghệ cao và phong cách bí ẩn.',
    tags: ['Neon Noir', 'Mưa Đêm Tokyo', 'Xe Bay Tương Lai', 'Hologram'],
    defaultIdea: 'Cô gái hacker cyberpunk đeo tai nghe phát sáng đứng dưới mưa đêm phố Neo-Tokyo',
    defaultStyle: 'Cyberpunk Neon Noir Art',
    defaultCamera: 'Eye-level shot, 85mm portrait lens, f/1.4 shallow depth of field',
    defaultLighting: 'Neon glow with colorful reflections on wet surfaces',
    accentColor: '#06b6d4',
  },
  {
    id: 'landscape_nature',
    icon: '🏔️',
    label: 'Phong Cảnh Flycam & Kỳ Quan Hùng Vĩ',
    badge: 'NATURAL 8K',
    badgeBg: 'linear-gradient(135deg, #10b981, #059669)',
    shortDescription: 'Những góc máy flycam rộng lớn bao quát núi tuyết hùng vĩ, hẻm núi kỳ quan, hoàng hôn trên biển và các công trình thiên nhiên ngoạn mục.',
    tags: ['Flycam Drone', 'Golden Hour', 'Thiên Nhiên Hùng Vĩ', 'National Geographic'],
    defaultIdea: 'Hồ nước ngọc bích nằm lọt thỏm giữa dãy núi băng đá hùng vĩ lúc bình minh',
    defaultStyle: 'National Geographic Wildlife Photography',
    defaultCamera: 'Top-down aerial drone view, symmetrical composition',
    defaultLighting: 'Golden hour warm sunlight with soft lens flare',
    accentColor: '#10b981',
  },
];

export function getImagePromptCategoryById(id) {
  return IMAGE_PROMPT_CATEGORIES.find((c) => c.id === id) || IMAGE_PROMPT_CATEGORIES[0];
}
