/**
 * Kho chủ đề dành riêng cho VIDEO DÀI (4-10 phút) của skill "Kịch Bản & Slide Ảnh Người Que".
 *
 * Tổng hợp các chủ đề viral, thịnh hành nhất hiện nay (AI, Brain Rot, thuật toán mạng xã hội,
 * bí ẩn vũ trụ, tiến hóa sinh tồn, tâm lý học và tự do tài chính) theo phong cách Mack, Kurzgesagt, Aperture.
 */
export const STICK_FIGURE_LONGFORM_GROUPS = [
  {
    key: 'trending_ai',
    label: '🔥 Xu Hướng Hot & Công Nghệ AI',
    icon: '🔥',
    sublabel: 'Trí tuệ nhân tạo, Brain Rot, thuật toán, tương lai',
    topics: [
      { id: 1, text: 'Will Artificial Intelligence Actually Take Your Job?', desc: 'Liệu Trí tuệ nhân tạo (AI) có thực sự cướp mất công việc của bạn?' },
      { id: 2, text: 'The Science of "Brain Rot": How Short Videos Are Destroying Focus', desc: 'Hội chứng "Brain Rot": Video ngắn đang tàn phá khả năng tập trung ra sao?' },
      { id: 3, text: 'How the TikTok Algorithm Secretly Reads Your Mind', desc: 'Bí ẩn thuật toán TikTok: Cơ chế đọc suy nghĩ và giữ chân người xem' },
      { id: 4, text: 'What If the Global Internet Completely Crashed for 24 Hours?', desc: 'Chuyện gì sẽ xảy ra nếu toàn bộ Internet thế giới sập trong 24 giờ?' },
      { id: 5, text: 'Deepfakes and the Terrifying End of Truth on the Internet', desc: 'Hiểm họa Deepfake và sự biến mất của sự thật trên không gian mạng' },
      { id: 6, text: 'Why Gen Z Is Quietly Abandoning Traditional 9-to-5 Office Jobs', desc: 'Vì sao Gen Z ngày càng chán nản và rời bỏ văn phòng 8 tiếng mỗi ngày?' },
      { id: 7, text: 'The Psychological Trap Behind "Buy Now, Pay Later" Services', desc: 'Cạm bẫy tâm lý "Mua trước trả sau" đang đẩy người trẻ vào nợ nần' },
      { id: 8, text: 'Why Everyone Feels Constantly Burned Out and Chronically Tired', desc: 'Nghịch lý kiệt sức mãn tính: Vì sao nghỉ ngơi mãi vẫn thấy mệt mỏi?' },
    ],
  },
  {
    key: 'earth_science',
    label: '🌍 Bí Ẩn & Khoa Học Trái Đất',
    icon: '🌍',
    sublabel: 'Lõi Trái Đất, từ trường, siêu lục địa, đại dương ngầm',
    topics: [
      { id: 1, text: "Earth's Inner Core Has Slowed Down: Is It Reversing Direction?", desc: 'Lõi trong Trái Đất quay chậm lại: Liệu nó có đang bắt đầu đổi hướng?' },
      { id: 2, text: "The Massive Hidden Ocean Trapped 600km Beneath Earth's Crust", desc: 'Bí ẩn đại dương ngầm khổng lồ bị giam giữ 600km dưới lòng đất' },
      { id: 3, text: "Geomagnetic Reversal: What Happens When Earth's Magnetic Poles Flip?", desc: 'Hiện tượng đảo cực địa từ: Chuyện gì xảy ra khi từ trường Trái Đất lật ngược?' },
      { id: 4, text: 'Snowball Earth: When Our Entire Planet Froze Into a Giant Ice Ball', desc: 'Giả thuyết Tuyết cầu Trái Đất: Thời kỳ cả hành tinh đóng băng trắng xóa' },
      { id: 5, text: 'The Mystery of the Massive "Gravity Hole" in the Indian Ocean', desc: 'Bí ẩn "Lỗ hổng trọng lực" khổng lồ đáy biển Ấn Độ Dương' },
      { id: 6, text: 'What Did Scientists Really Find at the Bottom of the Kola Superdeep Borehole?', desc: 'Các nhà khoa học thực sự tìm thấy gì dưới đáy hố khoan sâu nhất Trái Đất Kola?' },
      { id: 7, text: 'The Giant Impact Hypothesis: How the Ancient Planet Theia Created the Moon', desc: 'Giả thuyết Theia va chạm: Vụ nổ hành tinh khai sinh ra Mặt Trăng' },
      { id: 8, text: 'The Great Oxidation Event: How Oxygen Nearly Wiped Out All Life on Earth', desc: 'Thảm họa Oxy hóa Lớn: Khi khí oxy suýt hủy diệt toàn bộ sinh quyển Trái Đất' },
      { id: 9, text: "The Giant Mysterious Blobs Sitting on Top of Earth's Core (LLSVPs)", desc: 'Hai cấu trúc bí ẩn cỡ lục địa nằm đè lên lõi ngoài Trái Đất (LLSVPs)' },
      { id: 10, text: 'Pangea Ultima: What Will Happen When Continents Collide Again in 250M Years?', desc: 'Siêu lục địa Pangea Ultima: Viễn cảnh Trái Đất nóng rực sau 250 triệu năm' },
      { id: 11, text: 'The Purple Earth Hypothesis: Why Our Ancient Planet Was Once Completely Purple', desc: 'Giả thuyết Trái Đất màu Tím: Vì sao hành tinh cổ xưa từng mang sắc tím rực rỡ?' },
      { id: 12, text: 'The Terrifying Physics of the Deepest Mariana Trench and How Life Survives It', desc: 'Vật lý nghiền nát đáy Rãnh Mariana và cách sinh vật kỳ dị sinh tồn' },
      { id: 13, text: "Milankovitch Cycles: How Slight Shifts in Earth's Orbit Cause Ice Ages", desc: 'Chu kỳ Milankovitch: Dao động quỹ đạo kích hoạt các kỷ băng hà thế nào?' },
      { id: 14, text: 'The First 24 Hours After the Chicxulub Asteroid Impact Struck Earth', desc: '24 giờ kinh hoàng đầu tiên sau khi tiểu hành tinh Chicxulub đâm vào Trái Đất' },
      { id: 15, text: 'The Looming Collapse of the Atlantic Ocean Current (AMOC): Is Europe Freezing?', desc: 'Nguy cơ sụp đổ dòng hải lưu AMOC: Châu Âu đối mặt mùa đông băng giá?' },
      { id: 16, text: "The South Atlantic Anomaly: Earth's Magnetic Dent That Fries Spacecraft", desc: 'Vùng dị thường Nam Đại Tây Dương: Vết lõm từ trường làm tê liệt vệ tinh' },
      { id: 17, text: 'The Toba Supervolcano Eruption: When Humanity Nearly Went Extinct', desc: 'Siêu núi lửa Toba phun trào: Khi loài người suýt bị xóa sổ khỏi Trái Đất' },
      { id: 18, text: "Zealandia: The Geological Discovery of Earth's Hidden Eighth Continent", desc: 'Zealandia: Bí mật lục địa thứ 8 của Trái Đất bị chìm sâu dưới đáy biển' },
      { id: 19, text: 'The "Flying Rivers": How the Amazon Rainforest Creates Giant Rivers in the Sky', desc: 'Những "Dòng sông bay": Rừng Amazon tạo ra dòng sông khổng lồ trên bầu trời thế nào?' },
      { id: 20, text: "The Eternal Lightning of Catatumbo: Earth's Most Electric Place on the Planet", desc: 'Hiện tượng Sét vĩnh cửu Catatumbo: Nơi sét đánh liên tục 160 đêm mỗi năm' },
    ],
  },
  {
    key: 'cosmic_mysteries',
    label: '🌌 Bí Ẩn Vũ Trụ & Thiên Văn',
    icon: '🌌',
    sublabel: 'Hố đen, ngoài hành tinh, Big Bang, bão Mặt Trời',
    topics: [
      { id: 1, text: 'What If Earth Suddenly Stopped Spinning for Just 5 Seconds?', desc: 'Điều gì xảy ra nếu Trái Đất đột ngột ngừng quay chỉ trong 5 giây?' },
      { id: 2, text: 'The Fermi Paradox: If Aliens Exist, Where Is Everybody?', desc: 'Nghịch lý Fermi: Nếu vũ trụ bao la, tại sao ta chưa gặp người ngoài hành tinh?' },
      { id: 3, text: 'What Actually Happens If a Human Falls Straight Into a Black Hole?', desc: 'Điều kỳ dị gì xảy ra nếu bạn không may rơi vào một hố đen vũ trụ?' },
      { id: 4, text: 'The Brutal Reality of What Living on Mars Would Actually Feel Like', desc: 'Hiện thực khốc liệt về việc con người định cư trên Sao Hỏa' },
      { id: 5, text: 'What Was There Before the Big Bang Created Time and Space?', desc: 'Có gì tồn tại trước khi Vụ Nổ Lớn (Big Bang) tạo ra vũ trụ?' },
      { id: 6, text: 'How Will the Universe Eventually End in the Trillion-Year Future?', desc: 'Kịch bản tận cùng của vũ trụ sau hàng nghìn tỷ năm nữa' },
      { id: 7, text: 'What If the Sun Completely Disappeared from the Solar System?', desc: 'Chuyện gì xảy ra với Trái Đất nếu Mặt Trời đột ngột biến mất?' },
      { id: 8, text: 'The Carrington Event of 1859: What If a Super Solar Storm Hits Modern Earth Today?', desc: 'Siêu bão Mặt Trời Carrington: Chuyện gì xảy ra nếu quét qua Trái Đất hôm nay?' },
      { id: 9, text: 'What Would Happen If the Moon Drifted Away from Earth Forever?', desc: 'Điều gì xảy ra nếu Mặt Trăng trôi dạt vĩnh viễn khỏi Trái Đất?' },
      { id: 10, text: 'The James Webb Space Telescope: Discoveries That Broke Existing Cosmology Models', desc: 'Kính viễn vọng James Webb: Những khám phá làm lung lay mô hình vũ trụ học' },
    ],
  },
  {
    key: 'ancient_survival',
    label: '❄️ Bí Ẩn Sinh Tồn & Tiến Hóa',
    icon: '❄️',
    sublabel: 'Băng hà, săn bắt, lửa, tiến hóa',
    topics: [
      { id: 1, text: 'How Did Ancient Humans Survive Freezing Winters?', desc: 'Làm sao người cổ đại sống sót qua mùa đông kỷ băng hà?' },
      { id: 2, text: 'Why Humans Lost Their Body Hair (And Kept Head Hair)', desc: 'Vì sao con người rụng hết lông nhưng lại giữ tóc?' },
      { id: 3, text: 'How Prehistoric Humans Hunted Mammoths 10x Their Size', desc: 'Cách người tiền sử săn những con voi ma mút khổng lồ' },
      { id: 4, text: 'How Fire Transformed the Human Body and Brain Forever', desc: 'Ngọn lửa đã thay đổi cơ thể và bộ não con người ra sao?' },
      { id: 5, text: 'What Happened When Neanderthals Met Homo Sapiens?', desc: 'Chuyện gì xảy ra khi Neanderthal chạm trán Homo Sapiens?' },
      { id: 6, text: 'How Ancient Humans Cleaned Their Teeth Without Toothbrushes', desc: 'Người xưa chăm sóc răng miệng thế nào trước khi có bàn chải?' },
      { id: 7, text: 'The Surprising Truth About the First Shoes in Human History', desc: 'Sự thật bất ngờ về đôi giày đầu tiên trong lịch sử loài người' },
      { id: 8, text: 'What Would Happen If a Modern Human Was Dropped in the Ice Age?', desc: 'Nếu bị ném về Kỷ Băng hà, người hiện đại sống được bao lâu?' },
    ],
  },
  {
    key: 'human_science',
    label: '🧬 Khoa Học & Bí Ẩn Cơ Thể',
    icon: '🧬',
    sublabel: 'Giấc ngủ, ký ức, sốc nhiệt, mồ hôi',
    topics: [
      { id: 1, text: 'Why Humans Need 8 Hours of Sleep (And How Ancestors Really Slept)', desc: 'Bí ẩn giấc ngủ 8 tiếng và tổ tiên chúng ta từng ngủ thế nào' },
      { id: 2, text: 'Why Your Brain Erases Your Early Childhood Memories', desc: 'Vì sao não bộ xóa sạch toàn bộ ký ức thời thơ ấu?' },
      { id: 3, text: 'How Sweating Became the Deadliest Human Superpower', desc: 'Đổ mồ hôi: Siêu năng lực săn mồi bền bỉ nhất của loài người' },
      { id: 4, text: 'Why Do We Get Goosebumps When Cold or Scared?', desc: 'Tại sao con người lại nổi da gà khi lạnh hoặc sợ hãi?' },
      { id: 5, text: 'What Happens to Your Body If You Stop Eating Sugar for 30 Days?', desc: 'Điều gì xảy ra với cơ thể khi cắt hoàn toàn đường trong 30 ngày?' },
      { id: 6, text: 'Why the Human Body Can Survive Weeks Without Food But Days Without Water', desc: 'Vì sao nhịn ăn được cả tháng nhưng nhịn nước chỉ vài ngày?' },
      { id: 7, text: 'The Dark Science of Why Cold Water Shock Kills So Fast', desc: 'Khoa học đáng sợ về hiện tượng sốc nhiệt nước lạnh' },
      { id: 8, text: 'How Walking Upright Changed the Entire Human Skeleton', desc: 'Đi bằng hai chân đã thay đổi toàn bộ khung xương con người ra sao?' },
    ],
  },
  {
    key: 'habits',
    label: '⏰ Thói Quen & Kỷ Luật Thép',
    icon: '⏰',
    sublabel: 'Trì hoãn, dopamine, dậy sớm, tập trung',
    topics: [
      { id: 1, text: 'Why we procrastinate, and how to actually stop', desc: 'Gốc rễ tâm lý của trì hoãn và cách thoát ra' },
      { id: 2, text: 'How Dopamine Detox Can Reset Your Overstimulated Brain', desc: 'Detox Dopamine: Cách thiết lập lại bộ não quá tải vì mạng xã hội' },
      { id: 3, text: 'The real reason you cannot wake up early, and how to fix it', desc: 'Nhịp sinh học và cách xây thói quen dậy sớm' },
      { id: 4, text: 'How small daily habits decide who you become in five years', desc: 'Sức mạnh cộng dồn của thói quen nhỏ mỗi ngày' },
      { id: 5, text: 'Why motivation always fails you, and what works instead', desc: 'Vì sao động lực không đáng tin, kỷ luật mới bền vững' },
      { id: 6, text: 'How to build a habit that finally sticks', desc: 'Quy trình xây dựng thói quen bền vững từng bước' },
      { id: 7, text: 'The hidden cost of staying up late every night', desc: 'Thiếu ngủ tàn phá trí nhớ, cảm xúc và sức khỏe ra sao?' },
      { id: 8, text: 'Why doing less can help you achieve much more', desc: 'Tập trung vào ít việc thay vì ôm đồm để đạt hiệu quả cao' },
    ],
  },
  {
    key: 'money',
    label: '💸 Tài Chính & Tâm Lý Tiền Bạc',
    icon: '💸',
    sublabel: 'Lạm phát, tự do tài chính, chi tiêu thông minh',
    topics: [
      { id: 1, text: 'How Inflation Secretly Steals Your Savings Every Day', desc: 'Lạm phát âm thầm bốc hơi tiền tiết kiệm của bạn mỗi ngày thế nào?' },
      { id: 2, text: 'The FIRE Movement: How to Retire Financially Free by Age 35', desc: 'Phong trào FIRE: Làm sao để tự do tài chính và nghỉ hưu ở tuổi 35?' },
      { id: 3, text: 'Why Working Harder Will Never Make You Truly Rich', desc: 'Vì sao cày cuốc chăm chỉ không bao giờ giúp bạn thực sự giàu có?' },
      { id: 4, text: 'How Advertising Subtly Forces You to Buy Things You Do Not Need', desc: 'Tâm lý học đằng sau quảng cáo khiến bạn chi tiền không kiểm soát' },
      { id: 5, text: 'Why Saving a Little Early Beats Earning a Lot Later', desc: 'Sức mạnh lãi kép: Tiết kiệm sớm đánh bại kiếm nhiều tiền muộn' },
      { id: 6, text: 'The Hidden Debt Traps That Keep Middle Class Families Struggling', desc: 'Cơ chế nợ tiêu dùng và trả góp khiến nhiều người mãi chật vật' },
      { id: 7, text: 'Why Your First Job Matters Much Less Than the Skills You Build', desc: 'Kỹ năng tích lũy quan trọng hơn chức danh công việc đầu tiên' },
      { id: 8, text: 'The Danger of Lifestyle Inflation: Why More Income Rarely Means More Wealth', desc: 'Cạm bẫy lạm phát lối sống: Càng kiếm nhiều càng tiêu nhiều' },
    ],
  },
  {
    key: 'mindset',
    label: '🧠 Tư Duy & Tâm Lý Học Hiện Đại',
    icon: '🧠',
    sublabel: 'Overthinking, tự ti, so sánh, áp lực',
    topics: [
      { id: 1, text: 'Why comparing yourself to others online makes you miserable', desc: 'So sánh trên mạng xã hội và cái bẫy tự ti đánh mất chính mình' },
      { id: 2, text: 'How fear of failure keeps you stuck where you are', desc: 'Nỗi sợ thất bại đang kìm hãm cuộc đời bạn như thế nào?' },
      { id: 3, text: 'Why you feel tired even when you did nothing all day', desc: 'Mệt mỏi tinh thần khác gì mệt mỏi thể chất và cách hồi phục?' },
      { id: 4, text: 'How overthinking destroys your decisions and your sleep', desc: 'Vòng lặp suy nghĩ quá mức (Overthinking) và cách dập tắt' },
      { id: 5, text: 'Why you feel like a fraud even when you succeed', desc: 'Hội chứng kẻ mạo danh (Imposter Syndrome) ở người thành công' },
      { id: 6, text: 'How to stop caring so much about what people think', desc: 'Nghệ thuật không bận tâm đến ánh nhìn và phán xét của người khác' },
      { id: 7, text: 'Why being too hard on yourself slows you down', desc: 'Tự trách bản thân và học cách trắc ẩn với chính mình' },
      { id: 8, text: 'How to deal with pressure when everyone seems ahead of you', desc: 'Áp lực đồng trang lứa và cách đi theo nhịp độ riêng của bạn' },
    ],
  },
  {
    key: 'study',
    label: '📚 Học Tập & Trí Nhớ Siêu Phàm',
    icon: '📚',
    sublabel: 'Phương pháp học, ôn thi, tập trung cao độ',
    topics: [
      { id: 1, text: 'Why you forget almost everything you study, and how to fix it', desc: 'Đường cong quên lãng và kỹ thuật ôn tập ngắt quãng (Spaced Repetition)' },
      { id: 2, text: 'How to actually achieve deep focus in a world full of notifications', desc: 'Rèn khả năng tập trung sâu (Deep Work) giữa thế giới xao nhãng' },
      { id: 3, text: 'The wrong way most students study, and what to do instead', desc: 'Sai lầm đọc lại thụ động và phương pháp chủ động gợi nhớ (Active Recall)' },
      { id: 4, text: 'Why cramming the night before an exam always backfires', desc: 'Học dồn trước đêm thi và giới hạn của trí nhớ ngắn hạn' },
      { id: 5, text: 'The Feynman Technique: How to Master Any Difficult Subject Fast', desc: 'Kỹ thuật Feynman: Cách làm chủ mọi kiến thức khó cực nhanh' },
      { id: 6, text: 'Why smart people still freeze and fail important exams', desc: 'Tâm lý phòng thi và kỹ năng quản lý áp lực giờ chót' },
      { id: 7, text: 'How to remember names, facts, and numbers effortlessly', desc: 'Kỹ thuật ghi nhớ thông tin và sự kiện áp dụng được ngay' },
      { id: 8, text: 'Why taking notes word-for-word is a total waste of study time', desc: 'Ghi chép thông minh thay vì chép lại nguyên văn bài giảng' },
    ],
  },
  {
    key: 'social',
    label: '🤝 Giao Tiếp & Nghệ Thuật Ứng Xử',
    icon: '🤝',
    sublabel: 'Nói trước đám đông, kết bạn, thiết lập ranh giới',
    topics: [
      { id: 1, text: 'Why you freeze when you have to speak in front of people', desc: 'Cơ chế sợ nói trước đám đông và phương pháp làm chủ sân khấu' },
      { id: 2, text: 'How to make genuine friends as a busy adult', desc: 'Xây dựng tình bạn chất lượng khi đã trưởng thành' },
      { id: 3, text: 'Why saying no is harder than it should be, and how to set boundaries', desc: 'Nghệ thuật từ chối và thiết lập ranh giới không cảm thấy áy náy' },
      { id: 4, text: 'How to have conversations that people truly remember and enjoy', desc: 'Kỹ năng lắng nghe chân thành và dẫn dắt câu chuyện cuốn hút' },
      { id: 5, text: 'Why first impressions matter so much and how to nail them', desc: 'Tâm lý học về ấn tượng đầu tiên và cách tạo thiện cảm tức thì' },
      { id: 6, text: 'How being a people-pleaser quietly damages your self-worth', desc: 'Hội chứng cả nể: Vì sao làm hài lòng tất cả mọi người sẽ tự hại mình?' },
      { id: 7, text: 'Why misunderstandings happen even between people who love each other', desc: 'Rào cản giao tiếp và nguyên nhân gây hiểu lầm trong gia đình, người yêu' },
      { id: 8, text: 'How to apologize properly in a way that heals broken trust', desc: 'Cách xin lỗi chân thành để hàn gắn niềm tin và mối quan hệ' },
    ],
  },
  {
    key: 'health',
    label: '🌿 Sức Khỏe & Thần Kinh Học',
    icon: '🌿',
    sublabel: 'Ngồi nhiều, ánh sáng xanh, stress, nhịp sinh học',
    topics: [
      { id: 1, text: 'What sitting all day in an office chair is doing to your spine and organs', desc: 'Tác hại kinh hoàng của việc ngồi một chỗ cả ngày đến cột sống và nội tạng' },
      { id: 2, text: 'Why skipping breakfast messes with your blood sugar and focus all day', desc: 'Bỏ bữa sáng làm đảo lộn đường huyết và khả năng tập trung ra sao?' },
      { id: 3, text: 'How chronic invisible stress quietly degrades your immune system', desc: 'Căng thẳng mạn tính âm thầm tàn phá hệ miễn dịch như thế nào?' },
      { id: 4, text: 'Why drinking enough water changes your brain energy more than coffee', desc: 'Vì sao uống đủ nước giúp tăng năng lượng não bộ hơn cả cà phê?' },
      { id: 5, text: 'How a simple 20-minute daily walk can physically reshape your brain', desc: 'Đi bộ 20 phút mỗi ngày giúp tái tạo tế bào thần kinh thế nào?' },
      { id: 6, text: 'Why ultra-processed foods trick your brain into constant hunger', desc: 'Thực phẩm siêu chế biến đánh lừa não bộ khiến bạn luôn thèm ăn' },
      { id: 7, text: 'How blue light from phones before sleep destroys deep restorative sleep', desc: 'Ánh sáng xanh trước giờ ngủ phá hủy giai đoạn ngủ sâu ra sao?' },
      { id: 8, text: 'Why true rest is essential for peak cognitive performance', desc: 'Nghỉ ngơi đúng cách là điều kiện bắt buộc để đạt hiệu suất cao' },
    ],
  },
];

/** Tổng số chủ đề — dùng cho nhãn nút, khỏi phải đếm tay rồi lệch mỗi lần thêm bớt. */
export const STICK_FIGURE_LONGFORM_TOPIC_COUNT = STICK_FIGURE_LONGFORM_GROUPS
  .reduce((sum, g) => sum + g.topics.length, 0);
