export const READING_SYLLABUS = {
  a1: [
    { id: 1, text: "My Happy Family", desc: "Giới thiệu các thành viên trong gia đình nhỏ" },
    { id: 2, text: "The Little Golden Dog", desc: "Chú chó nhỏ thân thiện trong xóm" },
    { id: 3, text: "My Daily Morning Routine", desc: "Thói quen thức dậy và chuẩn bị buổi sáng" },
    { id: 4, text: "A Rainy Day at Home", desc: "Một ngày mưa ấm áp ở trong nhà" },
    { id: 5, text: "The Red Apple Tree", desc: "Cây táo đỏ ngọt ngào trong vườn" },
    { id: 6, text: "Breakfast with Grandma", desc: "Bữa sáng ấm áp cùng bà ngoại" },
    { id: 7, text: "My Cute Cat Whiskers", desc: "Chú mèo nhỏ đáng yêu với đôi râu dài" },
    { id: 8, text: "Walking in the Green Park", desc: "Đi dạo công viên rợp bóng cây xanh" },
    { id: 9, text: "Learning to Ride a Bicycle", desc: "Tập đi xe đạp lần đầu tiên" },
    { id: 10, text: "The Sun Comes Up", desc: "Bình minh rạng rỡ bắt đầu ngày mới" },
    { id: 11, text: "My Colorful Backpack", desc: "Chiếc cặp sách nhiều màu đi học" },
    { id: 12, text: "A Visit to the Zoo", desc: "Chuyến tham quan vườn thú vui vẻ" },
    { id: 13, text: "Making Hot Chocolate", desc: "Tự tay pha ly ca cao nóng thơm ngon" },
    { id: 14, text: "My Best School Friend", desc: "Người bạn thân thiết nhất ở trường" },
    { id: 15, text: "Playing Soccer in the Garden", desc: "Đá bóng cùng bạn bè ngoài sân" },
    { id: 16, text: "The Singing Birds", desc: "Những chú chim hót líu lo trên cành" },
    { id: 17, text: "Going to the Supermarket", desc: "Cùng mẹ đi siêu thị mua sắm đồ" },
    { id: 18, text: "My Cozy Bedroom", desc: "Căn phòng ngủ nhỏ nhắn ấm cúng" },
    { id: 19, text: "A Day at the Beach", desc: "Tắm biển và xây lâu đài cát" },
    { id: 20, text: "Cleaning My Room", desc: "Dọn dẹp phòng ngăn nắp đón người thân" },
    { id: 21, text: "The Magic Crayons", desc: "Hộp màu vẽ kỳ diệu sáng tạo" },
    { id: 22, text: "Eating Fresh Watermelon", desc: "Thưởng thức dưa hấu mát lạnh mùa hè" },
    { id: 23, text: "Helping Mom in the Kitchen", desc: "Phụ mẹ chuẩn bị cơm tối" },
    { id: 24, text: "The Little Blue Bird", desc: "Chú chim xanh nhỏ đậu ngoài cửa sổ" },
    { id: 25, text: "My New Shoes", desc: "Đôi giày mới tinh đi học" },
    { id: 26, text: "Feeding the Ducks", desc: "Cho bầy vịt ăn bên bờ hồ" },
    { id: 27, text: "The Little Seed in the Garden", desc: "Hạt giống nhỏ đơm mầm trong đất" },
    { id: 28, text: "My Toy Robot", desc: "Chú robot đồ chơi biết nhảy múa" },
    { id: 29, text: "A Starry Night Sky", desc: "Bầu trời đêm lấp lánh muôn ngàn sao" },
    { id: 30, text: "Planting a Flower", desc: "Trồng một chậu hoa xinh xắn" },
    { id: 31, text: "The Friendly Milkman", desc: "Chú giao sữa thân thiện mỗi sáng" },
    { id: 32, text: "Drinking Warm Milk", desc: "Uống ly sữa ấm trước khi ngủ" },
    { id: 33, text: "My Red Bicycle", desc: "Chiếc xe đạp màu đỏ yêu thích" },
    { id: 34, text: "The Loud Alarm Clock", desc: "Chiếc đồng hồ báo thức reo vang" },
    { id: 35, text: "Playing Hide and Seek", desc: "Trò chơi trốn tìm vui nhộn" },
    { id: 36, text: "Buying Fresh Bread", desc: "Đi mua bánh mì nóng hổi" },
    { id: 37, text: "A Cold Winter Day", desc: "Ngày mùa đông lành lạnh khoác áo ấm" },
    { id: 38, text: "My Yellow Umbrella", desc: "Chiếc ô màu vàng xinh xắn che mưa" },
    { id: 39, text: "The Little Fish in the Bowl", desc: "Chú cá vàng bơi tung tăng trong bể" },
    { id: 40, text: "Drawing a Rainbow", desc: "Vẽ cầu vồng 7 màu sau cơn mưa" },
    { id: 41, text: "Washing My Hands", desc: "Rửa tay sạch sẽ trước khi ăn" },
    { id: 42, text: "My Birthday Cake", desc: "Chiếc bánh sinh nhật thắp nến lung linh" },
    { id: 43, text: "The Fluffy White Rabbit", desc: "Chú thỏ trắng lông xù thích ăn cà rốt" },
    { id: 44, text: "Flying a Paper Airplane", desc: "Gấp máy bay giấy phóng lên bầu trời" },
    { id: 45, text: "The Old Wooden Chair", desc: "Chiếc ghế gỗ êm ái của ông" },
    { id: 46, text: "Watching Raindrops on the Window", desc: "Ngắm giọt mưa rơi ngoài ô cửa" },
    { id: 47, text: "Picking Strawberries", desc: "Hái dâu tây chín đỏ trong vườn" },
    { id: 48, text: "The Sweet Ice Cream Shop", desc: "Tiệm kem ngọt ngào nhiều hương vị" },
    { id: 49, text: "Saying Goodnight to the Moon", desc: "Chúc chị Hằng ngủ ngon mỗi đêm" },
    { id: 50, text: "Ready for Bed", desc: "Đã sẵn sàng vào giấc ngủ chìm trong giấc mơ" }
  ],

  a2: [
    { id: 1, text: "The Seed's Big Journey", desc: "Hành trình nảy mầm vươn lên thành cây lớn" },
    { id: 2, text: "A Boy Who Lost His Keys", desc: "Cậu bé đánh rơi chìa khóa và bài học cẩn thận" },
    { id: 3, text: "The Kind Neighbor Next Door", desc: "Bác hàng xóm tốt bụng luôn giúp đỡ mọi người" },
    { id: 4, text: "A Surprise Birthday Party", desc: "Bữa tiệc sinh nhật bất ngờ cho người bạn thân" },
    { id: 5, text: "My First Camping Trip", desc: "Chuyến cắm trại đêm đầu tiên trong rừng" },
    { id: 6, text: "The Lost Kitten in the Rain", desc: "Giải cứu chú mèo con đi lạc dưới mưa" },
    { id: 7, text: "Buying Fresh Vegetables at Market", desc: "Đi chợ rau củ truyền thống cùng mẹ" },
    { id: 8, text: "Learning How to Swim", desc: "Vượt qua nỗi sợ nước và học bơi thành thạo" },
    { id: 9, text: "An Unforgettable Picnic", desc: "Buổi dã ngoại rộn rã tiếng cười cuối tuần" },
    { id: 10, text: "The Mystery of the Missing Book", desc: "Cuốn sách thư viện đi đâu mất tệp?" },
    { id: 11, text: "A Letter to My Future Self", desc: "Viết thư gửi chính mình trong 5 năm nữa" },
    { id: 12, text: "The Brave Little Squirrel", desc: "Chú sóc nhỏ dũng cảm tích trữ hạt qua mùa đông" },
    { id: 13, text: "Visiting a Farm on the Weekend", desc: "Trải nghiệm làm nông dân một ngày ở trang trại" },
    { id: 14, text: "How to Make a Delicious Sandwich", desc: "Hướng dẫn làm kẹp bánh mì dinh dưỡng" },
    { id: 15, text: "The Old Clock Tower in Town", desc: "Tháp đồng hồ cổ kính chứng kiến bao thế hệ" },
    { id: 16, text: "A Ride on the Fast Train", desc: "Chuyến tàu hỏa tốc hành ngắm cảnh núi sông" },
    { id: 17, text: "Fixing an Old Toy Car", desc: "Cùng bố sửa lại chiếc xe đồ chơi kỷ niệm" },
    { id: 18, text: "A Day in the Life of a Baker", desc: "Một ngày bận rộn nhưng thơm phức của thợ bánh" },
    { id: 19, text: "The Secret Garden Behind House", desc: "Khu vườn bí mật đầy hoa dại sau nhà" },
    { id: 20, text: "Overcoming the Fear of Dark", desc: "Chiến thắng nỗi sợ bóng tối đêm khuya" },
    { id: 21, text: "Helping an Elderly Stranger", desc: "Giúp cụ già qua đường an toàn" },
    { id: 22, text: "The Little Library on Corner", desc: "Thư viện cộng đồng miễn phí ở góc phố" },
    { id: 23, text: "Taking Care of a Stray Puppy", desc: "Chăm sóc chú cún đi lang thang phục hồi" },
    { id: 24, text: "A Rainy Afternoon Tea", desc: "Thưởng thức tách trà chiều ấm nóng ngày mưa" },
    { id: 25, text: "Preparing for New School Day", desc: "Chuẩn bị tâm lý cho ngày đầu chuyển trường" },
    { id: 26, text: "The Magic of Reading Books", desc: "Sức mạnh kỳ diệu đưa ta đến những vùng đất mới" },
    { id: 27, text: "A Fun Day at Amusement Park", desc: "Thỏa sức chơi công viên giải trí rực rỡ" },
    { id: 28, text: "Learning to Cook Dinner Alone", desc: "Tự tay nấu bữa tối đầu tiên tặng gia đình" },
    { id: 29, text: "The Tale of Two Best Friends", desc: "Tình bạn diệu kỳ qua nhiều năm tháng" },
    { id: 30, text: "Saving Pocket Money for a Dream", desc: "Tiết kiệm tiền heo đất mua món đồ mơ ước" },
    { id: 31, text: "A Trip to the Science Museum", desc: "Khám phá thế giới khoa học đầy kinh ngạc" },
    { id: 32, text: "The Tree House We Built", desc: "Căn nhà trên cây độc đáo tự tay dựng nên" },
    { id: 33, text: "Finding a Forgotten Treasure", desc: "Tìm thấy chiếc hộp gác xép phủ bụi thời gian" },
    { id: 34, text: "The Street Musician's Song", desc: "Tiếng đàn violon lắng đọng trên con phố nhỏ" },
    { id: 35, text: "How Grandfather Made Wooden Toys", desc: "Ông ngoại đẽo gọt những món đồ chơi gỗ" },
    { id: 36, text: "A Snowy Day Adventure", desc: "Nặn người tuyết và ném tuyết cùng bạn bè" },
    { id: 37, text: "Cleaning Up the Beach", desc: "Nhặt rác làm sạch bãi biển quê hương" },
    { id: 38, text: "First Time I Saw the Sea", desc: "Cảm xúc ngỡ ngàng khi nhìn thấy biển rộng lớn" },
    { id: 39, text: "A Mischievous Monkey in Park", desc: "Chú khỉ tinh nghịch lém lỉnh xin ăn" },
    { id: 40, text: "Learning to Play the Guitar", desc: "Bắt đầu tập những nốt nhạc guitar đầu tiên" },
    { id: 41, text: "The Helpful Bus Driver", desc: "Bác tài xế buýt vui tính và cẩn thận" },
    { id: 42, text: "A Midnight Snack Story", desc: "Bữa ăn đêm giấu giếm cực kỳ thú vị" },
    { id: 43, text: "Why Exercise Makes Us Happy", desc: "Tập thể dục giúp cơ thể tràn đầy năng lượng" },
    { id: 44, text: "The Old Lighthouse on Cliff", desc: "Ngọn hải đăng bền bỉ soi đường cho tàu cá" },
    { id: 45, text: "A Funny Mix-up at Restaurant", desc: "Tình huống nhầm lẫn món ăn dở khóc dở cười" },
    { id: 46, text: "The Butterfly That Changed Colors", desc: "Chú bướm rực rỡ mang điềm lành kỳ diệu" },
    { id: 47, text: "Making Handmade Birthday Cards", desc: "Tự tay làm thiệp mừng ý nghĩa gửi bạn" },
    { id: 48, text: "The Story of a Little Sailor", desc: "Ước mơ ra khơi đánh bắt cá của cậu bé bờ biển" },
    { id: 49, text: "A Peaceful Evening by Lake", desc: "Mặt hồ phẳng lặng phản chiếu ánh hoàng hôn" },
    { id: 50, text: "Looking at Old Family Photos", desc: "Lật mở cuốn album ảnh ghi dấu kỷ niệm" }
  ],

  b1: [
    { id: 1, text: "The Power of Small Habits", desc: "Sức mạnh tích lũy của những thói quen nhỏ mỗi ngày" },
    { id: 2, text: "Why Making Mistakes Helps Us Learn", desc: "Sai lầm là người thầy tốt nhất trên con đường trưởng thành" },
    { id: 3, text: "The Value of True Friendship", desc: "Tình bạn chân thành thử thách qua gian khó" },
    { id: 4, text: "Overcoming Stage Fright", desc: "Vượt qua nỗi sợ phát biểu trước đám đông" },
    { id: 5, text: "The Importance of Active Listening", desc: "Lắng nghe chân thành để thấu hiểu người đối diện" },
    { id: 6, text: "Finding Balance Between Work and Rest", desc: "Cân bằng cuộc sống giữa công việc và thư giãn" },
    { id: 7, text: "Story of a Renewable Energy Inventor", desc: "Nhà sáng chế năng lượng sạch bảo vệ trái đất" },
    { id: 8, text: "Dealing with Disappointment Gracefully", desc: "Đón nhận sự thất vọng một cách bình thản và đi tiếp" },
    { id: 9, text: "How Technology Changed Communication", desc: "Công nghệ số đã làm thay đổi cách con người kết nối" },
    { id: 10, text: "The Art of Asking Good Questions", desc: "Đặt câu hỏi thông minh giúp mở ra tri thức mới" },
    { id: 11, text: "Learning to Manage Time Effectively", desc: "Quản lý thời gian cá nhân để sống trọn vẹn" },
    { id: 12, text: "Why Traveling Opens Your Mind", desc: "Đi một ngày đàng học một nia khôn" },
    { id: 13, text: "Journey of a Self-Taught Artist", desc: "Hành trình tự học vẽ và chạm tới ước mơ" },
    { id: 14, text: "How Kindness Spreads Like Waves", desc: "Một hành động tử tế lan tỏa năng lượng tích cực" },
    { id: 15, text: "Staying Focused in a Distracted World", desc: "Giữ vững sự tập trung giữa vô vàn xao nhãng" },
    { id: 16, text: "Understanding Cultures Through Food", desc: "Khám phá bản sắc văn hóa qua ẩm thực vùng miền" },
    { id: 17, text: "Failure is a Stepping Stone to Success", desc: "Thất bại chỉ là bước đệm để vươn tới thành công" },
    { id: 18, text: "Power of Teamwork in Problem Solving", desc: "Sức mạnh đồng đội giải quyết bài toán khó" },
    { id: 19, text: "Embracing Minimalist Living", desc: "Lối sống tối giản giúp tâm trí thảnh thơi" },
    { id: 20, text: "The Story of a Forest Ranger", desc: "Người kiểm lâm tận tụy giữ gìn mảng xanh" },
    { id: 21, text: "How Gratitude Changes Your Outlook", desc: "Lòng biết ơn giúp thay đổi góc nhìn cuộc sống" },
    { id: 22, text: "History Behind Everyday Inventions", desc: "Nguồn gốc bất ngờ của những vật dụng quen thuộc" },
    { id: 23, text: "Overcoming Procrastination Habits", desc: "Đẩy lùi thói quen trì hoãn công việc" },
    { id: 24, text: "Magic of Storytelling Across Generations", desc: "Nghệ thuật truyền lửa qua những câu chuyện kể" },
    { id: 25, text: "Protecting Local Wildlife in Cities", desc: "Bảo vệ động vật hoang dã nơi đô thị" },
    { id: 26, text: "Courage to Stand Up for Justice", desc: "Lòng dũng cảm bảo vệ lẽ phải" },
    { id: 27, text: "How Music Heals the Human Soul", desc: "Âm nhạc là liều thuốc chữa lành tâm hồn" },
    { id: 28, text: "Finding Happiness in Simple Things", desc: "Hạnh phúc đích thực đến từ những điều bình dị" },
    { id: 29, text: "Challenges of Moving to a New City", desc: "Thử thách và cơ hội khi bắt đầu ở thành phố mới" },
    { id: 30, text: "Role of Mentors in Personal Growth", desc: "Vai trò người dẫn đường trong phát triển bản thân" },
    { id: 31, text: "Why Reading Classic Literature Matters", desc: "Tại sao nên đọc văn học kinh điển?" },
    { id: 32, text: "Importance of Sleep for Mental Clarity", desc: "Giấc ngủ chất lượng nâng cao trí tuệ" },
    { id: 33, text: "Building Resilience in Hard Times", desc: "Tôi luyện bản lĩnh kiên cường trước nghịch cảnh" },
    { id: 34, text: "Story of an Urban Community Garden", desc: "Khu vườn cộng đồng kết nối tình nghĩa xóm giềng" },
    { id: 35, text: "How Curiosity Drives Scientific Discovery", desc: "Tò mò là động cơ cho mọi phát minh khoa học" },
    { id: 36, text: "Learning a Foreign Language as Adult", desc: "Học ngoại ngữ khi đã trưởng thành: Gian nan và trái ngọt" },
    { id: 37, text: "The Healing Power of Forgiveness", desc: "Bao dung và tha thứ để tâm tha tự do" },
    { id: 38, text: "Micro-loans Changing Small Villages", desc: "Tín dụng nhỏ làm đổi thay những làng quê nghèo" },
    { id: 39, text: "Impact of Plastic Waste on Oceans", desc: "Tác hại của rác thải nhựa đại dương" },
    { id: 40, text: "The Art of Peaceful Negotiation", desc: "Nghệ thuật đàm phán ôn hòa trong xung đột" },
    { id: 41, text: "Why Honesty is the Best Policy", desc: "Sự thành thật là kim chỉ nam dài lâu" },
    { id: 42, text: "Life Lessons Learned from Sports", desc: "Những bài học đời người đúc kết từ thể thao" },
    { id: 43, text: "How Architecture Influences Our Mood", desc: "Kiến trúc không gian tác động tới cảm xúc" },
    { id: 44, text: "Benefits of Alone Time in Nature", desc: "Thời gian tĩnh lặng một mình giữa thiên nhiên" },
    { id: 45, text: "Second-Chance Animal Shelter", desc: "Mái ấm trao cơ hội sống mới cho thú cưng" },
    { id: 46, text: "How Mindfulness Reduces Stress", desc: "Chánh niệm giải tỏa áp lực cuộc sống hiện đại" },
    { id: 47, text: "Value of Keeping a Personal Journal", desc: "Lợi ích của việc viết nhật ký mỗi ngày" },
    { id: 48, text: "Navigating Peer Pressure Positively", desc: "Ứng xử thông minh trước áp lực đồng lứa" },
    { id: 49, text: "Evolution of Traditional Craftsmanship", desc: "Gìn giữ và phát triển làng nghề truyền thống" },
    { id: 50, text: "Leaving a Positive Footprint on Earth", desc: "Sống có trách nhiệm vì một hành tinh xanh" }
  ],

  b2: [
    { id: 1, text: "The Psychology of Decision Making", desc: "Tâm lý học đằng sau cách con người đưa ra quyết định" },
    { id: 2, text: "Critical Thinking in Social Media Era", desc: "Tư duy phản biện trước bão thông tin mạng xã hội" },
    { id: 3, text: "Security vs Personal Freedom Balance", desc: "Cân bằng giữa an ninh quốc gia và tự do cá nhân" },
    { id: 4, text: "How AI Shapes Modern Careers", desc: "Trí tuệ nhân tạo đang định hình lại thị trường lao động" },
    { id: 5, text: "The Ethics of Genetic Engineering", desc: "Đạo đức sinh học trong chỉnh sửa gen con người" },
    { id: 6, text: "Navigating Ambiguity in Leadership", desc: "Bản lĩnh lãnh đạo khi đối mặt với sự mơ hồ" },
    { id: 7, text: "The Paradox of Choice in Society", desc: "Nghịch lý của quá nhiều sự lựa chọn trong tiêu dùng" },
    { id: 8, text: "Role of Empathy in Modern Diplomacy", desc: "Thấu cảm trong ngoại giao và hòa giải quốc tế" },
    { id: 9, text: "Evolution of Human Language Expression", desc: "Sự biến đổi của ngôn ngữ và biểu đạt qua thời gian" },
    { id: 10, text: "Remote Work Impact on Cities", desc: "Làm việc từ xa tái cấu trúc không gian đô thị" },
    { id: 11, text: "Emotional vs Intellectual Intelligence", desc: "Trí tuệ cảm xúc (EQ) và Trí thông minh (IQ)" },
    { id: 12, text: "Economics of Sustainable Business", desc: "Mô hình kinh doanh tuần hoàn và phát triển bền vững" },
    { id: 13, text: "Understanding Bias in News Coverage", desc: "Nhận diện định kiến trong truyền thông đại chúng" },
    { id: 14, text: "Stoicism Philosophy for Anxiety", desc: "Triết học Chủ nghĩa Khắc kỷ cho áp lực thời nay" },
    { id: 15, text: "Architecture of High-Performing Teams", desc: "Bí quyết xây dựng đội ngũ hiệu suất vượt trội" },
    { id: 16, text: "Urban Planning Affecting Mental Health", desc: "Quy hoạch đô thị tác động đến sức khỏe tâm thần" },
    { id: 17, text: "Future of Higher Education & Upskilling", desc: "Tương lai của giáo dục đại học và học tập suốt đời" },
    { id: 18, text: "Influence of Advertising on Desires", desc: "Quảng cáo định hình khao khát tiêu dùng ra sao?" },
    { id: 19, text: "Cognitive Dissonance in Human Beliefs", desc: "Bất hòa nhận thức và cách con người tự bào chữa" },
    { id: 20, text: "Neuroscience of Creativity & Flow State", desc: "Khoa học thần kinh về sáng tạo và trạng thái Dòng chảy" },
    { id: 21, text: "Environmental Stewardship in Industry", desc: "Trách nhiệm môi trường trong sản xuất công nghiệp" },
    { id: 22, text: "Power of Rhetoric in Public Discourse", desc: "Nghệ thuật hùng biện trong diễn ngôn công cộng" },
    { id: 23, text: "Cultural Relativity and Global Ethics", desc: "Tương đối luận văn hóa và chuẩn mực đạo đức toàn cầu" },
    { id: 24, text: "Psychology of Habits: Cue & Reward", desc: "Vòng lặp thói quen: Gợi ý, Hành động và Phần thưởng" },
    { id: 25, text: "Resilience of Indigenous Knowledge", desc: "Tri thức bản địa bền vững ứng phó biến đổi khí hậu" },
    { id: 26, text: "Intersection of Art and Science", desc: "Điểm giao thoa giữa nghệ thuật thị giác và khoa học" },
    { id: 27, text: "Privacy in the Age of Big Data", desc: "Quyền riêng tư trong kỷ nguyên phân tích dữ liệu lớn" },
    { id: 28, text: "Sociology of Online Digital Communities", desc: "Xã hội học về các cộng đồng ảo trên Internet" },
    { id: 29, text: "Historical Narrative Shaping Identity", desc: "Kể chuyện lịch sử kiến tạo bản sắc dân tộc" },
    { id: 30, text: "Economics of Circular Waste Management", desc: "Kinh tế học quản lý rác thải theo chu trình đóng" },
    { id: 31, text: "Overcoming Imposter Syndrome at Work", desc: "Chiến thắng hội chứng Kẻ giả mạo trong sự nghiệp" },
    { id: 32, text: "Changing Nature of Relationships Online", desc: "Sự thay đổi bản chất mối quan hệ thời đại số" },
    { id: 33, text: "Philanthropy: Altruism vs PR Strategy", desc: "Hoạt động từ thiện: Lòng vị tha hay chiến lược PR?" },
    { id: 34, text: "Science of Memory Formation & Recall", desc: "Cơ chế hình thành và khôi phục ký ức trí não" },
    { id: 35, text: "Ethical Dilemmas in Autonomous Cars", desc: "Thách thức đạo đức xe tự lái trong giao thông" },
    { id: 36, text: "Subconscious Mind in Problem Solving", desc: "Vai trò tiềm thức trong giải quyết vấn đề phức tạp" },
    { id: 37, text: "Redefining Success Beyond Money", desc: "Định nghĩa lại thành công vượt ngoài thước đo tài chính" },
    { id: 38, text: "Dynamics of Digital Social Movements", desc: "Động lực các phong trào xã hội trong kỷ nguyên số" },
    { id: 39, text: "Role of Satire in Political Discourse", desc: "Châm biếm và trào phúng trong phản biện chính trị" },
    { id: 40, text: "Navigating Intergenerational Workplace", desc: "Hòa hợp khoảng cách thế hệ trong môi trường làm việc" },
    { id: 41, text: "Impact of Fast Fashion on Labor", desc: "Mặt tối của thời trang nhanh đối với người lao động" },
    { id: 42, text: "Biophilia: Why Humans Need Nature", desc: "Giả thuyết Biophilia: Vì sao con người khát khao thiên nhiên?" },
    { id: 43, text: "Mechanics of Economic Inflation", desc: "Cơ chế lạm phát và sức mua của đồng tiền" },
    { id: 44, text: "Cognitive Flexibility in Changing World", desc: "Sự linh hoạt nhận thức thích ứng biến động" },
    { id: 45, text: "Paradox of Perfectionism at Work", desc: "Nghịch lý chủ nghĩa hoàn hảo cản trở thành công" },
    { id: 46, text: "How Music Triggers Deep Memory", desc: "Tại sao âm nhạc khơi gợi ký ức mạnh mẽ?" },
    { id: 47, text: "Future of Renewable Energy Microgrids", desc: "Mạng lưới điện tái tạo vi mô cho tương lai" },
    { id: 48, text: "Philosophy of Time: Perception vs Reality", desc: "Triết học về thời gian: Cảm nhận và thực tại" },
    { id: 49, text: "Restorative vs Retributive Justice", desc: "Tư pháp phục hồi và Tư pháp trừng phạt" },
    { id: 50, text: "Science of Sleep Cycles and Peak Output", desc: "Chu kỳ sinh học giấc ngủ và tối ưu hiệu suất" }
  ],

  c1: [
    { id: 1, text: "Deconstructing Epistemology & Truth", desc: "Giải mã Bản thể luận: Làm sao ta biết điều ta biết là đúng?" },
    { id: 2, text: "Ephemeral Nature of Digital Archives", desc: "Sự mong mong của kho lưu trữ số và ký ức văn hóa" },
    { id: 3, text: "Algorithmic Governance & Democracy", desc: "Quản trị thuật toán và nguy cơ xói mòn dân chủ" },
    { id: 4, text: "Psychoanalysis of Modern Consumerism", desc: "Phân tâm học về tiêu dùng: Ham muốn do truyền thông tạo ra" },
    { id: 5, text: "Semiotics of Architecture & Urban Space", desc: "Ký hiệu học kiến trúc và ngôn ngữ không gian đô thị" },
    { id: 6, text: "Quantum Supremacy & Cryptography", desc: "Vượt ngưỡng lượng tử và tương lai mật mã học" },
    { id: 7, text: "Geopolitics of Rare Earth Minerals", desc: "Địa chính trị nguyên tố đất hiếm và chuyển dịch năng lượng" },
    { id: 8, text: "Universal Rights vs Cultural Relativism", desc: "Tăng đòn giữa Nhân quyền toàn cầu và Tương đối luận văn hóa" },
    { id: 9, text: "Cognitive Biases in High-Stakes Risk", desc: "Định kiến nhận thức trong quản trị rủi ro tài chính lớn" },
    { id: 10, text: "Linguistic Determinism & Reality Construct", desc: "Giả thuyết Sapir-Whorf: Ngôn ngữ có nhào nặn thực tại?" },
    { id: 11, text: "Bioethics of Neural Augmentation", desc: "Đạo đức sinh học trong cấy ghép chip não con người" },
    { id: 12, text: "Hegemonic Transition in Multipolar World", desc: "Chuyển dịch cường quyền trong trật tự thế giới đa cực" },
    { id: 13, text: "Phenomenological View of Consciousness", desc: "Góc nhìn Hiện tượng học về bản chất ý thức" },
    { id: 14, text: "Erosion of Nuance in Polarized Debates", desc: "Sự biến mất của chiều sâu trong tranh luận cực đoan" },
    { id: 15, text: "Post-Industrial Attention Economy", desc: "Nền kinh tế chú ý trong xã hội hậu công nghiệp" },
    { id: 16, text: "Aesthetics of Imperfection (Wabi-Sabi)", desc: "Triết lý Wabi-Sabi: Vẻ đẹp từ sự bất toàn" },
    { id: 17, text: "Entropy Metaphor in Organizations", desc: "Định luật Entropy áp dụng trong suy thoái tổ chức" },
    { id: 18, text: "Epigenetics: Environment Rewriting Genes", desc: "Di truyền ngoài gen: Môi trường biến đổi biểu hiện gen" },
    { id: 19, text: "Rhetorical Structure of Manifestos", desc: "Cấu trúc hùng biện trong các bản tuyên ngôn lịch sử" },
    { id: 20, text: "Technocratic vs Participatory Governance", desc: "Quản trị kỹ trị và Dân chủ tham gia" },
    { id: 21, text: "Paradox of Tolerance in Open Societies", desc: "Nghịch lý sự khoan dung của Karl Popper" },
    { id: 22, text: "Neuroplasticity Limits in Adult Brains", desc: "Hạn chế và tiềm năng dẻo não ở người trưởng thành" },
    { id: 23, text: "Computational Semantics in Language AI", desc: "Ngữ nghĩa học tính toán trong mô hình ngôn ngữ AI" },
    { id: 24, text: "Subtleties of Unconscious Social Signals", desc: "Các tín hiệu giao tiếp phi ngôn ngữ vô thức" },
    { id: 25, text: "Macroeconomic Policy Trilemma", desc: "Bộ ba bất khả thi trong chính sách kinh tế vĩ mô" },
    { id: 26, text: "Philosophy of Mind: Functionalism & Qualia", desc: "Triết học trí tuệ: Thuyết chức năng và Cảm quan Qualia" },
    { id: 27, text: "Institutional Drift & Bureaucratic Decay", desc: "Xói mòn thể chế và suy thoái bộ máy hành chính" },
    { id: 28, text: "Microbiome Ecology & Human Immunity", desc: "Hệ sinh thái vi sinh vật và khả năng miễn dịch con người" },
    { id: 29, text: "Hegelian Dialectics in History", desc: "Phép biện chứng Hegel trong các phong trào lịch sử" },
    { id: 30, text: "Synthetic Biology & Ecosystem Design", desc: "Sinh học tổng hợp và tái thiết kế hệ sinh thái" },
    { id: 31, text: "Ethics of Predictive Algorithms", desc: "Đạo đức của thuật toán dự báo tội phạm" },
    { id: 32, text: "Existential Risk in Frontier Tech", desc: "Đánh giá rủi ro tồn vong từ công nghệ tiên phong" },
    { id: 33, text: "Jurisprudence of Maritime Boundaries", desc: "Lý luận pháp lý trong phân định ranh giới biển quốc tế" },
    { id: 34, text: "Cybernetic Feedback Loops in Society", desc: "Vòng phản hồi điều khiển học trong hệ thống xã hội" },
    { id: 35, text: "Hermeneutics of Literary Interpretation", desc: "Thông giải học trong phân tích tác phẩm văn học" },
    { id: 36, text: "Deepfakes and Collapse of Visual Truth", desc: "Công nghệ Deepfake và sự sụp đổ của bằng chứng thị giác" },
    { id: 37, text: "Psychology of Mass Hysteria", desc: "Tâm lý học về hiện tượng cuồng loạn đám đông" },
    { id: 38, text: "Resource Allocation in Extreme Crisis", desc: "Mô hình phân bổ nguồn lực trong khủng hoảng cấp bách" },
    { id: 39, text: "Epistemic Communities in Global Science", desc: "Cộng đồng tri thức trong hợp tác khoa học toàn cầu" },
    { id: 40, text: "Deconstructive Analysis of Postmodern Art", desc: "Phân tích giải cấu trúc trong nghệ thuật hậu hiện đại" },
    { id: 41, text: "Behavioral Economics & Nudge Theory", desc: "Kinh tế học hành vi và Thuyết Cú hích trong chính sách" },
    { id: 42, text: "Geopolitics of Semiconductor Supply", desc: "Địa chính trị chuỗi cung ứng bán dẫn toàn cầu" },
    { id: 43, text: "Metaphysics of Identity Across Time", desc: "Siêu hình học về sự đồng nhất của bản thể qua thời gian" },
    { id: 44, text: "Quantum Entanglement & Non-Locality", desc: "Vướng víu lượng tử và hiện tượng phi vị trí vật lý" },
    { id: 45, text: "Philosophy of Language: Sense & Reference", desc: "Triết học ngôn ngữ: Hàm nghĩa và Vật chỉ phối" },
    { id: 46, text: "Socio-Economic Stratification in Megacities", desc: "Phân tầng xã hội kinh tế tại các siêu đô thị" },
    { id: 47, text: "Structural Mechanics of Financial Crises", desc: "Cơ cấu hệ thống dẫn tới khủng hoảng tài chính toàn cầu" },
    { id: 48, text: "Biopolitics and State Surveillance", desc: "Chính trị sinh học và cơ chế giám sát nhà nước" },
    { id: 49, text: "Evolutionary Biology of Altruism", desc: "Sinh học tiến hóa về hành vi vị tha" },
    { id: 50, text: "Transcendental Idealism of Immanuel Kant", desc: "Chủ nghĩa duy tâm siêu việt trong Triết học Kant" }
  ],

  c2: [
    { id: 1, text: "Ontological Paradoxes of Quantum Mechanics", desc: "Nghịch lý bản thể luận trong Cơ học lượng tử và Lưỡng tính sóng-hạt" },
    { id: 2, text: "Hegemonic Stability & Global Trade", desc: "Thuyết ổn định cường quyền và sự đứt gãy thương mại toàn cầu" },
    { id: 3, text: "Teleological Ethics vs Deontological Systems", desc: "Đạo đức mục đích luận và Nghĩa vụ luận trong AI sinh học" },
    { id: 4, text: "Machine Learning as Epistemic Agent", desc: "Máy học như một chủ thể nhận thức luận phi con người" },
    { id: 5, text: "Geopolitical Economy of Outer Space", desc: "Địa chính trị kinh tế không gian vũ trụ và khai thác tài nguyên" },
    { id: 6, text: "Linguistic Relativity & Semantic Loss", desc: "Tương đối luận ngôn ngữ và sự thất thoát ngữ nghĩa khi dịch thuật" },
    { id: 7, text: "Post-Structuralist Canon Formation", desc: "Phân tích hậu cấu trúc về quá trình hình thành quy chuẩn văn học" },
    { id: 8, text: "Illusion of Free Will in Neuro-Philosophy", desc: "Ảo tưởng về Tự do ý chí dưới góc nhìn Triết học thần kinh" },
    { id: 9, text: "Macro-Financial Stability in Fragmentation", desc: "Ổn định tài chính vĩ mô trước sự rạn nứt địa chính trị" },
    { id: 10, text: "Hermeneutics of Suspicion: Marx & Nietzsche", desc: "Thông giải học hoài nghi: Di sản của Marx, Nietzsche & Freud" },
    { id: 11, text: "Commodification of Human Genomic Data", desc: "Chính trị sinh học và sự thương mại hóa dữ liệu gen người" },
    { id: 12, text: "Rhetorical Mechanics of Judicial Dissent", desc: "Cơ chế hùng biện trong các ý kiến bất đồng tại Tòa án Hiến pháp" },
    { id: 13, text: "Thermodynamic Systems in Ecological Collapse", desc: "Lý thuyết hệ thống nhiệt động lực học trong suy thoái sinh thái" },
    { id: 14, text: "Aesthetics of Sublime in Modern Literature", desc: "Mỹ học về Cái cao cả (Sublime) trong văn học triết học thế kỷ 20" },
    { id: 15, text: "Algorithmic Bias in Autonomous Weapons", desc: "Định kiến thuật toán trong vũ khí tự hành quân sự" },
    { id: 16, text: "Dialectic of Enlightenment & Self-Destruction", desc: "Biện chứng của Khai sáng: Tính lý trí và nguy cơ tự hủy" },
    { id: 17, text: "Holographic Principle in Theoretical Physics", desc: "Nguyên lý toàn ảnh trong Vật lý lý thuyết lượng tử" },
    { id: 18, text: "Epistemic Closure in Technocratic Elites", desc: "Xã hội học về sự khép kín nhận thức trong giới tinh hoa" },
    { id: 19, text: "Cybernetic Self-Organizing Ecosystems", desc: "Điều khiển học trong các hệ sinh thái tự tổ chức độc lập" },
    { id: 20, text: "Mathematical Platonism vs Formalism", desc: "Nền tảng siêu hình học: Chủ nghĩa Platon hay Thuyết hình thức toán" },
    { id: 21, text: "Deconstructing Myth of Tech Neutrality", desc: "Giải cấu trúc huyền thoại về tính trung lập của công nghệ" },
    { id: 22, text: "Evolutionary Neurobiology of Morality", desc: "Sinh học thần kinh tiến hóa về bản năng đạo đức con người" },
    { id: 23, text: "Mechanics of Hyper-Inflationary Collapses", desc: "Động lực học của sự sụp đổ siêu lạm phát qua lịch sử" },
    { id: 24, text: "Husserl's Internal Time Consciousness", desc: "Hiện tượng học về ý thức thời gian nội tại của Husserl" },
    { id: 25, text: "Synthetic Genomics & Creating Life", desc: "Genomics tổng hợp: Đạo đức tạo ra sự sống nhân tạo từ con số 0" },
    { id: 26, text: "Transformation of Public Sphere in AI Era", desc: "Sự biến đổi cấu trúc của Miền công cộng trong kỷ nguyên thuật toán" },
    { id: 27, text: "Common Law vs Civil Law Positivism", desc: "Thực chứng luận pháp lý: Thông luật (Common Law) và Dân luật (Civil Law)" },
    { id: 28, text: "Macro-Historical Patterns of Collapse", desc: "Mô hình lịch sử vĩ mô về sự sụp đổ văn minh: Tainter & Spengler" },
    { id: 29, text: "Quantum Thermodynamics & Arrow of Time", desc: "Nhiệt động lực học lượng tử và Mũi tên thời gian" },
    { id: 30, text: "Semiotics of Digital Identity Disassociation", desc: "Ký hiệu học về sự đứt gãy bản sắc trong nhân dạng số" },
    { id: 31, text: "Philosophical Pessimism & Nihilism", desc: "Chủ nghĩa bi quan triết học: Schopenhauer, Cioran & Hư vô luận" },
    { id: 32, text: "IP Monopolies vs Open-Source Frontiers", desc: "Độc quyền sở hữu trí tuệ và Ranh giới nguồn mở" },
    { id: 33, text: "Neuro-Law: Brain Evidence in Culprit Legal", desc: "Pháp lý thần kinh: Bằng chứng hình ảnh não trước tòa án" },
    { id: 34, text: "Geopolitics of Transboundary Water Disputes", desc: "Địa chính trị tranh chấp nguồn nước xuyên biên giới" },
    { id: 35, text: "Social Stratification in Post-Scarcity", desc: "Phân tầng xã hội trong tương lai lý thuyết hậu khan hiếm" },
    { id: 36, text: "Ontological Security in Rapid Disruption", desc: "An ninh bản thể luận trong thời kỳ đứt gãy văn minh nhanh" },
    { id: 37, text: "Structural Mechanics of Language Shift", desc: "Cơ chế cấu trúc dẫn tới sự chuyển dịch và tuyệt chủng ngôn ngữ" },
    { id: 38, text: "Gödel's Incompleteness Theorems", desc: "Định lý bất toàn của Gödel trong Triết học Toán học" },
    { id: 39, text: "Ethics of Mind Uploading & Post-Human", desc: "Đạo đức tải trí tuệ lên đám mây và sự sống Hậu sinh học" },
    { id: 40, text: "Kuhn's Paradigm Shifts Mechanics", desc: "Nghệ thuật chuyển đổi nhận thức: Cơ chế bước ngoặt của Thomas Kuhn" },
    { id: 41, text: "Macroeconomic Game Theory in Tariff Wars", desc: "Lý thuyết trò chơi vĩ mô trong chiến tranh thuế quan đa phương" },
    { id: 42, text: "Phenomenology of Trauma & Somatic Memory", desc: "Hiện tượng học về chấn thương và Ký ức thể chất" },
    { id: 43, text: "Deep-Sea Mining & Benthic Vulnerability", desc: "Khai thác khoáng sản đáy biển sâu và nguy cơ sinh thái" },
    { id: 44, text: "Surveillance Capitalism of Zuboff", desc: "Kinh tế chính trị học về Chủ nghĩa tư bản giám sát của Zuboff" },
    { id: 45, text: "Deconstructive Philosophy of Law (Derrida)", desc: "Triết học giải cấu trúc về Luật pháp và Lực lượng của Derrida" },
    { id: 46, text: "Physics of Cosmological Inflation", desc: "Vật lý về sự lạm phát vũ trụ và Giả thuyết Đa vũ trụ" },
    { id: 47, text: "Cognitive Archaeology of Prehistoric Mind", desc: "Khảo cổ học nhận thức về tư duy con người tiền sử" },
    { id: 48, text: "Cybernetics of Global Supply Resilience", desc: "Điều khiển học trong sức chống chịu chuỗi cung ứng toàn cầu" },
    { id: 49, text: "Transcendental Phenomenology & Epoché", desc: "Hiện tượng học siêu việt: Tính ý hướng và Phương pháp Epoché" },
    { id: 50, text: "Final Horizon: Entropy & Fate of Cosmos", desc: "Ranh giới vĩnh hằng: Entropy, Cái chết nhiệt và Số phận vũ trụ" }
  ]
};
