export const MORAL_SYLLABUS = {
  self_help: [
    { id: 1, text: "Kiên trì sẽ luôn được đền đáp xứng đáng", desc: "Sức mạnh của việc không bỏ cuộc trước khó khăn" },
    { id: 2, text: "Kỷ luật bản thân là chìa khóa của tự do", desc: "Làm chủ hành động để làm chủ tương lai" },
    { id: 3, text: "Thất bại hôm nay là học phí cho thành công ngày mai", desc: "Xem trở ngại là cơ hội học hỏi quý giá" },
    { id: 4, text: "Mỗi ngày tiến bộ 1% sau một năm sẽ thay đổi kinh ngạc", desc: "Tích lũy những thay đổi nhỏ làm nên kỳ tích" },
    { id: 5, text: "Đừng so sánh chương 1 của mình với chương 20 của người khác", desc: "Tập trung vào hành trình của riêng bạn" },
    { id: 6, text: "Giới hạn duy nhất là những gì bạn tự đặt ra", desc: "Vượt qua rào cản tâm lý để bứt phá" },
    { id: 7, text: "Thức dậy với mục tiêu, đi ngủ với sự hài lòng", desc: "Sống có định hướng rõ ràng mỗi ngày" },
    { id: 8, text: "Thành công không đến từ sự ngẫu hứng, nó đến từ sự đều đặn", desc: "Giá trị của thói quen và sự nhất quán" },
    { id: 9, text: "Khi muốn bỏ cuộc, hãy nhớ lý do bạn bắt đầu", desc: "Định vị lại động lực cốt lõi khi mệt mỏi" },
    { id: 10, text: "Nỗi đau của sự kỷ luật nhẹ hơn nỗi đau của sự hối hận", desc: "Lựa chọn cái giá để trưởng thành" },
    { id: 11, text: "Bắt đầu từ nơi bạn đứng, sử dụng những gì bạn có", desc: "Hành động ngay thay vì chờ đợi sự hoàn hảo" },
    { id: 12, text: "Đừng đợi cơ hội xuất hiện, hãy tự tạo ra nó", desc: "Tinh thần chủ động nắm giữ vận mệnh" },
    { id: 13, text: "Bạn là trung bình cộng của 5 người bạn dành thời gian nhiều nhất", desc: "Lựa chọn môi trường và các mối quan hệ tích cực" },
    { id: 14, text: "Việc hôm nay chớ để ngày mai", desc: "Đập tan thói quen trì hoãn phá hủy cơ hội" },
    { id: 15, text: "Học cách nói không với những thứ làm xao nhãng mục tiêu", desc: "Bảo vệ sự tập trung của bản thân" },
    { id: 16, text: "Tập trung vào quá trình, kết quả tự khắc sẽ đến", desc: "Không nóng vội, làm tốt từng bước nhỏ" },
    { id: 17, text: "Sự kiên nhẫn có thể biến lá dâu thành tơ lụa", desc: "Thời gian là người đồng minh tốt nhất" },
    { id: 18, text: "Không có lối đi tắt nào cho những nơi thực sự đáng đến", desc: "Tôn trọng quy luật nhân quả của nỗ lực" },
    { id: 19, text: "Người kiên trì là người không bao giờ bị đánh bại", desc: "Sức mạnh ý chí bền bỉ theo năm tháng" },
    { id: 20, text: "Trực giác mách bảo con đường, hành động tạo ra đích đến", desc: "Kết hợp tư duy nhạy bén và hành động quyết liệt" },
    { id: 21, text: "Thói quen tốt tạo nên cuộc đời tốt", desc: "Xây dựng nền móng cuộc sống vững chắc" },
    { id: 22, text: "Hãy làm việc trong im lặng và để thành công lên tiếng", desc: "Hành động âm thầm tạo kết quả vang dội" },
    { id: 23, text: "Đừng sợ đi chậm, chỉ sợ đứng yên", desc: "Duy trì quán tính tiến bước mỗi ngày" },
    { id: 24, text: "Quản lý thời gian tốt là quản lý cuộc đời tốt", desc: "Tối ưu hóa tài nguyên quý giá nhất" },
    { id: 25, text: "Mọi thay đổi lớn đều bắt đầu từ một quyết định nhỏ", desc: "Dũng cảm thực hiện bước ngoặt đầu tiên" },
    { id: 26, text: "Khó khăn chỉ là phép thử cho lòng kiên nhẫn", desc: "Trui rèn bản lĩnh qua sóng gió" },
    { id: 27, text: "Đầu tư vào bản thân là khoản đầu tư sinh lời nhất", desc: "Nâng cao tri thức và kỹ năng sống" },
    { id: 28, text: "Thái độ tích cực quyết định độ cao của thành công", desc: "Nhìn nhận thế giới bằng lăng kính lạc quan" },
    { id: 29, text: "Muốn đi nhanh thì đi một mình, muốn đi xa hãy kiên trì", desc: "Đồng hành bền bỉ vượt thời gian" },
    { id: 30, text: "Vượt qua vùng an toàn là nơi phép màu bắt đầu", desc: "Thách thức bản thân ở lĩnh vực mới" },
    { id: 31, text: "Đừng cầu nguyện cho cuộc sống dễ dàng, hãy cầu nguyện để mạnh mẽ hơn", desc: "Tôi luyện nội lực vững vàng" },
    { id: 32, text: "Mọi thành quả lớn đều cần thời gian tích lũy", desc: "Không đốt cháy giai đoạn gieo trồng" },
    { id: 33, text: "Sự chú ý là tài sản quý giá nhất của bạn", desc: "Tránh xa cạm bẫy xao nhãng của công nghệ" },
    { id: 34, text: "Hãy là phiên bản tốt nhất của chính mình hôm nay", desc: "Chỉ cạnh tranh với chính mình hôm qua" },
    { id: 35, text: "Chiến thắng bản thân là chiến thắng hiển hách nhất", desc: "Kiểm soát phần lười biếng và bản năng" },
    { id: 36, text: "Đọc sách là cách nhanh nhất để đứng trên vai người khổng lồ", desc: "Khai thác kho tàng trí tuệ nhân loại" },
    { id: 37, text: "Nghĩ lớn, bắt đầu nhỏ, hành động ngay lập tức", desc: "Chiến thuật triển khai dự án hiệu quả" },
    { id: 38, text: "Mỗi vết sẹo đều mang lại một bài học trưởng thành", desc: "Chữa lành và đứng dậy mạnh mẽ hơn" },
    { id: 39, text: "Đừng lãng phí năng lượng vào những việc không thể thay đổi", desc: "Học cách buông bỏ và tập trung hiện tại" },
    { id: 40, text: "Sự tập trung là sức mạnh tối thượng", desc: "Dành toàn lực cho một mục tiêu duy nhất" },
    { id: 41, text: "Không có thất bại thực sự, chỉ có bài học kinh nghiệm", desc: "Thay đổi góc nhìn về những lần vấp ngã" },
    { id: 42, text: "Niềm tin là bước đi đầu tiên ngay cả khi chưa thấy toàn bộ cầu thang", desc: "Dũng cảm bước đi bằng niềm tin nội tâm" },
    { id: 43, text: "Làm chủ cảm xúc là làm chủ vận mệnh", desc: "Kiểm soát nóng giận để tránh sai lầm" },
    { id: 44, text: "Hãy kiên định với mục tiêu nhưng linh hoạt với phương pháp", desc: "Chiến lược thông minh để thích ứng khó khăn" },
    { id: 45, text: "Sự chuẩn bị gặp gỡ cơ hội sẽ tạo nên may mắn", desc: "Không ngừng tích lũy chờ ngày tỏa sáng" },
    { id: 46, text: "Tiền bạc đi sau giá trị trao đi", desc: "Tập trung cống hiến để nhận lại xứng đáng" },
    { id: 47, text: "Học hỏi từ người giỏi nhất để rút ngắn con đường", desc: "Tìm kiếm người cố vấn dẫn đường" },
    { id: 48, text: "Đừng sống một năm 75 lần và gọi đó là cuộc đời", desc: "Sống trải nghiệm và bứt phá thay vì lặp lại" },
    { id: 49, text: "Năng lượng tích cực sẽ thu hút những điều tích cực", desc: "Quy luật hấp dẫn của tâm thức" },
    { id: 50, text: "Hành trình vạn dặm bắt đầu từ một bước chân đầu tiên", desc: "Hành động nhỏ mở ra chặng đường lớn" }
  ],
  top_lists: [
    { id: 1, text: "Top 5 thứ tuyệt đối không nên làm khi đi du lịch nước ngoài", desc: "Tránh rắc rối luật pháp và văn hóa bản địa" },
    { id: 2, text: "Top 3 thói quen buổi sáng đang âm thầm hủy hoại sức khỏe của bạn", desc: "Thay đổi để bảo vệ năng lượng khởi đầu ngày mới" },
    { id: 3, text: "Top 4 hành động lịch sự nhưng lại cực kỳ mất điểm trong giao tiếp", desc: "Những hiểu lầm tai hại khi cố tỏ ra tế nhị" },
    { id: 4, text: "Top 5 quy tắc ngầm khi đi ăn tiệc xã giao bạn bắt buộc phải biết", desc: "Cách hành xử tinh tế giúp ghi điểm tuyệt đối" },
    { id: 5, text: "Top 3 sai lầm phổ biến khi mua đồ dùng gia đình gây lãng phí tiền bạc", desc: "Chi tiêu thông minh cho tổ ấm" },
    { id: 6, text: "Top 5 dấu hiệu cảnh báo một mối quan hệ độc hại cần tránh xa", desc: "Bảo vệ sức khỏe tinh thần của chính mình" },
    { id: 7, text: "Top 4 việc cần làm ngay lập tức khi phát hiện bị mất ví tiền", desc: "Xử lý khủng hoảng nhanh chóng, giảm thiểu thiệt hại" },
    { id: 8, text: "Top 3 sai lầm ngớ ngẩn khi phỏng vấn xin việc khiến bạn bị loại ngay", desc: "Những chi tiết nhỏ quyết định thành bại" },
    { id: 9, text: "Top 5 mẹo tiết kiệm tiền hiệu quả cho người trẻ thu nhập trung bình", desc: "Tích lũy tài sản thông minh và bền vững" },
    { id: 10, text: "Top 4 thứ không nên chia sẻ lên mạng xã hội để bảo vệ bản thân", desc: "Giữ an toàn thông tin cá nhân trên không gian số" },
    { id: 11, text: "Top 3 thói quen trước khi đi ngủ giúp bạn ngủ ngon và sâu giấc hơn", desc: "Cải thiện chất lượng giấc ngủ tự nhiên" },
    { id: 12, text: "Top 5 cách từ chối khéo léo mà không làm mất lòng người khác", desc: "Nghệ thuật từ chối nhẹ nhàng nhưng dứt khoát" },
    { id: 13, text: "Top 4 kỹ năng tự vệ cơ bản ai cũng cần biết khi đi một mình ban đêm", desc: "Đề phòng nguy hiểm và tự bảo vệ bản thân" },
    { id: 14, text: "Top 3 biểu hiện của người có EQ cao trong các cuộc tranh luận", desc: "Giao tiếp thuyết phục bằng sự điềm tĩnh" },
    { id: 15, text: "Top 5 thực phẩm quen thuộc tưởng tốt nhưng ăn nhiều lại gây hại", desc: "Cân nhắc chế độ dinh dưỡng lành mạnh" },
    { id: 16, text: "Top 4 thói quen mua sắm thông minh giúp bạn dư dả cuối tháng", desc: "Quản lý ngân sách mua sắm hiệu quả" },
    { id: 17, text: "Top 3 cách xử lý thông minh khi gặp khách hàng khó tính", desc: "Hóa giải mâu thuẫn, giữ chân khách hàng" },
    { id: 18, text: "Top 5 điều bạn nên chuẩn bị kỹ càng trước khi bước sang tuổi 30", desc: "Định hình sự nghiệp và tài chính vững vàng" },
    { id: 19, text: "Top 4 dấu hiệu cho thấy bạn đang bị quá tải công việc (Burnout)", desc: "Lắng nghe cơ thể và dành thời gian phục hồi" },
    { id: 20, text: "Top 3 quy tắc ứng xử khi mượn tiền hoặc đồ dùng của người khác", desc: "Giữ gìn uy tín và mối quan hệ tốt đẹp" },
    { id: 21, text: "Top 5 mẹo sắp xếp hành lý siêu gọn nhẹ khi đi du lịch dài ngày", desc: "Tối ưu hóa balo hành lý thông minh" },
    { id: 22, text: "Top 4 sai lầm khi chăm sóc da mặt khiến mụn nổi nhiều hơn", desc: "Điều chỉnh thói quen dưỡng da đúng cách" },
    { id: 23, text: "Top 3 việc nên làm ngay khi chuyển đến nơi ở mới", desc: "Bắt đầu cuộc sống mới suôn sẻ" },
    { id: 24, text: "Top 5 thói quen giúp bạn duy trì năng lượng tích cực suốt cả ngày", desc: "Nạp năng lượng cho tâm trí và thể chất" },
    { id: 25, text: "Top 4 ngôn ngữ cơ thể vô tình tố cáo sự thiếu tự tin của bạn", desc: "Điều chỉnh tư thế để giao tiếp hiệu quả" },
    { id: 26, text: "Top 3 lỗi sai phổ biến khi viết CV xin việc bạn cần sửa ngay", desc: "Gây ấn tượng mạnh mẽ với nhà tuyển dụng" },
    { id: 27, text: "Top 5 điều cấm kỵ khi nói chuyện với người mới quen lần đầu", desc: "Tránh tạo ấn tượng xấu ban đầu" },
    { id: 28, text: "Top 4 thói quen ăn uống đang làm chậm quá trình giảm cân của bạn", desc: "Tối ưu hóa chế độ dinh dưỡng hàng ngày" },
    { id: 29, text: "Top 3 cách đối phó với những lời chỉ trích tiêu cực từ đồng nghiệp", desc: "Xử lý thông minh trước thị phi công sở" },
    { id: 30, text: "Top 5 kỹ năng giao tiếp giúp bạn dễ dàng kết bạn ở môi trường mới", desc: "Hòa nhập nhanh chóng và tự nhiên" },
    { id: 31, text: "Top 4 đồ vật không nên để trong xe ô tô dưới trời nắng nóng", desc: "Phòng tránh cháy nổ và hỏng hóc đồ đạc" },
    { id: 32, text: "Top 3 quy tắc ngầm khi sử dụng thang máy ở nơi công sở", desc: "Lịch sự văn minh tại tòa nhà văn phòng" },
    { id: 33, text: "Top 5 thói quen chi tiêu đang khiến bạn mãi không có tiền tiết kiệm", desc: "Nhận diện những khoản chi vô ích ngầm" },
    { id: 34, text: "Top 4 việc nên làm trước khi quyết định đầu tư vào bất cứ lĩnh vực nào", desc: "Giảm thiểu rủi ro mất tiền oan" },
    { id: 35, text: "Top 3 dấu hiệu cho thấy điện thoại của bạn đang bị theo dõi", desc: "Bảo mật thông tin thiết bị cá nhân" },
    { id: 36, text: "Top 5 sai lầm khi quản lý tài chính cá nhân ở tuổi đôi mươi", desc: "Tránh nợ nần và xây dựng tài sản sớm" },
    { id: 37, text: "Top 4 cách rèn luyện tư duy phản biện trong học tập và công việc", desc: "Nâng cao năng lực phân tích vấn đề độc lập" },
    { id: 38, text: "Top 3 mẹo giúp giảm căng thẳng cực nhanh trong vòng 5 phút", desc: "Lấy lại bình tĩnh và cân bằng tức thì" },
    { id: 39, text: "Top 5 điều cần kiểm tra kỹ trước khi rời khỏi phòng khách sạn", desc: "Tránh bỏ quên tài sản quan trọng" },
    { id: 40, text: "Top 4 quy tắc an toàn khi sử dụng thẻ tín dụng để tránh mất tiền", desc: "Bảo vệ thông tin tài chính cá nhân" },
    { id: 41, text: "Top 3 thói quen giúp cải thiện trí nhớ cực kỳ hiệu quả", desc: "Rèn luyện bộ não sắc bén mỗi ngày" },
    { id: 42, text: "Top 5 việc không nên làm ngay sau khi ăn no để bảo vệ dạ dày", desc: "Bảo vệ hệ tiêu hóa hoạt động khỏe mạnh" },
    { id: 43, text: "Top 4 cách nhận biết một trang web lừa đảo trực tuyến", desc: "Tránh mất mát thông tin tài khoản và tiền bạc" },
    { id: 44, text: "Top 3 kỹ năng giao tiếp quan trọng nhất mà trường học không dạy bạn", desc: "Trang bị hành trang ứng xử thực tế cuộc sống" },
    { id: 45, text: "Top 5 món đồ công nghệ đáng tiền nhất giúp tăng hiệu suất làm việc", desc: "Lựa chọn công cụ hỗ trợ công việc thông minh" },
    { id: 46, text: "Top 4 sai lầm khi tập thể dục khiến bạn dễ bị chấn thương", desc: "Rèn luyện cơ thể an toàn và khoa học" },
    { id: 47, text: "Top 3 thói quen giúp giữ nhà cửa luôn gọn gàng mà không tốn công dọn", desc: "Duy trì không gian sống sạch sẽ tự động" },
    { id: 48, text: "Top 5 điều bạn sẽ hối hận nếu không làm khi còn trẻ", desc: "Sống trọn vẹn và ý nghĩa từng phút giây" },
    { id: 49, text: "Top 4 mẹo nói chuyện trước đám đông giúp bạn bớt run và tự tin hơn", desc: "Làm chủ bục giảng và thuyết trình cuốn hút" },
    { id: 50, text: "Top 3 quy tắc vàng khi thảo luận công việc nhóm để tránh xung đột", desc: "Làm việc nhóm hiệu quả và gắn kết" }
  ],
  rules_of_life: [
    { id: 1, text: "Quy tắc giao tiếp tế nhị với lãnh đạo khi bất đồng ý kiến", desc: "Trình bày quan điểm thông minh, tôn trọng cấp trên" },
    { id: 2, text: "Cách cư xử lịch thiệp khi nhận được món quà bạn không thích", desc: "Tôn trọng tấm lòng người tặng, ứng xử tinh tế" },
    { id: 3, text: "Quy tắc ứng xử khi đồng nghiệp nói xấu sau lưng người khác", desc: "Tránh xa thị phi và giữ thái độ trung lập chuyên nghiệp" },
    { id: 4, text: "Cách xử lý thông minh khi vô tình làm đổ đồ uống tại bữa tiệc", desc: "Giữ bình tĩnh, xử lý khéo léo để không gây chú ý tiêu cực" },
    { id: 5, text: "Quy tắc giới thiệu người khác trong lần đầu gặp mặt xã giao", desc: "Thứ tự giới thiệu tôn trọng cấp bậc và tuổi tác" },
    { id: 6, text: "Quy tắc vàng khi trả lời điện thoại trong không gian làm việc chung", desc: "Giữ âm lượng vừa phải, tôn trọng sự tập trung của đồng nghiệp" },
    { id: 7, text: "Cách ứng xử khéo léo khi bị người khác hỏi những câu hỏi quá riêng tư", desc: "Đánh lạc hướng nhẹ nhàng, bảo vệ không gian cá nhân" },
    { id: 8, text: "Quy tắc ăn uống lịch sự khi đi ăn tối cùng đối tác làm ăn", desc: "Những cử chỉ bàn ăn tối thiểu của người lịch thiệp" },
    { id: 9, text: "Cách cư xử văn minh khi xếp hàng ở nơi công cộng bị chen hàng", desc: "Nhắc nhở nhẹ nhàng, giữ bình tĩnh ứng xử" },
    { id: 10, text: "Quy tắc ứng xử khi bạn trễ hẹn để giữ uy tín cá nhân", desc: "Thông báo sớm, xin lỗi chân thành và đề xuất giải pháp" },
    { id: 11, text: "Cách xin lỗi chân thành và chuyên nghiệp trong công việc", desc: "Nhận trách nhiệm và đưa ra kế hoạch khắc phục rõ ràng" },
    { id: 12, text: "Quy tắc chúc mừng đồng nghiệp được thăng chức mà không mang tiếng nịnh bợ", desc: "Chúc mừng chân thành dựa trên thành quả thực tế" },
    { id: 13, text: "Cách cư xử khi bạn là người duy nhất không đồng tình trong cuộc họp", desc: "Trình bày lý do logic thay vì tranh cãi cảm xúc" },
    { id: 14, text: "Quy tắc gửi email công việc chuyên nghiệp và lịch sự", desc: "Bố cục rõ ràng, câu từ ngắn gọn và tôn trọng" },
    { id: 15, text: "Cách ứng xử khi bạn vô tình nghe thấy bí mật của sếp hoặc đồng nghiệp", desc: "Giữ im lặng tuyệt đối, tập trung vào công việc riêng" },
    { id: 16, text: "Quy tắc ứng xử khi đi nhờ xe của người khác để luôn được chào đón", desc: "Lịch sự, chủ động chia sẻ chi phí và giữ vệ sinh xe" },
    { id: 17, text: "Cách cư xử tinh tế khi từ chối lời mời ăn tối từ đối tác", desc: "Nêu lý do hợp lý và đề xuất một lịch hẹn phù hợp khác" },
    { id: 18, text: "Quy tắc giao tiếp bằng mắt để tạo lòng tin mà không gây khó chịu", desc: "Nghệ thuật duy trì ánh mắt tự nhiên và vừa vặn" },
    { id: 19, text: "Cách ứng xử khi bạn nhận ra mình đã nói sai điều gì đó trong cuộc trò chuyện", desc: "Chủ động đính chính nhẹ nhàng, tiếp tục mạch truyện" },
    { id: 20, text: "Quy tắc ứng xử khi sử dụng mạng xã hội của công ty", desc: "Bảo vệ uy tín tập thể và hình ảnh thương hiệu công việc" },
    { id: 21, text: "Cách cư xử lịch sự khi nhận được lời khen ngợi từ cấp trên", desc: "Đón nhận khiêm tốn và chia sẻ thành tích cùng đội ngũ" },
    { id: 22, text: "Quy tắc thảo luận về lương thưởng một cách khéo léo với nhân sự", desc: "Chuẩn bị dẫn chứng giá trị đóng góp thay vì đòi hỏi cảm tính" },
    { id: 23, text: "Cách phản hồi lịch sự trước những lời khuyên không mong muốn", desc: "Cảm ơn lịch sự và giữ vững quan điểm riêng" },
    { id: 24, text: "Quy tắc ứng xử khi bạn cần mượn văn phòng phẩm của đồng nghiệp", desc: "Xin phép trước, hoàn trả đúng hẹn và bảo quản tốt" },
    { id: 25, text: "Cách cư xử đúng mực khi tham gia chuyến dã ngoại của công ty", desc: "Thoải mái giao lưu nhưng giữ chừng mực chuyên nghiệp" },
    { id: 26, text: "Quy tắc bắt tay lịch sự và tự tin trong các cuộc gặp gỡ đối tác", desc: "Cường độ và thời gian bắt tay tạo thiện cảm tốt" },
    { id: 27, text: "Cách ứng xử khi bạn gặp lại người quen cũ nhưng quên mất tên họ", desc: "Chào hỏi nồng nhiệt và khéo léo hỏi lại thông tin" },
    { id: 28, text: "Quy tắc chia sẻ tủ lạnh chung và lò vi sóng tại văn phòng", desc: "Tôn trọng đồ ăn của người khác, dọn dẹp sau khi dùng" },
    { id: 29, text: "Cách cư xử văn minh khi tài xế công nghệ đi sai đường hoặc thái độ kém", desc: "Phản hồi nhẹ nhàng thông qua đánh giá ứng dụng" },
    { id: 30, text: "Quy tắc ứng xử khi bạn muốn xin nghỉ phép đột xuất vì việc gia đình", desc: "Bàn giao công việc rõ ràng, xin lỗi vì sự bất tiện" },
    { id: 31, text: "Cách xử lý khi bạn bị sếp phê bình trực tiếp trước mặt đồng nghiệp", desc: "Lắng nghe cầu thị, giải thích riêng tư sau cuộc họp" },
    { id: 32, text: "Quy tắc ứng xử khi tham dự một đám tang hoặc lễ chia buồn", desc: "Kính cẩn, trang phục trang nhã, tránh cười đùa xôn xao" },
    { id: 33, text: "Cách cư xử khi bạn muốn nhờ đồng nghiệp giúp đỡ công việc cá nhân", desc: "Hỏi ý kiến lịch sự, không ép buộc và sẵn sàng hỗ trợ lại" },
    { id: 34, text: "Quy tắc lịch sự khi sử dụng tai nghe tại văn phòng làm việc", desc: "Vẫn chú ý xung quanh khi đồng nghiệp cần gọi" },
    { id: 35, text: "Cách từ chối uống rượu bia tại các bữa tiệc công việc một cách khéo léo", desc: "Nêu lý do sức khỏe hoặc lái xe an toàn thuyết phục" },
    { id: 36, text: "Quy tắc chúc mừng sinh nhật sếp một cách tinh tế và trang trọng", desc: "Lời chúc lịch thiệp, ý nghĩa và tránh phô trương" },
    { id: 37, text: "Cách ứng xử khi bạn phát hiện lỗi sai trong báo cáo của đồng nghiệp", desc: "Góp ý riêng tư nhẹ nhàng để đồng nghiệp tự sửa" },
    { id: 38, text: "Quy tắc ứng xử khi bạn muốn rời khỏi một cuộc trò chuyện tẻ nhạt", desc: "Khéo léo lấy lý do công việc hoặc nước uống để ngắt mạch" },
    { id: 39, text: "Cách cư xử tinh tế khi đi ăn cùng nhóm và chia hóa đơn", desc: "Chủ động thanh toán phần của mình sòng phẳng, nhanh chóng" },
    { id: 40, text: "Quy tắc phản hồi tin nhắn công việc ngoài giờ hành chính", desc: "Thiết lập ranh giới lịch sự cho cuộc sống cá nhân" },
    { id: 41, text: "Cách ứng xử khi bạn nhận được phản hồi tiêu cực từ khách hàng", desc: "Lắng nghe khiếu nại, xoa dịu cảm xúc và đưa ra hướng xử lý" },
    { id: 42, text: "Quy tắc lịch sự khi mượn sách hoặc tài liệu của người khác", desc: "Bảo quản sạch sẽ, trả lại đúng thời gian đã hứa" },
    { id: 43, text: "Cách cư xử khi bạn phải làm việc nhóm với người bạn không thích", desc: "Đặt công việc lên trên cảm xúc cá nhân" },
    { id: 44, text: "Quy tắc ứng xử khi bạn muốn phản bác ý kiến của sếp trong cuộc họp", desc: "Đưa ra bằng chứng khách quan thay vì phản đối chủ quan" },
    { id: 45, text: "Cách cư xử lịch tế khi đi thang máy cùng ban lãnh đạo công ty", desc: "Chào hỏi lễ phép, nhường đường sếp đi trước" },
    { id: 46, text: "Quy tắc giữ khoảng cách cá nhân phù hợp khi nói chuyện xã giao", desc: "Tránh đứng quá gần gây ngột ngạt cho người đối diện" },
    { id: 47, text: "Cách ứng xử khi đồng nghiệp mượn đồ nhưng quên trả nhiều lần", desc: "Nhắc nhở hài hước nhẹ nhàng để lấy lại món đồ" },
    { id: 48, text: "Quy tắc ứng xử văn minh khi sử dụng nhà vệ sinh chung nơi công sở", desc: "Giữ gìn vệ sinh chung, tôn trọng không gian tập thể" },
    { id: 49, text: "Cách cư xử tinh tế khi sếp mời cơm thân mật tại nhà riêng", desc: "Đến đúng giờ, có món quà nhỏ chào chủ nhà" },
    { id: 50, text: "Quy tắc vàng để duy trì ranh giới chuyên nghiệp giữa công việc và đời tư", desc: "Sắp xếp thời gian cân bằng và tránh chia sẻ quá đà" }
  ]
};
